#!/bin/sh
python setup.py bdist_rpm --spec-only
patch dist/addie.spec addie.spec.patch

python setup.py pyuic
python setup.py sdist
mkdir -p ~/rpmbuild/SOURCES/
cp dist/addie-*.tar.gz ~/rpmbuild/SOURCES/

rpmbuild -ba dist/addie.spec
cp ~/rpmbuild/SRPMS/addie-*.src.rpm dist/
cp ~/rpmbuild/RPMS/noarch/addie-*.noarch.rpm dist/
