
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-09T10:09:26-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9b4b6bb70cb855b0f560b7405fc96244bc8bb91",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
