# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1348, 904)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(800, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1328, 837))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_44 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_44.setObjectName(_fromUtf8("verticalLayout_44"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.tabWidget_2 = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(500, 0))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.groupBox_27 = QtGui.QGroupBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_27.sizePolicy().hasHeightForWidth())
        self.groupBox_27.setSizePolicy(sizePolicy)
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.groupBox_27)
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.select_current_folder_button = QtGui.QPushButton(self.groupBox_27)
        self.select_current_folder_button.setMinimumSize(QtCore.QSize(160, 0))
        self.select_current_folder_button.setMaximumSize(QtCore.QSize(160, 16777215))
        self.select_current_folder_button.setObjectName(_fromUtf8("select_current_folder_button"))
        self.horizontalLayout_4.addWidget(self.select_current_folder_button)
        self.exp_ini_file_status = QtGui.QLabel(self.groupBox_27)
        self.exp_ini_file_status.setMinimumSize(QtCore.QSize(500, 0))
        self.exp_ini_file_status.setMaximumSize(QtCore.QSize(500, 16777215))
        self.exp_ini_file_status.setText(_fromUtf8(""))
        self.exp_ini_file_status.setObjectName(_fromUtf8("exp_ini_file_status"))
        self.horizontalLayout_4.addWidget(self.exp_ini_file_status)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_31.addLayout(self.horizontalLayout_4)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_63 = QtGui.QLabel(self.groupBox_27)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_63.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_15.addWidget(self.label_63, 3, 2, 1, 1)
        self.label_64 = QtGui.QLabel(self.groupBox_27)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_15.addWidget(self.label_64, 3, 0, 1, 1)
        self.diamond_background = QtGui.QLineEdit(self.groupBox_27)
        self.diamond_background.setToolTip(_fromUtf8(""))
        self.diamond_background.setStatusTip(_fromUtf8(""))
        self.diamond_background.setAccessibleDescription(_fromUtf8(""))
        self.diamond_background.setInputMask(_fromUtf8(""))
        self.diamond_background.setText(_fromUtf8(""))
        self.diamond_background.setPlaceholderText(_fromUtf8(""))
        self.diamond_background.setObjectName(_fromUtf8("diamond_background"))
        self.gridLayout_15.addWidget(self.diamond_background, 1, 1, 1, 1)
        self.label_65 = QtGui.QLabel(self.groupBox_27)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_15.addWidget(self.label_65, 0, 0, 1, 1)
        self.sample_background = QtGui.QLineEdit(self.groupBox_27)
        self.sample_background.setToolTip(_fromUtf8(""))
        self.sample_background.setStatusTip(_fromUtf8(""))
        self.sample_background.setAccessibleDescription(_fromUtf8(""))
        self.sample_background.setInputMask(_fromUtf8(""))
        self.sample_background.setText(_fromUtf8(""))
        self.sample_background.setPlaceholderText(_fromUtf8(""))
        self.sample_background.setObjectName(_fromUtf8("sample_background"))
        self.gridLayout_15.addWidget(self.sample_background, 4, 1, 1, 1)
        self.vanadium = QtGui.QLineEdit(self.groupBox_27)
        self.vanadium.setToolTip(_fromUtf8(""))
        self.vanadium.setStatusTip(_fromUtf8(""))
        self.vanadium.setAccessibleDescription(_fromUtf8(""))
        self.vanadium.setInputMask(_fromUtf8(""))
        self.vanadium.setText(_fromUtf8(""))
        self.vanadium.setPlaceholderText(_fromUtf8(""))
        self.vanadium.setObjectName(_fromUtf8("vanadium"))
        self.gridLayout_15.addWidget(self.vanadium, 2, 1, 1, 1)
        self.label_66 = QtGui.QLabel(self.groupBox_27)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_15.addWidget(self.label_66, 2, 0, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBox_27)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_67.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_15.addWidget(self.label_67, 1, 2, 1, 1)
        self.label_68 = QtGui.QLabel(self.groupBox_27)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_68.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_15.addWidget(self.label_68, 0, 2, 1, 1)
        self.label_69 = QtGui.QLabel(self.groupBox_27)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_69.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_15.addWidget(self.label_69, 2, 2, 1, 1)
        self.label_70 = QtGui.QLabel(self.groupBox_27)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_70.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_15.addWidget(self.label_70, 4, 2, 1, 2)
        self.label_71 = QtGui.QLabel(self.groupBox_27)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_15.addWidget(self.label_71, 1, 0, 1, 1)
        self.label_72 = QtGui.QLabel(self.groupBox_27)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_15.addWidget(self.label_72, 4, 0, 1, 1)
        self.vanadium_background = QtGui.QLineEdit(self.groupBox_27)
        self.vanadium_background.setToolTip(_fromUtf8(""))
        self.vanadium_background.setStatusTip(_fromUtf8(""))
        self.vanadium_background.setAccessibleDescription(_fromUtf8(""))
        self.vanadium_background.setInputMask(_fromUtf8(""))
        self.vanadium_background.setText(_fromUtf8(""))
        self.vanadium_background.setPlaceholderText(_fromUtf8(""))
        self.vanadium_background.setObjectName(_fromUtf8("vanadium_background"))
        self.gridLayout_15.addWidget(self.vanadium_background, 3, 1, 1, 1)
        self.diamond = QtGui.QLineEdit(self.groupBox_27)
        self.diamond.setToolTip(_fromUtf8(""))
        self.diamond.setStatusTip(_fromUtf8(""))
        self.diamond.setAccessibleDescription(_fromUtf8(""))
        self.diamond.setInputMask(_fromUtf8(""))
        self.diamond.setText(_fromUtf8(""))
        self.diamond.setPlaceholderText(_fromUtf8(""))
        self.diamond.setObjectName(_fromUtf8("diamond"))
        self.gridLayout_15.addWidget(self.diamond, 0, 1, 1, 1)
        self.verticalLayout_31.addLayout(self.gridLayout_15)
        self.horizontalLayout_51 = QtGui.QHBoxLayout()
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.label_73 = QtGui.QLabel(self.groupBox_27)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_73.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_51.addWidget(self.label_73)
        self.label_74 = QtGui.QLabel(self.groupBox_27)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_51.addWidget(self.label_74)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem1)
        self.verticalLayout_31.addLayout(self.horizontalLayout_51)
        self.verticalLayout_30.addWidget(self.groupBox_27)
        self.line_3 = QtGui.QFrame(self.tab_5)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_30.addWidget(self.line_3)
        self.horizontalLayout_52 = QtGui.QHBoxLayout()
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_75 = QtGui.QLabel(self.tab_5)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_16.addWidget(self.label_75, 0, 0, 1, 1)
        self.label_76 = QtGui.QLabel(self.tab_5)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_16.addWidget(self.label_76, 2, 0, 1, 1)
        self.label_77 = QtGui.QLabel(self.tab_5)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_16.addWidget(self.label_77, 1, 0, 1, 1)
        self.last_scan = QtGui.QLineEdit(self.tab_5)
        self.last_scan.setText(_fromUtf8(""))
        self.last_scan.setObjectName(_fromUtf8("last_scan"))
        self.gridLayout_16.addWidget(self.last_scan, 1, 1, 1, 1)
        self.first_scan = QtGui.QLineEdit(self.tab_5)
        self.first_scan.setText(_fromUtf8(""))
        self.first_scan.setObjectName(_fromUtf8("first_scan"))
        self.gridLayout_16.addWidget(self.first_scan, 0, 1, 1, 1)
        self.frequency = QtGui.QComboBox(self.tab_5)
        self.frequency.setObjectName(_fromUtf8("frequency"))
        self.frequency.addItem(_fromUtf8(""))
        self.frequency.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.frequency, 2, 1, 1, 1)
        self.verticalLayout_32.addLayout(self.gridLayout_16)
        self.horizontalLayout_52.addLayout(self.verticalLayout_32)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem2)
        self.verticalLayout_30.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtGui.QHBoxLayout()
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.groupBox_28 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_28.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_28.setObjectName(_fromUtf8("groupBox_28"))
        self.horizontalLayout_54 = QtGui.QHBoxLayout(self.groupBox_28)
        self.horizontalLayout_54.setObjectName(_fromUtf8("horizontalLayout_54"))
        self.recalibration_yes = QtGui.QRadioButton(self.groupBox_28)
        self.recalibration_yes.setObjectName(_fromUtf8("recalibration_yes"))
        self.horizontalLayout_54.addWidget(self.recalibration_yes)
        self.recalibration_no = QtGui.QRadioButton(self.groupBox_28)
        self.recalibration_no.setChecked(True)
        self.recalibration_no.setObjectName(_fromUtf8("recalibration_no"))
        self.horizontalLayout_54.addWidget(self.recalibration_no)
        self.horizontalLayout_53.addWidget(self.groupBox_28)
        self.groupBox_29 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_29.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_29.setObjectName(_fromUtf8("groupBox_29"))
        self.horizontalLayout_55 = QtGui.QHBoxLayout(self.groupBox_29)
        self.horizontalLayout_55.setObjectName(_fromUtf8("horizontalLayout_55"))
        self.renormalization_yes = QtGui.QRadioButton(self.groupBox_29)
        self.renormalization_yes.setObjectName(_fromUtf8("renormalization_yes"))
        self.horizontalLayout_55.addWidget(self.renormalization_yes)
        self.renormalization_no = QtGui.QRadioButton(self.groupBox_29)
        self.renormalization_no.setChecked(True)
        self.renormalization_no.setObjectName(_fromUtf8("renormalization_no"))
        self.horizontalLayout_55.addWidget(self.renormalization_no)
        self.horizontalLayout_53.addWidget(self.groupBox_29)
        self.groupBox_30 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_30.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_30.setObjectName(_fromUtf8("groupBox_30"))
        self.horizontalLayout_56 = QtGui.QHBoxLayout(self.groupBox_30)
        self.horizontalLayout_56.setObjectName(_fromUtf8("horizontalLayout_56"))
        self.autotemplate_yes = QtGui.QRadioButton(self.groupBox_30)
        self.autotemplate_yes.setChecked(True)
        self.autotemplate_yes.setObjectName(_fromUtf8("autotemplate_yes"))
        self.horizontalLayout_56.addWidget(self.autotemplate_yes)
        self.autotemplate_no = QtGui.QRadioButton(self.groupBox_30)
        self.autotemplate_no.setChecked(False)
        self.autotemplate_no.setObjectName(_fromUtf8("autotemplate_no"))
        self.horizontalLayout_56.addWidget(self.autotemplate_no)
        self.horizontalLayout_53.addWidget(self.groupBox_30)
        self.groupBox = QtGui.QGroupBox(self.tab_5)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.postprocessing_yes = QtGui.QRadioButton(self.groupBox)
        self.postprocessing_yes.setChecked(True)
        self.postprocessing_yes.setObjectName(_fromUtf8("postprocessing_yes"))
        self.horizontalLayout_5.addWidget(self.postprocessing_yes)
        self.postprocessing_no = QtGui.QRadioButton(self.groupBox)
        self.postprocessing_no.setObjectName(_fromUtf8("postprocessing_no"))
        self.horizontalLayout_5.addWidget(self.postprocessing_no)
        self.horizontalLayout_53.addWidget(self.groupBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem3)
        self.verticalLayout_30.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_57 = QtGui.QHBoxLayout()
        self.horizontalLayout_57.setObjectName(_fromUtf8("horizontalLayout_57"))
        self.label_78 = QtGui.QLabel(self.tab_5)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_57.addWidget(self.label_78)
        self.comments = QtGui.QLineEdit(self.tab_5)
        self.comments.setObjectName(_fromUtf8("comments"))
        self.horizontalLayout_57.addWidget(self.comments)
        self.verticalLayout_30.addLayout(self.horizontalLayout_57)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem4)
        self.horizontalLayout_58 = QtGui.QHBoxLayout()
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.create_folder_button = QtGui.QCheckBox(self.tab_5)
        self.create_folder_button.setChecked(True)
        self.create_folder_button.setObjectName(_fromUtf8("create_folder_button"))
        self.verticalLayout_33.addWidget(self.create_folder_button)
        self.name_of_output_folder = QtGui.QGroupBox(self.tab_5)
        self.name_of_output_folder.setObjectName(_fromUtf8("name_of_output_folder"))
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.name_of_output_folder)
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.auto_manual_folder = QtGui.QRadioButton(self.name_of_output_folder)
        self.auto_manual_folder.setChecked(True)
        self.auto_manual_folder.setObjectName(_fromUtf8("auto_manual_folder"))
        self.verticalLayout_34.addWidget(self.auto_manual_folder)
        self.horizontalLayout_59 = QtGui.QHBoxLayout()
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.manual_output_folder = QtGui.QRadioButton(self.name_of_output_folder)
        self.manual_output_folder.setObjectName(_fromUtf8("manual_output_folder"))
        self.horizontalLayout_59.addWidget(self.manual_output_folder)
        self.manual_output_folder_field = QtGui.QLineEdit(self.name_of_output_folder)
        self.manual_output_folder_field.setEnabled(False)
        self.manual_output_folder_field.setObjectName(_fromUtf8("manual_output_folder_field"))
        self.horizontalLayout_59.addWidget(self.manual_output_folder_field)
        self.manual_output_folder_button = QtGui.QPushButton(self.name_of_output_folder)
        self.manual_output_folder_button.setEnabled(False)
        self.manual_output_folder_button.setObjectName(_fromUtf8("manual_output_folder_button"))
        self.horizontalLayout_59.addWidget(self.manual_output_folder_button)
        self.verticalLayout_34.addLayout(self.horizontalLayout_59)
        self.verticalLayout_33.addWidget(self.name_of_output_folder)
        self.horizontalLayout_58.addLayout(self.verticalLayout_33)
        self.verticalLayout_35 = QtGui.QVBoxLayout()
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_35.addItem(spacerItem5)
        self.run_autonom_script = QtGui.QPushButton(self.tab_5)
        self.run_autonom_script.setEnabled(False)
        self.run_autonom_script.setObjectName(_fromUtf8("run_autonom_script"))
        self.verticalLayout_35.addWidget(self.run_autonom_script)
        self.horizontalLayout_58.addLayout(self.verticalLayout_35)
        self.verticalLayout_30.addLayout(self.horizontalLayout_58)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_36 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_36.setObjectName(_fromUtf8("verticalLayout_36"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout()
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.move_to_button = QtGui.QPushButton(self.tab_6)
        self.move_to_button.setMaximumSize(QtCore.QSize(240, 16777215))
        self.move_to_button.setObjectName(_fromUtf8("move_to_button"))
        self.horizontalLayout_60.addWidget(self.move_to_button)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem6)
        self.verticalLayout_36.addLayout(self.horizontalLayout_60)
        self.populate_table = QtGui.QPushButton(self.tab_6)
        self.populate_table.setMinimumSize(QtCore.QSize(800, 0))
        self.populate_table.setObjectName(_fromUtf8("populate_table"))
        self.verticalLayout_36.addWidget(self.populate_table)
        self.table = QtGui.QTableWidget(self.tab_6)
        self.table.setMinimumSize(QtCore.QSize(800, 0))
        self.table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.table.setAlternatingRowColors(True)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(9)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_36.addWidget(self.table)
        self.label_80 = QtGui.QLabel(self.tab_6)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.verticalLayout_36.addWidget(self.label_80)
        self.horizontalLayout_61 = QtGui.QHBoxLayout()
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.groupBox_32 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_32.setObjectName(_fromUtf8("groupBox_32"))
        self.verticalLayout_37 = QtGui.QVBoxLayout(self.groupBox_32)
        self.verticalLayout_37.setObjectName(_fromUtf8("verticalLayout_37"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout()
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.background_no = QtGui.QRadioButton(self.groupBox_32)
        self.background_no.setMinimumSize(QtCore.QSize(50, 0))
        self.background_no.setMaximumSize(QtCore.QSize(50, 16777215))
        self.background_no.setChecked(True)
        self.background_no.setObjectName(_fromUtf8("background_no"))
        self.horizontalLayout_62.addWidget(self.background_no)
        self.background_no_field = QtGui.QLabel(self.groupBox_32)
        self.background_no_field.setMinimumSize(QtCore.QSize(300, 0))
        self.background_no_field.setObjectName(_fromUtf8("background_no_field"))
        self.horizontalLayout_62.addWidget(self.background_no_field)
        self.label_81 = QtGui.QLabel(self.groupBox_32)
        self.label_81.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.horizontalLayout_62.addWidget(self.label_81)
        self.verticalLayout_37.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_63 = QtGui.QHBoxLayout()
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.background_yes = QtGui.QRadioButton(self.groupBox_32)
        self.background_yes.setObjectName(_fromUtf8("background_yes"))
        self.horizontalLayout_63.addWidget(self.background_yes)
        self.background_comboBox = QtGui.QComboBox(self.groupBox_32)
        self.background_comboBox.setEnabled(False)
        self.background_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.background_comboBox.setObjectName(_fromUtf8("background_comboBox"))
        self.horizontalLayout_63.addWidget(self.background_comboBox)
        self.background_line_edit = QtGui.QLineEdit(self.groupBox_32)
        self.background_line_edit.setEnabled(False)
        self.background_line_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.background_line_edit.setObjectName(_fromUtf8("background_line_edit"))
        self.horizontalLayout_63.addWidget(self.background_line_edit)
        self.verticalLayout_37.addLayout(self.horizontalLayout_63)
        self.horizontalLayout_61.addWidget(self.groupBox_32)
        self.fourier_filter_group_box = QtGui.QGroupBox(self.tab_6)
        self.fourier_filter_group_box.setObjectName(_fromUtf8("fourier_filter_group_box"))
        self.horizontalLayout_64 = QtGui.QHBoxLayout(self.fourier_filter_group_box)
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.fourier_filter_from = QtGui.QLineEdit(self.fourier_filter_group_box)
        self.fourier_filter_from.setObjectName(_fromUtf8("fourier_filter_from"))
        self.horizontalLayout_64.addWidget(self.fourier_filter_from)
        self.label_82 = QtGui.QLabel(self.fourier_filter_group_box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_82.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_64.addWidget(self.label_82)
        self.label_83 = QtGui.QLabel(self.fourier_filter_group_box)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_64.addWidget(self.label_83)
        self.fourier_filter_to = QtGui.QLineEdit(self.fourier_filter_group_box)
        self.fourier_filter_to.setObjectName(_fromUtf8("fourier_filter_to"))
        self.horizontalLayout_64.addWidget(self.fourier_filter_to)
        self.label_84 = QtGui.QLabel(self.fourier_filter_group_box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_84.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayout_64.addWidget(self.label_84)
        self.horizontalLayout_61.addWidget(self.fourier_filter_group_box)
        self.groupBox_34 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_34.setObjectName(_fromUtf8("groupBox_34"))
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.groupBox_34)
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.horizontalLayout_65 = QtGui.QHBoxLayout()
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_85 = QtGui.QLabel(self.groupBox_34)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_65.addWidget(self.label_85)
        self.hydrogen_yes = QtGui.QRadioButton(self.groupBox_34)
        self.hydrogen_yes.setChecked(False)
        self.hydrogen_yes.setObjectName(_fromUtf8("hydrogen_yes"))
        self.horizontalLayout_65.addWidget(self.hydrogen_yes)
        self.hydrogen_no = QtGui.QRadioButton(self.groupBox_34)
        self.hydrogen_no.setChecked(True)
        self.hydrogen_no.setObjectName(_fromUtf8("hydrogen_no"))
        self.horizontalLayout_65.addWidget(self.hydrogen_no)
        self.verticalLayout_38.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_66 = QtGui.QHBoxLayout()
        self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        self.label_86 = QtGui.QLabel(self.groupBox_34)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.horizontalLayout_66.addWidget(self.label_86)
        self.plazcek_fit_range_min = QtGui.QLineEdit(self.groupBox_34)
        self.plazcek_fit_range_min.setMinimumSize(QtCore.QSize(50, 0))
        self.plazcek_fit_range_min.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plazcek_fit_range_min.setObjectName(_fromUtf8("plazcek_fit_range_min"))
        self.horizontalLayout_66.addWidget(self.plazcek_fit_range_min)
        self.label_87 = QtGui.QLabel(self.groupBox_34)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_87.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_87.setFont(font)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.horizontalLayout_66.addWidget(self.label_87)
        self.label_88 = QtGui.QLabel(self.groupBox_34)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayout_66.addWidget(self.label_88)
        self.plazcek_fit_range_max = QtGui.QLineEdit(self.groupBox_34)
        self.plazcek_fit_range_max.setMinimumSize(QtCore.QSize(50, 0))
        self.plazcek_fit_range_max.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plazcek_fit_range_max.setObjectName(_fromUtf8("plazcek_fit_range_max"))
        self.horizontalLayout_66.addWidget(self.plazcek_fit_range_max)
        self.label_89 = QtGui.QLabel(self.groupBox_34)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_89.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_89.setFont(font)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.horizontalLayout_66.addWidget(self.label_89)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem7)
        self.verticalLayout_38.addLayout(self.horizontalLayout_66)
        self.horizontalLayout_61.addWidget(self.groupBox_34)
        self.verticalLayout_36.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.q_range_group_box = QtGui.QGroupBox(self.tab_6)
        self.q_range_group_box.setObjectName(_fromUtf8("q_range_group_box"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.q_range_group_box)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.q_range_group_box)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.q_range_min = QtGui.QLineEdit(self.q_range_group_box)
        self.q_range_min.setMinimumSize(QtCore.QSize(80, 0))
        self.q_range_min.setMaximumSize(QtCore.QSize(80, 16777215))
        self.q_range_min.setObjectName(_fromUtf8("q_range_min"))
        self.horizontalLayout.addWidget(self.q_range_min)
        self.label_94 = QtGui.QLabel(self.q_range_group_box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_94.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_94.setFont(font)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.horizontalLayout.addWidget(self.label_94)
        self.label_2 = QtGui.QLabel(self.q_range_group_box)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.q_range_max = QtGui.QLineEdit(self.q_range_group_box)
        self.q_range_max.setMinimumSize(QtCore.QSize(80, 0))
        self.q_range_max.setMaximumSize(QtCore.QSize(80, 16777215))
        self.q_range_max.setObjectName(_fromUtf8("q_range_max"))
        self.horizontalLayout.addWidget(self.q_range_max)
        self.label_95 = QtGui.QLabel(self.q_range_group_box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_95.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_95.setFont(font)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.horizontalLayout.addWidget(self.label_95)
        self.pushButton = QtGui.QPushButton(self.q_range_group_box)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.q_range_group_box)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.groupBox_38 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_38.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_38.setObjectName(_fromUtf8("groupBox_38"))
        self.horizontalLayout_76 = QtGui.QHBoxLayout(self.groupBox_38)
        self.horizontalLayout_76.setObjectName(_fromUtf8("horizontalLayout_76"))
        self.muscat_yes = QtGui.QRadioButton(self.groupBox_38)
        self.muscat_yes.setObjectName(_fromUtf8("muscat_yes"))
        self.horizontalLayout_76.addWidget(self.muscat_yes)
        self.radioButton_26 = QtGui.QRadioButton(self.groupBox_38)
        self.radioButton_26.setChecked(True)
        self.radioButton_26.setObjectName(_fromUtf8("radioButton_26"))
        self.horizontalLayout_76.addWidget(self.radioButton_26)
        self.horizontalLayout_2.addWidget(self.groupBox_38)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.groupBox_39 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_39.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_39.setObjectName(_fromUtf8("groupBox_39"))
        self.horizontalLayout_77 = QtGui.QHBoxLayout(self.groupBox_39)
        self.horizontalLayout_77.setObjectName(_fromUtf8("horizontalLayout_77"))
        self.scale_data_yes = QtGui.QRadioButton(self.groupBox_39)
        self.scale_data_yes.setChecked(True)
        self.scale_data_yes.setObjectName(_fromUtf8("scale_data_yes"))
        self.horizontalLayout_77.addWidget(self.scale_data_yes)
        self.radioButton_27 = QtGui.QRadioButton(self.groupBox_39)
        self.radioButton_27.setChecked(False)
        self.radioButton_27.setObjectName(_fromUtf8("radioButton_27"))
        self.horizontalLayout_77.addWidget(self.radioButton_27)
        self.horizontalLayout_2.addWidget(self.groupBox_39)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.groupBox_40 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_40.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_40.setObjectName(_fromUtf8("groupBox_40"))
        self.horizontalLayout_78 = QtGui.QHBoxLayout(self.groupBox_40)
        self.horizontalLayout_78.setObjectName(_fromUtf8("horizontalLayout_78"))
        self.run_rmc_yes = QtGui.QRadioButton(self.groupBox_40)
        self.run_rmc_yes.setChecked(True)
        self.run_rmc_yes.setObjectName(_fromUtf8("run_rmc_yes"))
        self.horizontalLayout_78.addWidget(self.run_rmc_yes)
        self.radioButton_28 = QtGui.QRadioButton(self.groupBox_40)
        self.radioButton_28.setChecked(False)
        self.radioButton_28.setObjectName(_fromUtf8("radioButton_28"))
        self.horizontalLayout_78.addWidget(self.radioButton_28)
        self.horizontalLayout_2.addWidget(self.groupBox_40)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_36.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_71 = QtGui.QHBoxLayout()
        self.horizontalLayout_71.setObjectName(_fromUtf8("horizontalLayout_71"))
        self.label_90 = QtGui.QLabel(self.tab_6)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_90.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_90.setFont(font)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.horizontalLayout_71.addWidget(self.label_90)
        self.label_91 = QtGui.QLabel(self.tab_6)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_71.addWidget(self.label_91)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem12)
        self.interactive_mode_checkbox = QtGui.QCheckBox(self.tab_6)
        self.interactive_mode_checkbox.setChecked(True)
        self.interactive_mode_checkbox.setObjectName(_fromUtf8("interactive_mode_checkbox"))
        self.horizontalLayout_71.addWidget(self.interactive_mode_checkbox)
        self.run_sum_scans_button = QtGui.QPushButton(self.tab_6)
        self.run_sum_scans_button.setEnabled(False)
        self.run_sum_scans_button.setObjectName(_fromUtf8("run_sum_scans_button"))
        self.horizontalLayout_71.addWidget(self.run_sum_scans_button)
        spacerItem13 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem13)
        self.label_5 = QtGui.QLabel(self.tab_6)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_71.addWidget(self.label_5)
        self.run_ndabs_output_file_name = QtGui.QLineEdit(self.tab_6)
        self.run_ndabs_output_file_name.setMinimumSize(QtCore.QSize(70, 0))
        self.run_ndabs_output_file_name.setMaximumSize(QtCore.QSize(70, 16777215))
        self.run_ndabs_output_file_name.setObjectName(_fromUtf8("run_ndabs_output_file_name"))
        self.horizontalLayout_71.addWidget(self.run_ndabs_output_file_name)
        self.label_6 = QtGui.QLabel(self.tab_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_71.addWidget(self.label_6)
        spacerItem14 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem14)
        self.run_ndabs_button = QtGui.QPushButton(self.tab_6)
        self.run_ndabs_button.setEnabled(False)
        self.run_ndabs_button.setObjectName(_fromUtf8("run_ndabs_button"))
        self.horizontalLayout_71.addWidget(self.run_ndabs_button)
        self.verticalLayout_36.addLayout(self.horizontalLayout_71)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_bragg = QtGui.QWidget()
        self.tab_bragg.setObjectName(_fromUtf8("tab_bragg"))
        self.horizontalLayout_72 = QtGui.QHBoxLayout(self.tab_bragg)
        self.horizontalLayout_72.setObjectName(_fromUtf8("horizontalLayout_72"))
        self.verticalLayout_39 = QtGui.QVBoxLayout()
        self.verticalLayout_39.setObjectName(_fromUtf8("verticalLayout_39"))
        self.horizontalLayout_73 = QtGui.QHBoxLayout()
        self.horizontalLayout_73.setObjectName(_fromUtf8("horizontalLayout_73"))
        self.verticalLayout_40 = QtGui.QVBoxLayout()
        self.verticalLayout_40.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_40.setObjectName(_fromUtf8("verticalLayout_40"))
        self.horizontalLayout_74 = QtGui.QHBoxLayout()
        self.horizontalLayout_74.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_74.setObjectName(_fromUtf8("horizontalLayout_74"))
        self.label_92 = QtGui.QLabel(self.tab_bragg)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.horizontalLayout_74.addWidget(self.label_92)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_74.addItem(spacerItem15)
        self.verticalLayout_40.addLayout(self.horizontalLayout_74)
        self.graphicsView_bragg = BraggView(self.tab_bragg)
        self.graphicsView_bragg.setObjectName(_fromUtf8("graphicsView_bragg"))
        self.verticalLayout_40.addWidget(self.graphicsView_bragg)
        self.horizontalLayout_75 = QtGui.QHBoxLayout()
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        self.comboBox_xUnit = QtGui.QComboBox(self.tab_bragg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_xUnit.sizePolicy().hasHeightForWidth())
        self.comboBox_xUnit.setSizePolicy(sizePolicy)
        self.comboBox_xUnit.setObjectName(_fromUtf8("comboBox_xUnit"))
        self.comboBox_xUnit.addItem(_fromUtf8(""))
        self.comboBox_xUnit.addItem(_fromUtf8(""))
        self.comboBox_xUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_75.addWidget(self.comboBox_xUnit)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_75.addItem(spacerItem16)
        self.verticalLayout_40.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_73.addLayout(self.verticalLayout_40)
        self.verticalLayout_41 = QtGui.QVBoxLayout()
        self.verticalLayout_41.setObjectName(_fromUtf8("verticalLayout_41"))
        self.pushButton_loadBraggFile = QtGui.QPushButton(self.tab_bragg)
        self.pushButton_loadBraggFile.setObjectName(_fromUtf8("pushButton_loadBraggFile"))
        self.verticalLayout_41.addWidget(self.pushButton_loadBraggFile)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_41.addItem(spacerItem17)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_41.addItem(spacerItem18)
        self.checkBox_bank1 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank1.setObjectName(_fromUtf8("checkBox_bank1"))
        self.verticalLayout_41.addWidget(self.checkBox_bank1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_41.addItem(spacerItem19)
        self.checkBox_bank2 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank2.setObjectName(_fromUtf8("checkBox_bank2"))
        self.verticalLayout_41.addWidget(self.checkBox_bank2)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_41.addItem(spacerItem20)
        self.checkBox_bank3 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank3.setObjectName(_fromUtf8("checkBox_bank3"))
        self.verticalLayout_41.addWidget(self.checkBox_bank3)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_41.addItem(spacerItem21)
        self.checkBox_bank4 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank4.setObjectName(_fromUtf8("checkBox_bank4"))
        self.verticalLayout_41.addWidget(self.checkBox_bank4)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_41.addItem(spacerItem22)
        self.checkBox_bank5 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank5.setObjectName(_fromUtf8("checkBox_bank5"))
        self.verticalLayout_41.addWidget(self.checkBox_bank5)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_41.addItem(spacerItem23)
        self.checkBox_bank6 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank6.setObjectName(_fromUtf8("checkBox_bank6"))
        self.verticalLayout_41.addWidget(self.checkBox_bank6)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_41.addItem(spacerItem24)
        self.radioButton_multiBank = QtGui.QRadioButton(self.tab_bragg)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_multiBank.setFont(font)
        self.radioButton_multiBank.setObjectName(_fromUtf8("radioButton_multiBank"))
        self.verticalLayout_41.addWidget(self.radioButton_multiBank)
        self.radioButton_multiGSS = QtGui.QRadioButton(self.tab_bragg)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_multiGSS.setFont(font)
        self.radioButton_multiGSS.setObjectName(_fromUtf8("radioButton_multiGSS"))
        self.verticalLayout_41.addWidget(self.radioButton_multiGSS)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_41.addItem(spacerItem25)
        self.horizontalLayout_73.addLayout(self.verticalLayout_41)
        self.verticalLayout_39.addLayout(self.horizontalLayout_73)
        self.horizontalLayout_72.addLayout(self.verticalLayout_39)
        self.treeWidget_braggWSList = BraggTree(self.tab_bragg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_braggWSList.sizePolicy().hasHeightForWidth())
        self.treeWidget_braggWSList.setSizePolicy(sizePolicy)
        self.treeWidget_braggWSList.setObjectName(_fromUtf8("treeWidget_braggWSList"))
        self.horizontalLayout_72.addWidget(self.treeWidget_braggWSList)
        self.tabWidget_2.addTab(self.tab_bragg, _fromUtf8(""))
        self.tab_gR = QtGui.QWidget()
        self.tab_gR.setObjectName(_fromUtf8("tab_gR"))
        self.gridLayout = QtGui.QGridLayout(self.tab_gR)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graphicsView_sq = SofQView(self.tab_gR)
        self.graphicsView_sq.setMinimumSize(QtCore.QSize(50, 300))
        self.graphicsView_sq.setObjectName(_fromUtf8("graphicsView_sq"))
        self.gridLayout.addWidget(self.graphicsView_sq, 0, 0, 1, 1)
        self.verticalLayout_42 = QtGui.QVBoxLayout()
        self.verticalLayout_42.setObjectName(_fromUtf8("verticalLayout_42"))
        self.pushButton_loadSQ = QtGui.QPushButton(self.tab_gR)
        self.pushButton_loadSQ.setObjectName(_fromUtf8("pushButton_loadSQ"))
        self.verticalLayout_42.addWidget(self.pushButton_loadSQ)
        self.radioButton_sq = QtGui.QRadioButton(self.tab_gR)
        self.radioButton_sq.setObjectName(_fromUtf8("radioButton_sq"))
        self.verticalLayout_42.addWidget(self.radioButton_sq)
        self.radioButton_sqm1 = QtGui.QRadioButton(self.tab_gR)
        self.radioButton_sqm1.setObjectName(_fromUtf8("radioButton_sqm1"))
        self.verticalLayout_42.addWidget(self.radioButton_sqm1)
        self.radioButton_qsqm1 = QtGui.QRadioButton(self.tab_gR)
        self.radioButton_qsqm1.setObjectName(_fromUtf8("radioButton_qsqm1"))
        self.verticalLayout_42.addWidget(self.radioButton_qsqm1)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.comboBox_pdfType = QtGui.QComboBox(self.tab_gR)
        self.comboBox_pdfType.setObjectName(_fromUtf8("comboBox_pdfType"))
        self.gridLayout_18.addWidget(self.comboBox_pdfType, 3, 1, 1, 1)
        self.labelQmax = QtGui.QLabel(self.tab_gR)
        self.labelQmax.setObjectName(_fromUtf8("labelQmax"))
        self.gridLayout_18.addWidget(self.labelQmax, 1, 0, 1, 1)
        self.doubleSpinBoxQmax = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxQmax.setMinimum(1.0)
        self.doubleSpinBoxQmax.setMaximum(50.0)
        self.doubleSpinBoxQmax.setSingleStep(0.5)
        self.doubleSpinBoxQmax.setObjectName(_fromUtf8("doubleSpinBoxQmax"))
        self.gridLayout_18.addWidget(self.doubleSpinBoxQmax, 1, 1, 1, 1)
        self.doubleSpinBoxQmin = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxQmin.setMinimum(0.01)
        self.doubleSpinBoxQmin.setMaximum(10.0)
        self.doubleSpinBoxQmin.setSingleStep(0.01)
        self.doubleSpinBoxQmin.setObjectName(_fromUtf8("doubleSpinBoxQmin"))
        self.gridLayout_18.addWidget(self.doubleSpinBoxQmin, 0, 1, 1, 1)
        self.labelQmin = QtGui.QLabel(self.tab_gR)
        self.labelQmin.setObjectName(_fromUtf8("labelQmin"))
        self.gridLayout_18.addWidget(self.labelQmin, 0, 0, 1, 1)
        self.pushButton_showQMinMax = QtGui.QPushButton(self.tab_gR)
        self.pushButton_showQMinMax.setObjectName(_fromUtf8("pushButton_showQMinMax"))
        self.gridLayout_18.addWidget(self.pushButton_showQMinMax, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_gR)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_18.addWidget(self.label_3, 3, 0, 1, 1)
        self.verticalLayout_42.addLayout(self.gridLayout_18)
        self.comboBox_SofQ = QtGui.QComboBox(self.tab_gR)
        self.comboBox_SofQ.setObjectName(_fromUtf8("comboBox_SofQ"))
        self.verticalLayout_42.addWidget(self.comboBox_SofQ)
        self.pushButton_generateGR = QtGui.QPushButton(self.tab_gR)
        self.pushButton_generateGR.setObjectName(_fromUtf8("pushButton_generateGR"))
        self.verticalLayout_42.addWidget(self.pushButton_generateGR)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox_pdfFilter = QtGui.QCheckBox(self.tab_gR)
        self.checkBox_pdfFilter.setObjectName(_fromUtf8("checkBox_pdfFilter"))
        self.horizontalLayout_6.addWidget(self.checkBox_pdfFilter)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem26)
        self.label_4 = QtGui.QLabel(self.tab_gR)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit_rho = QtGui.QLineEdit(self.tab_gR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rho.sizePolicy().hasHeightForWidth())
        self.lineEdit_rho.setSizePolicy(sizePolicy)
        self.lineEdit_rho.setObjectName(_fromUtf8("lineEdit_rho"))
        self.horizontalLayout_6.addWidget(self.lineEdit_rho)
        self.verticalLayout_42.addLayout(self.horizontalLayout_6)
        self.pushButton_clearSofQ = QtGui.QPushButton(self.tab_gR)
        self.pushButton_clearSofQ.setObjectName(_fromUtf8("pushButton_clearSofQ"))
        self.verticalLayout_42.addWidget(self.pushButton_clearSofQ)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_42.addItem(spacerItem27)
        self.gridLayout.addLayout(self.verticalLayout_42, 0, 1, 1, 1)
        self.graphicsView_gr = GofRView(self.tab_gR)
        self.graphicsView_gr.setMinimumSize(QtCore.QSize(50, 300))
        self.graphicsView_gr.setObjectName(_fromUtf8("graphicsView_gr"))
        self.gridLayout.addWidget(self.graphicsView_gr, 1, 0, 1, 1)
        self.verticalLayout_43 = QtGui.QVBoxLayout()
        self.verticalLayout_43.setObjectName(_fromUtf8("verticalLayout_43"))
        self.pushButton_loadGofR = QtGui.QPushButton(self.tab_gR)
        self.pushButton_loadGofR.setObjectName(_fromUtf8("pushButton_loadGofR"))
        self.verticalLayout_43.addWidget(self.pushButton_loadGofR)
        self.treeWidget_grWsList = GofRTree(self.tab_gR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_grWsList.sizePolicy().hasHeightForWidth())
        self.treeWidget_grWsList.setSizePolicy(sizePolicy)
        self.treeWidget_grWsList.setObjectName(_fromUtf8("treeWidget_grWsList"))
        self.verticalLayout_43.addWidget(self.treeWidget_grWsList)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.labelRmin = QtGui.QLabel(self.tab_gR)
        self.labelRmin.setObjectName(_fromUtf8("labelRmin"))
        self.gridLayout_20.addWidget(self.labelRmin, 0, 0, 1, 1)
        self.labeldelR = QtGui.QLabel(self.tab_gR)
        self.labeldelR.setObjectName(_fromUtf8("labeldelR"))
        self.gridLayout_20.addWidget(self.labeldelR, 0, 2, 1, 1)
        self.labelRmax = QtGui.QLabel(self.tab_gR)
        self.labelRmax.setObjectName(_fromUtf8("labelRmax"))
        self.gridLayout_20.addWidget(self.labelRmax, 0, 4, 1, 1)
        self.doubleSpinBoxRmin = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxRmin.setMinimum(0.1)
        self.doubleSpinBoxRmin.setMaximum(4.0)
        self.doubleSpinBoxRmin.setSingleStep(0.1)
        self.doubleSpinBoxRmin.setObjectName(_fromUtf8("doubleSpinBoxRmin"))
        self.gridLayout_20.addWidget(self.doubleSpinBoxRmin, 1, 0, 1, 1)
        self.doubleSpinBoxDelR = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxDelR.setMinimum(0.01)
        self.doubleSpinBoxDelR.setMaximum(1.0)
        self.doubleSpinBoxDelR.setSingleStep(0.01)
        self.doubleSpinBoxDelR.setProperty("value", 0.1)
        self.doubleSpinBoxDelR.setObjectName(_fromUtf8("doubleSpinBoxDelR"))
        self.gridLayout_20.addWidget(self.doubleSpinBoxDelR, 1, 2, 1, 1)
        self.doubleSpinBoxRmax = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxRmax.setMinimum(5.0)
        self.doubleSpinBoxRmax.setMaximum(100.0)
        self.doubleSpinBoxRmax.setProperty("value", 20.0)
        self.doubleSpinBoxRmax.setObjectName(_fromUtf8("doubleSpinBoxRmax"))
        self.gridLayout_20.addWidget(self.doubleSpinBoxRmax, 1, 4, 1, 1)
        self.verticalLayout_43.addLayout(self.gridLayout_20)
        self.pushButton_clearGrCanvas = QtGui.QPushButton(self.tab_gR)
        self.pushButton_clearGrCanvas.setObjectName(_fromUtf8("pushButton_clearGrCanvas"))
        self.verticalLayout_43.addWidget(self.pushButton_clearGrCanvas)
        self.pushButton_saveGR = QtGui.QPushButton(self.tab_gR)
        self.pushButton_saveGR.setObjectName(_fromUtf8("pushButton_saveGR"))
        self.verticalLayout_43.addWidget(self.pushButton_saveGR)
        self.gridLayout.addLayout(self.verticalLayout_43, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_gR, _fromUtf8(""))
        self.gridLayout_14.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.verticalLayout_44.addLayout(self.gridLayout_14)
        self.dockWidget_ipython = IPythonDockWidget(self.scrollAreaWidgetContents)
        self.dockWidget_ipython.setMinimumSize(QtCore.QSize(800, 41))
        self.dockWidget_ipython.setMaximumSize(QtCore.QSize(524287, 300))
        self.dockWidget_ipython.setObjectName(_fromUtf8("dockWidget_ipython"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dockWidget_ipython.setWidget(self.dockWidgetContents)
        self.verticalLayout_44.addWidget(self.dockWidget_ipython)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1348, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset_GSAS_tab = QtGui.QAction(MainWindow)
        self.actionReset_GSAS_tab.setObjectName(_fromUtf8("actionReset_GSAS_tab"))
        self.actionReset_GofR_tab = QtGui.QAction(MainWindow)
        self.actionReset_GofR_tab.setObjectName(_fromUtf8("actionReset_GofR_tab"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCheat_sheet = QtGui.QAction(MainWindow)
        self.actionCheat_sheet.setObjectName(_fromUtf8("actionCheat_sheet"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.action_preview_ascii = QtGui.QAction(MainWindow)
        self.action_preview_ascii.setObjectName(_fromUtf8("action_preview_ascii"))
        self.menuFile.addAction(self.action_preview_ascii)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionReset_GSAS_tab)
        self.menuEdit.addAction(self.actionReset_GofR_tab)
        self.menuHelp.addAction(self.actionCheat_sheet)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.diamond, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.diamond_edited)
        QtCore.QObject.connect(self.diamond_background, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.diamond_background_edited)
        QtCore.QObject.connect(self.vanadium, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.vanadium_edited)
        QtCore.QObject.connect(self.vanadium_background, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.vanadium_background_edited)
        QtCore.QObject.connect(self.sample_background, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.sample_background_edited)
        QtCore.QObject.connect(self.auto_manual_folder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.output_folder_radio_buttons)
        QtCore.QObject.connect(self.manual_output_folder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.output_folder_radio_buttons)
        QtCore.QObject.connect(self.manual_output_folder_field, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.manual_output_folder_field_edited)
        QtCore.QObject.connect(self.run_autonom_script, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.run_autonom)
        QtCore.QObject.connect(self.table, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), MainWindow.table_right_click)
        QtCore.QObject.connect(self.run_ndabs_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.run_ndabs_clicked)
        QtCore.QObject.connect(self.populate_table, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.populate_table_clicked)
        QtCore.QObject.connect(self.plazcek_fit_range_min, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_plazcek_widgets)
        QtCore.QObject.connect(self.plazcek_fit_range_max, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_plazcek_widgets)
        QtCore.QObject.connect(self.hydrogen_yes, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.hidrogen_clicked)
        QtCore.QObject.connect(self.hydrogen_no, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.no_hidrogen_clicked)
        QtCore.QObject.connect(self.fourier_filter_from, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_fourier_filter_widgets)
        QtCore.QObject.connect(self.fourier_filter_to, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_fourier_filter_widgets)
        QtCore.QObject.connect(self.background_yes, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.yes_background_clicked)
        QtCore.QObject.connect(self.background_comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.background_combobox_changed)
        QtCore.QObject.connect(self.move_to_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.move_to_folder_clicked)
        QtCore.QObject.connect(self.table, QtCore.SIGNAL(_fromUtf8("cellChanged(int,int)")), MainWindow.check_step2_gui)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.reset_q_range)
        QtCore.QObject.connect(self.q_range_min, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_q_range)
        QtCore.QObject.connect(self.q_range_max, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_q_range)
        QtCore.QObject.connect(self.run_sum_scans_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.run_sum_scans_clicked)
        QtCore.QObject.connect(self.select_current_folder_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.select_current_folder_clicked)
        QtCore.QObject.connect(self.manual_output_folder_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.manual_output_folder_button_clicked)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.help_about_clicked)
        QtCore.QObject.connect(self.action_preview_ascii, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.action_preview_ascii_clicked)
        QtCore.QObject.connect(self.run_ndabs_output_file_name, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainWindow.output_file_name_changed)
        QtCore.QObject.connect(self.create_folder_button, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.create_new_autonom_folder_button_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_27.setTitle(_translate("MainWindow", "Scan Numbers  (ex: 1234, 1300-1305, 1310)", None))
        self.select_current_folder_button.setText(_translate("MainWindow", "Select Working Folder ...", None))
        self.label_63.setText(_translate("MainWindow", "*", None))
        self.label_64.setText(_translate("MainWindow", "Vanadium background", None))
        self.label_65.setText(_translate("MainWindow", "Diamond", None))
        self.label_66.setText(_translate("MainWindow", "Vanadium", None))
        self.label_67.setText(_translate("MainWindow", "*", None))
        self.label_68.setText(_translate("MainWindow", "*", None))
        self.label_69.setText(_translate("MainWindow", "*", None))
        self.label_70.setText(_translate("MainWindow", "*", None))
        self.label_71.setText(_translate("MainWindow", "Diamond background", None))
        self.label_72.setText(_translate("MainWindow", "Sample background", None))
        self.label_73.setText(_translate("MainWindow", "*", None))
        self.label_74.setText(_translate("MainWindow", ": Mandatory field", None))
        self.label_75.setText(_translate("MainWindow", "First scan to be analyzed", None))
        self.label_76.setText(_translate("MainWindow", "Frequency (Hz)", None))
        self.label_77.setText(_translate("MainWindow", "Last scan to be analyzed", None))
        self.frequency.setItemText(0, _translate("MainWindow", "60", None))
        self.frequency.setItemText(1, _translate("MainWindow", "30", None))
        self.groupBox_28.setTitle(_translate("MainWindow", "Recalibration", None))
        self.recalibration_yes.setText(_translate("MainWindow", "yes", None))
        self.recalibration_no.setText(_translate("MainWindow", "No", None))
        self.groupBox_29.setTitle(_translate("MainWindow", "Renormalization", None))
        self.renormalization_yes.setText(_translate("MainWindow", "Yes", None))
        self.renormalization_no.setText(_translate("MainWindow", "No", None))
        self.groupBox_30.setTitle(_translate("MainWindow", "Autotemplate", None))
        self.autotemplate_yes.setText(_translate("MainWindow", "Yes", None))
        self.autotemplate_no.setText(_translate("MainWindow", "No", None))
        self.groupBox.setTitle(_translate("MainWindow", "Postprocessing", None))
        self.postprocessing_yes.setToolTip(_translate("MainWindow", "Will not overwrite the data reduction config file", None))
        self.postprocessing_yes.setText(_translate("MainWindow", "Yes", None))
        self.postprocessing_no.setToolTip(_translate("MainWindow", "Will overwrite the data reduction config file", None))
        self.postprocessing_no.setText(_translate("MainWindow", "No", None))
        self.label_78.setText(_translate("MainWindow", "Comments:", None))
        self.create_folder_button.setText(_translate("MainWindow", "Create New autoNOM Folder?", None))
        self.name_of_output_folder.setTitle(_translate("MainWindow", "Name of Output Folder", None))
        self.auto_manual_folder.setText(_translate("MainWindow", "Automatic (autoNOM_##)", None))
        self.manual_output_folder.setText(_translate("MainWindow", "Manual", None))
        self.manual_output_folder_button.setText(_translate("MainWindow", "Select ...", None))
        self.run_autonom_script.setText(_translate("MainWindow", "Run autoNOM script", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "autoNOM", None))
        self.move_to_button.setText(_translate("MainWindow", "Move to Folder and Refresh Table ...", None))
        self.populate_table.setText(_translate("MainWindow", "Refresh Table", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Select", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Runs", None))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sample Formula", None))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mass Density (g/cc)", None))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Radius (cm)", None))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Packing Fraction", None))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sample Shape", None))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Do Abs. Corr. ?", None))
        self.label_80.setText(_translate("MainWindow", "Sample formula example: H 2 O 1, 2H 2 O 1, 238U 1 O 2", None))
        self.groupBox_32.setTitle(_translate("MainWindow", "Background", None))
        self.background_no.setText(_translate("MainWindow", "No", None))
        self.background_no_field.setText(_translate("MainWindow", "N/A", None))
        self.label_81.setText(_translate("MainWindow", "(from exp.ini file)", None))
        self.background_yes.setText(_translate("MainWindow", "Yes", None))
        self.fourier_filter_group_box.setTitle(_translate("MainWindow", "Fourier Filter", None))
        self.fourier_filter_from.setText(_translate("MainWindow", "1.5", None))
        self.label_82.setText(_translate("MainWindow", "*", None))
        self.label_83.setText(_translate("MainWindow", ",", None))
        self.fourier_filter_to.setText(_translate("MainWindow", "50", None))
        self.label_84.setText(_translate("MainWindow", "*", None))
        self.groupBox_34.setTitle(_translate("MainWindow", "Plazcek", None))
        self.label_85.setText(_translate("MainWindow", "Type", None))
        self.hydrogen_yes.setText(_translate("MainWindow", "hydrogen", None))
        self.hydrogen_no.setText(_translate("MainWindow", "no hydrogren", None))
        self.label_86.setText(_translate("MainWindow", "Fit Range", None))
        self.plazcek_fit_range_min.setText(_translate("MainWindow", "10", None))
        self.label_87.setText(_translate("MainWindow", "*", None))
        self.label_88.setText(_translate("MainWindow", ",", None))
        self.plazcek_fit_range_max.setText(_translate("MainWindow", "50", None))
        self.label_89.setText(_translate("MainWindow", "*", None))
        self.q_range_group_box.setTitle(_translate("MainWindow", "Q range", None))
        self.label.setText(_translate("MainWindow", "Qmin", None))
        self.q_range_min.setText(_translate("MainWindow", "0.2", None))
        self.label_94.setText(_translate("MainWindow", "*", None))
        self.label_2.setText(_translate("MainWindow", "Qmin", None))
        self.q_range_max.setText(_translate("MainWindow", "31.4", None))
        self.label_95.setText(_translate("MainWindow", "*", None))
        self.pushButton.setText(_translate("MainWindow", "Reset", None))
        self.groupBox_38.setTitle(_translate("MainWindow", "Muscat", None))
        self.muscat_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_26.setText(_translate("MainWindow", "No", None))
        self.groupBox_39.setTitle(_translate("MainWindow", "Scale Data", None))
        self.scale_data_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_27.setText(_translate("MainWindow", "No", None))
        self.groupBox_40.setTitle(_translate("MainWindow", "Run RMC", None))
        self.run_rmc_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_28.setText(_translate("MainWindow", "No", None))
        self.label_90.setText(_translate("MainWindow", "*", None))
        self.label_91.setText(_translate("MainWindow", ": Mandatory field", None))
        self.interactive_mode_checkbox.setText(_translate("MainWindow", "Interactive Mode ?", None))
        self.run_sum_scans_button.setText(_translate("MainWindow", "Run Sum Scans", None))
        self.label_5.setText(_translate("MainWindow", "Output File Name:", None))
        self.run_ndabs_output_file_name.setText(_translate("MainWindow", "STO", None))
        self.label_6.setText(_translate("MainWindow", ".ndsum", None))
        self.run_ndabs_button.setText(_translate("MainWindow", "Run NDabs", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "NDabs", None))
        self.label_92.setText(_translate("MainWindow", "SNS Powder Reduction Configuration for NOMAD", None))
        self.comboBox_xUnit.setItemText(0, _translate("MainWindow", "TOF", None))
        self.comboBox_xUnit.setItemText(1, _translate("MainWindow", "d-Spacing", None))
        self.comboBox_xUnit.setItemText(2, _translate("MainWindow", "Q", None))
        self.pushButton_loadBraggFile.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load GSS/S(Q)/general 3-column ASCII</p><p>1. GSS: load and then split to 6 workspaces with single spectrum.  Finally group all 6 workspaces to a workspace group</p></body></html>", None))
        self.pushButton_loadBraggFile.setText(_translate("MainWindow", "Load", None))
        self.checkBox_bank1.setText(_translate("MainWindow", "Bank 1", None))
        self.checkBox_bank2.setText(_translate("MainWindow", "Bank 2", None))
        self.checkBox_bank3.setText(_translate("MainWindow", "Bank 3", None))
        self.checkBox_bank4.setText(_translate("MainWindow", "Bank 4", None))
        self.checkBox_bank5.setText(_translate("MainWindow", "Bank 5", None))
        self.checkBox_bank6.setText(_translate("MainWindow", "Bank 6", None))
        self.radioButton_multiBank.setText(_translate("MainWindow", "Multiple Banks", None))
        self.radioButton_multiGSS.setText(_translate("MainWindow", "Multiple GSS", None))
        self.treeWidget_braggWSList.setToolTip(_translate("MainWindow", "<html><head/><body><p>List of workspace names.  Each workspace is an individual bank</p></body></html>", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_bragg), _translate("MainWindow", "Bragg Peaks", None))
        self.pushButton_loadSQ.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load S(Q) from the reduction tab. Plot S(Q), S(Q)-1 or Q[S(Q)-1] according to the selected radio buttons below.</p><p><span style=\" font-weight:600;\">Use regular file loader at this phase.</span></p><p>Duplicate the function in FastGR/scripts/fastgr</p><p>149     def read_SQ_file(self):</p><p><br/></p></body></html>", None))
        self.pushButton_loadSQ.setText(_translate("MainWindow", "Load SQ", None))
        self.radioButton_sq.setText(_translate("MainWindow", "S(Q)", None))
        self.radioButton_sqm1.setText(_translate("MainWindow", "S(Q)-1", None))
        self.radioButton_qsqm1.setText(_translate("MainWindow", "Q[S(Q)-1]", None))
        self.labelQmax.setText(_translate("MainWindow", "Qmax", None))
        self.labelQmin.setText(_translate("MainWindow", "Qmin", None))
        self.pushButton_showQMinMax.setToolTip(_translate("MainWindow", "<html><head/><body><p>Show or hide the vertical indicators for Qmin and Qmax</p></body></html>", None))
        self.pushButton_showQMinMax.setText(_translate("MainWindow", "Show Min/Max", None))
        self.label_3.setText(_translate("MainWindow", "PDF Type", None))
        self.pushButton_generateGR.setText(_translate("MainWindow", "Generate GR", None))
        self.checkBox_pdfFilter.setText(_translate("MainWindow", "Filter", None))
        self.label_4.setText(_translate("MainWindow", "rho0", None))
        self.pushButton_clearSofQ.setText(_translate("MainWindow", "Clear S(Q) Canvas", None))
        self.pushButton_loadGofR.setText(_translate("MainWindow", "Load G(r)", None))
        self.treeWidget_grWsList.setToolTip(_translate("MainWindow", "<html><head/><body><p>write click on the workspace name should give user the option to plot/over plot </p></body></html>", None))
        self.labelRmin.setText(_translate("MainWindow", "Rmin", None))
        self.labeldelR.setText(_translate("MainWindow", "deltaR", None))
        self.labelRmax.setText(_translate("MainWindow", "Rmax", None))
        self.pushButton_clearGrCanvas.setText(_translate("MainWindow", "Clear G(r) Canvas", None))
        self.pushButton_saveGR.setText(_translate("MainWindow", "Save G(r)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_gR), _translate("MainWindow", "Calculate G(R)", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionReset_GSAS_tab.setText(_translate("MainWindow", "Reset GSAS-tab", None))
        self.actionReset_GofR_tab.setText(_translate("MainWindow", "Reset GofR-tab", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionCheat_sheet.setText(_translate("MainWindow", "Cheat sheet", None))
        self.actionAbout.setText(_translate("MainWindow", "About ...", None))
        self.action_preview_ascii.setText(_translate("MainWindow", "Preview Ascii ...", None))

from graphicviewlib import BraggView, GofRView, SofQView
from ipythondockwidget import IPythonDockWidget
from treelib import BraggTree, GofRTree
