#!/usr/bin/env python

import sys
import os
import itertools
from fastgr.ipythondockwidget import IPythonDockWidget

import fastgr.ui_mainWindow
import fastgr.step1
import fastgr.step2

from fastgr.about import AboutDialog
from fastgr.advanced_window_handler.advanced_window import AdvancedWindow
from fastgr.configuration.export_configuration import ExportConfiguration
from fastgr.configuration.import_configuration import ImportConfiguration

from fastgr.general_handler.help_gui import HelpGui, help_button_activator

from fastgr.initialization.init_step1 import InitStep1
from fastgr.step1_handler.step1_gui_handler import Step1GuiHandler
from fastgr.step1_handler.run_step1 import RunStep1

from fastgr.initialization.init_step2 import InitStep2
from fastgr.step2_handler.populate_master_table import PopulateMasterTable
from fastgr.step2_handler.populate_background_widgets import PopulateBackgroundWidgets
from fastgr.step2_handler.step2_gui_handler import Step2GuiHandler
from fastgr.step2_handler.table_handler import TableHandler
from fastgr.step2_handler.create_sample_files import CreateSampleFiles
from fastgr.step2_handler.create_ndsum_file import CreateNdsumFile
from fastgr.step2_handler.run_ndabs import RunNDabs
from fastgr.step2_handler.run_sum_scans import RunSumScans
from fastgr.step2_handler.run_thread import RunThread

from fastgr.step3_handler.step3_gui_handler import Step3GuiHandler

from fastgr.mantid_handler.browse_file_folder_handler import BrowseFileFolderHandler
from fastgr.mantid_handler.mantid_reduction import GlobalMantidReduction
from fastgr.mantid_handler.mantid_thread import MantidThread

import PyQt4
import PyQt4.QtCore as QtCore
import PyQt4.QtGui as QtGui

import fastgr.fastgrdriver as driver
import fastgr.specify_plots_style as ps


class MainWindow(PyQt4.QtGui.QMainWindow, fastgr.ui_mainWindow.Ui_MainWindow):
    """ Main FastGR window
    """
    debugging = False
    current_folder = os.getcwd()
    configuration_folder = current_folder
    calibration_folder = '/SNS/lustre/NOM/shared/CALIBRATION/2016_2_1B_CAL/'
    characterization_folder = '/SNS/lustre/NOM/shared/CALIBRATION/2016_2_1B_CAL/'
    file_path = os.getcwd()
    table_selection_buffer = {}
    _run_thread_sum_scans = RunThread()
    _run_thread = RunThread()
    _mantid_thread_array = list(itertools.repeat(MantidThread(), 30))
    config_section_name = 'Configuration'

    o_help_autonom = None
    o_help_ndabs = None
    o_help_scans = None
    o_help_mantid = None

    def __init__(self):
        """ Initialization
        Parameters
        ----------
        """
        # Base class
        QtGui.QMainWindow.__init__(self)

	if self.debugging:
	    self.calibration_folder = '/SNS/NOM/IPTS-17118/shared/'
	    self.characterization_folder = '/SNS/NOM/shared/CALIBRATION/'

        # Initialize the UI widgets
        self.ui = fastgr.ui_mainWindow.Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.graphicsView_sq.set_main(self)
 
        self.ui.dockWidget_ipython.setup()

        # set widgets
        self._init_widgets()
        init_step1 = InitStep1(parent=self)
        init_step2 = InitStep2(parent=self)

        # define the event handling methods

        # bragg diffraction tab
        self.connect(self.ui.pushButton_loadBraggFile, QtCore.SIGNAL('clicked()'),
                     self.do_load_bragg_file)
        self.connect(self.ui.checkBox_bank1, QtCore.SIGNAL('toggled(bool)'),
                     self.evt_plot_bragg_bank)
        self.connect(self.ui.checkBox_bank2, QtCore.SIGNAL('toggled(bool)'),
                     self.evt_plot_bragg_bank)
        self.connect(self.ui.checkBox_bank3, QtCore.SIGNAL('toggled(bool)'),
                     self.evt_plot_bragg_bank)
        self.connect(self.ui.checkBox_bank4, QtCore.SIGNAL('toggled(bool)'),
                     self.evt_plot_bragg_bank)
        self.connect(self.ui.checkBox_bank5, QtCore.SIGNAL('toggled(bool)'),
                     self.evt_plot_bragg_bank)
        self.connect(self.ui.checkBox_bank6, QtCore.SIGNAL('toggled(bool)'),
                     self.evt_plot_bragg_bank)
        self.connect(self.ui.comboBox_xUnit, QtCore.SIGNAL('currentIndexChanged(int)'),
                     self.evt_switch_bragg_unit)
        self.connect(self.ui.radioButton_multiBank, QtCore.SIGNAL('toggled(bool)'),
                     self.evt_change_gss_mode)

        self.connect(self.ui.pushButton_rescaleGSAS, QtCore.SIGNAL('clicked()'),
                     self.do_rescale_bragg)

        self.connect(self.ui.pushButton_gsasColorStyle, QtCore.SIGNAL('clicked()'),
                     self.do_set_bragg_color_marker)

        # for tab G(R)
        self.connect(self.ui.pushButton_loadSQ, QtCore.SIGNAL('clicked()'),
                     self.do_load_sq)
        self.connect(self.ui.comboBox_SofQType, QtCore.SIGNAL('currentIndexChanged(int)'),
                     self.evt_plot_sq)
        self.connect(self.ui.pushButton_clearSofQ, QtCore.SIGNAL('clicked()'),
                     self.do_clear_sq)
        self.connect(self.ui.pushButton_showQMinMax, QtCore.SIGNAL('clicked()'),
                     self.do_show_sq_bound)
        self.connect(self.ui.pushButton_generateGR, QtCore.SIGNAL('clicked()'),
                     self.do_generate_gr)
        self.connect(self.ui.pushButton_loadGofR, QtCore.SIGNAL('clicked()'),
                     self.do_load_gr)
        self.connect(self.ui.pushButton_saveGR, QtCore.SIGNAL('clicked()'),
                     self.do_save_gr)
        self.connect(self.ui.pushButton_clearGrCanvas, QtCore.SIGNAL('clicked()'),
                     self.do_clear_gr)

        self.connect(self.ui.doubleSpinBoxQmin, QtCore.SIGNAL('valueChanged(double)'),
                     self.evt_qmin_changed)
        self.connect(self.ui.doubleSpinBoxQmax, QtCore.SIGNAL('valueChanged(double)'),
                     self.evt_qmax_changed)

        self.connect(self.ui.pushButton_rescaleSq, QtCore.SIGNAL('clicked()'),
                     self.do_rescale_sofq)
        self.connect(self.ui.pushButton_rescaleGr, QtCore.SIGNAL('clicked()'),
                     self.do_rescale_gofr)

        self.connect(self.ui.pushButton_grColorStyle, QtCore.SIGNAL('clicked()'),
                     self.do_set_gofr_color_marker)
        self.connect(self.ui.pushButton_sqColorStyle, QtCore.SIGNAL('clicked()'),
                     self.do_set_sq_color_marker)

        #  menu operations
        self.connect(self.ui.actionReset_GofR_tab, QtCore.SIGNAL('triggered()'),
                     self.do_reset_gr_tab)
        self.connect(self.ui.actionReset_GSAS_tab, QtCore.SIGNAL('triggered()'),
                     self.do_reset_gsas_tab)
        self.connect(self.ui.actionQuit, QtCore.SIGNAL('triggered()'),
                     self.evt_quit)
        self.connect(self.ui.actionCheat_sheet, QtCore.SIGNAL('triggered()'),
                     self.do_show_help)

        # organize widgets group
        self._braggBankWidgets = {1: self.ui.checkBox_bank1,
                                  2: self.ui.checkBox_bank2,
                                  3: self.ui.checkBox_bank3,
                                  4: self.ui.checkBox_bank4,
                                  5: self.ui.checkBox_bank5,
                                  6: self.ui.checkBox_bank6}
        self._braggBankWidgetRecords = dict()
        for bank_id in self._braggBankWidgets.keys():
            checked = self._braggBankWidgets[bank_id].isChecked()
            self._braggBankWidgetRecords[bank_id] = checked

        # define the driver
        self._myController = driver.FastGRDriver()

        # class variable for easy access
        self._gssGroupName = None
        self._currDataDir = None

        # some controlling variables
        self._currBraggXUnit = str(self.ui.comboBox_xUnit.currentText())
        if self._currBraggXUnit == 'Q':
            self._currBraggXUnit = 'MomentumTransfer'
        self._onCanvasGSSBankList = list()

        # mutex-like variables
        self._noEventBankWidgets = False

        # help (refer to DGSPlanner and HFIR Powder reduction GUI)
        self._assistantProcess = QtCore.QProcess(self)

        return

    def _init_widgets(self):
        """ Initialize widgets
        Returns
        -------

        """
        self.ui.comboBox_xUnit.clear()
        self.ui.comboBox_xUnit.addItems(['TOF', 'dSpacing', 'Q'])

        self.ui.treeWidget_braggWSList.set_main_window(self)
        self.ui.treeWidget_braggWSList.add_main_item('workspaces', append=True, as_current_index=False)

        self.ui.treeWidget_grWsList.set_main_window(self)
        self.ui.treeWidget_grWsList.add_main_item('workspaces', append=True, as_current_index=False)
        self.ui.treeWidget_grWsList.add_main_item('SofQ', append=True, as_current_index=False)

        self.ui.dockWidget_ipython.iPythonWidget.set_main_application(self)

        self.ui.comboBox_SofQType.clear()
        self.ui.comboBox_SofQType.addItem('S(Q)')
        self.ui.comboBox_SofQType.addItem('S(Q)-1')
        self.ui.comboBox_SofQType.addItem('Q[S(Q)-1]')
        self.ui.comboBox_SofQType.setCurrentIndex(0)

        self.ui.radioButton_multiBank.setChecked(True)

        # add the combo box for PDF type
        self.ui.comboBox_pdfType.addItems(['G(r)', 'g(r)', 'RDF(r)'])

        # some starting value
        self.ui.doubleSpinBoxDelR.setValue(0.01)

        # set a constant item to combobox Sq
        self.ui.comboBox_SofQ.addItem('All')

        return

    def do_set_bragg_color_marker(self):
        """
        set the color/marker to plots on bragg canvas
        :return:
        """
        # get the current figure' on-shown plots
        plot_id_label_list = self.ui.graphicsView_bragg.get_current_plots()

        # get the line ID, color, and marker
        plot_id_list, color, marker = ps.get_plots_color_marker(self, plot_label_list=plot_id_label_list)
        if plot_id_list is None:
            # operation is cancelled by user
            pass
        else:
            # set the color and mark
            for plot_id in plot_id_list:
                self.ui.graphicsView_bragg.updateLine(ikey=plot_id, linecolor=color, marker=marker,
                                                      markercolor=color)

        return

    def do_set_gofr_color_marker(self):
        """
        set the color/marker to plots on G(r) canvas
        :return:
        """
        # get the line ID, color, and marker
        plot_id_label_list = self.ui.graphicsView_gr.get_current_plots()

        # get the line ID, color, and marker
        plot_id_list, color, marker = ps.get_plots_color_marker(self, plot_label_list=plot_id_label_list)
        if plot_id_list is None:
            # operation is cancelled by user
            pass
        else:
            # set the color and mark
            for plot_id in plot_id_list:
                self.ui.graphicsView_gr.updateLine(ikey=plot_id, linecolor=color, marker=marker,
                                                   markercolor=color)

        return

    def do_set_sq_color_marker(self):
        """
        set the color/marker on S(q) canvas
        Returns:

        """
        # get the line ID, color, and marker
        plot_id_label_list = self.ui.graphicsView_sq.get_current_plots()

        # get the line ID, color, and marker
        plot_id_list, color, marker = ps.get_plots_color_marker(self, plot_label_list=plot_id_label_list)
        if plot_id_list is None:
            # operation is cancelled by user
            pass
        else:
            # set the color and mark
            for plot_id in plot_id_list:
                self.ui.graphicsView_sq.updateLine(ikey=plot_id, linecolor=color, marker=marker,
                                                   markercolor=color)

        return

    def do_show_help(self):
        """ Show help
        Copied from DGSPlanner
        """
        # close previous service
        self._assistantProcess.close()
        self._assistantProcess.waitForFinished()

        # launch
        # helper_url = QtCore.QUrl('fastgr_helper.html')
        helper_url = QtCore.QUrl('https://neutrons.github.io/FastGR/index.html')
        QtGui.QDesktopServices.openUrl(helper_url)

        return

    def do_clear_gr(self):
        """
        Clear G(r) canvas
        Returns
        -------

        """
        self.ui.graphicsView_gr.clear_all_lines()
        self.ui.graphicsView_gr.reset_color()

        return

    def do_clear_sq(self):
        """
        Remove all lines from S(Q) canvas
        Returns
        -------

        """
        self.ui.graphicsView_sq.clear_all_lines()
        self.ui.graphicsView_sq.reset_line_color_marker_index()

        return

    def do_generate_gr(self):
        """
        Generate G(r) by the present user-setup
        Returns
        -------

        """
        # get S(Q) workspace
        selected_sq = str(self.ui.comboBox_SofQ.currentText())
        if selected_sq == 'All':
            sq_ws_name_list = list()
            for index in range(self.ui.comboBox_SofQ.count()):
                item = str(self.ui.comboBox_SofQ.itemText(index))
                if item != 'All':
                    # add S(Q) name unless it is 'All'
                    sq_ws_name_list.append(item)
                # END-IF
            # END-FOR
        else:
            # selected S(Q) is a single S(Q) name
            sq_ws_name_list = [selected_sq]

        # get r-range and q-range
        min_r = float(self.ui.doubleSpinBoxRmin.value())
        max_r = float(self.ui.doubleSpinBoxRmax.value())
        delta_r = float(self.ui.doubleSpinBoxDelR.value())

        min_q = float(self.ui.doubleSpinBoxQmin.value())
        max_q = float(self.ui.doubleSpinBoxQmax.value())

        use_filter = self.ui.checkBox_pdfFilter.isChecked()
        rho0_str = str(self.ui.lineEdit_rho.text())
        if rho0_str.isdigit():
            rho0 = float(rho0_str)
        else:
            rho0 = None

        # PDF type
        pdf_type = str(self.ui.comboBox_pdfType.currentText())

        # loop for all selected S(Q)
        for sq_ws_name in sq_ws_name_list:
            # calculate G(r)
            gr_ws_name = self._myController.calculate_gr(sq_ws_name, pdf_type, min_r, delta_r, max_r,
                                                         min_q, max_q, use_filter, rho0)

            # plot G(R)
            vec_r, vec_g, vec_ge = self._myController.get_gr(min_q, max_q)
            key_plot = gr_ws_name
            self.ui.graphicsView_gr.plot_gr(key_plot, vec_r, vec_g, vec_ge, False)

            # add to tree
            gr_param_str = 'Q: (%.3f, %.3f)' % (min_q, max_q)
            self.ui.treeWidget_grWsList.add_gr(gr_param_str, gr_ws_name)
        # END-FOR

        return

    def do_rescale_bragg(self):
        """

        :return:
        """
        min_y_value = self.ui.graphicsView_bragg.get_y_min()
        max_y_value = self.ui.graphicsView_bragg.get_y_max()
        delta_y = max(1, max_y_value - min_y_value)

        y_lower_limit = min_y_value - delta_y * 0.05
        y_upper_limit = max_y_value + delta_y * 0.05

        self.ui.graphicsView_bragg.setXYLimit(ymin=y_lower_limit, ymax=y_upper_limit)

        return

    def do_rescale_sofq(self):
        """

        :return:
        """
        min_y_value = self.ui.graphicsView_sq.get_y_min()
        max_y_value = self.ui.graphicsView_sq.get_y_max()
        delta_y = max(1, max_y_value - min_y_value)

        y_lower_limit = min_y_value - delta_y * 0.05
        y_upper_limit = max_y_value + delta_y * 0.05

        self.ui.graphicsView_sq.setXYLimit(ymin=y_lower_limit, ymax=y_upper_limit)

        return

    def do_rescale_gofr(self):
        """

        :return:
        """
        min_y_value = self.ui.graphicsView_gr.get_y_min()
        max_y_value = self.ui.graphicsView_gr.get_y_max()
        delta_y = max(1, max_y_value - min_y_value)

        y_lower_limit = min_y_value - delta_y * 0.05
        y_upper_limit = max_y_value + delta_y * 0.05

        self.ui.graphicsView_gr.setXYLimit(ymin=y_lower_limit, ymax=y_upper_limit)

        return

    def do_reset_gr_tab(self):
        """
        Reset G(r)-tab, including deleting all the G(r) and S(Q) workspaces,
        clearing the G(r) and S(Q) trees, and clearing both G(r) and S(Q) canvas
        Returns:
        None
        """
        # get workspace from trees
        workspace_list = self.ui.treeWidget_grWsList.get_workspaces()

        # reset the tree to initial status
        self.ui.treeWidget_grWsList.reset_gr_tree()

        # delete all the workspaces
        for workspace in workspace_list:
            self._myController.delete_workspace(workspace)

        # clear all the canvas
        self.ui.graphicsView_gr.clear_all_lines()
        self.ui.graphicsView_sq.clear_all_lines()

        # clear the S(Q) combo box
        self.ui.comboBox_SofQ.clear()
        self.ui.comboBox_SofQ.addItem('All')
        

        return

    def do_reset_gsas_tab(self):
        """
        Reset the GSAS-tab including
        1. deleting all the GSAS workspaces
        2. clearing the GSAS tree
        3. clearing GSAS canvas
        Returns:
        None
        """
        # delete all workspaces: get GSAS workspaces from tree
        gsas_group_node_list = self.ui.treeWidget_braggWSList.get_main_nodes(output_str=False)
        for gsas_group_node in gsas_group_node_list:
            # skip if the workspace is 'workspaces'
            gss_node_name = str(gsas_group_node.text())
            if gss_node_name == 'workspaces':
                continue
            # get the split workspaces' names and delete
            gsas_ws_name_list = self.ui.treeWidget_braggWSList.get_child_nodes(gsas_group_node, output_str=True)
            for workspace in gsas_ws_name_list:
                self._myController.delete_workspace(workspace)
            # END-FOR

            # guess for the main workspace and delete
            gss_main_ws = gss_node_name.split('_group')[0]
            self._myController.delete_workspace(gss_main_ws, no_throw=True)
            
        # END-FOR (gsas_group_node)

        # reset the GSAS tree
        self.ui.treeWidget_braggWSList.reset_bragg_tree()

        # clear the canvas
        self.ui.graphicsView_bragg.reset()

        # clear the checkboxes for banks
        self._noEventBankWidgets = True
        for check_box in self._braggBankWidgets.values():
            check_box.setChecked(False)
        self._noEventBankWidgets = False

        return

    def plot_bragg(self, bragg_ws_list,  clear_canvas=False):
        """
        Parameters
        ----------
        bragg_ws_list: list of (single spectrum) Bragg workspace
        clear_canvas

        Returns
        -------

        """
        # check
        assert isinstance(bragg_ws_list, list)

        # clear canvas if necessary
        if clear_canvas:
            self.ui.graphicsView_bragg.reset()

        # get unit
        curr_unit = self._currBraggXUnit
        # curr_unit = str(self.ui.comboBox_xUnit.currentText())
        # if curr_unit == 'Q':
        #     curr_unit =

        # plot all workspsaces
        for bragg_ws_name in bragg_ws_list:

            # get the last section of the workspace name: _bank%d
            postfix = bragg_ws_name.split('_')[-1]

            if postfix.startswith('bank') and 0 <= int(postfix.split('bank')[1]) <= 6:
                # belonged to a Bragg-workspace-group
                ws_group = bragg_ws_name.split('_%s' % postfix)[0] + '_group'
                bank_id = int(bragg_ws_name.split('bank')[1])
                vec_x, vec_y, vec_e = self._myController.get_bragg_data(ws_group_name=ws_group, bank_id=bank_id,
                                                                        x_unit=curr_unit)

                # construct dictionary for plotting
                plot_data_dict = dict()
                plot_data_dict[ws_group] = dict()
                plot_data_dict[ws_group][bank_id] = (vec_x, vec_y, vec_e)

                # set the bank to be checked
                self._braggBankWidgets[bank_id].setChecked(True)

                # plot
                self.ui.graphicsView_bragg.plot_banks(plot_data_dict, curr_unit)

            else:
                vec_x, vec_y, vec_e = self._myController.get_ws_data(bragg_ws_name)
                self.ui.graphicsView_bragg.plot_general_ws(bragg_ws_name, vec_x, vec_y, vec_e)

        return

    def plot_gr(self, gr_ws_name_list):
        """
        Plot G(r) by their names (workspace as protocol)
        Parameters
        ----------
        gr_ws_name_list: list of G(r) workspaces

        Returns
        -------

        """
        # check
        assert isinstance(gr_ws_name_list, list) and len(gr_ws_name_list) > 0

        # plot G(R)
        for gr_ws_name in gr_ws_name_list:
            vec_r, vec_g, vec_ge = self._myController.get_gr_by_ws(gr_ws_name)
            key_plot = gr_ws_name
            self.ui.graphicsView_gr.plot_gr(key_plot, vec_r, vec_g, vec_ge, False)

        return

    def plot_sq(self, sq_ws_name, clear_prev):
        """
        Plot S(Q)
        Parameters
        ----------
        sq_ws_name
        clear_prev

        Returns
        -------

        """
        # clear previous lines
        if clear_prev:
            self.ui.graphicsView_sq.reset()

        # get data
        vec_q, vec_sq, vec_se = self._myController.get_sq(sq_ws_name)

        # get the unit & do conversion if necessary
        sq_type = str(self.ui.comboBox_SofQType.currentText())
        if sq_type == 'S(Q)':
            # use the original S(Q)
            sq_unit = 'S(Q)'
            vec_y = vec_sq
        elif sq_type == 'S(Q)-1':
            # use S(Q)-1
            sq_unit = 'S(Q)-1'
            vec_y = vec_sq - 1
        elif sq_type == 'Q[S(Q)-1]':
            # use Q(S(Q)-1)
            sq_unit = 'Q[S(Q)-1]'
            vec_y = vec_q * (vec_sq - 1)
        else:
            raise RuntimeError('None of S(Q), S(Q)-1 or Q(S(Q)-1) is chosen.')

        # plot
        if clear_prev:
            reset = True
        else:
            reset = False
        self.ui.graphicsView_sq.plot_sq(sq_ws_name, vec_q, vec_y, vec_se, sq_unit, reset)

        return

    def do_load_bragg_file(self):
        """
        Load Bragg files including GSAS, NeXus, 3-column ASCii.
        Returns
        -------
        """
        # get file
        ext = 'GSAS (*.gsa);;DAT (*.dat);;All (*.*)'

        # get default dir
        if self._currDataDir is None:
            default_dir = os.getcwd()
        else:
            default_dir = self._currDataDir

        bragg_file_name = str(QtGui.QFileDialog.getOpenFileName(self, 'Choose Bragg File', default_dir, ext))
        if bragg_file_name is None or bragg_file_name == '':
            return

        # update stored data directory
        self._currDataDir = os.path.abspath(bragg_file_name)

        # load file
        gss_ws_name = self._myController.load_bragg_file(bragg_file_name)

        # split
        # FIXME - _gssGroupName may have an issie with multiple-GSS mode
        self._gssGroupName, banks_list, bank_angles = self._myController.split_to_single_bank(gss_ws_name)

        # add to tree
        self.ui.treeWidget_braggWSList.add_bragg_ws_group(self._gssGroupName, banks_list)

        # get plot mode
        single_gss_mode = self.ui.radioButton_multiBank.isChecked()

        if single_gss_mode:
            # single-GSS/multi-bank mode
            # rename bank
            for bank_id in self._braggBankWidgets.keys():
                bank_check_box = self._braggBankWidgets[bank_id]

                if bank_id > len(bank_angles) or bank_angles[bank_id - 1] is None:
                    bank_check_box.setText('Bank %d' % bank_id)
                else:
                    bank_check_box.setText('Bank %.1f' % bank_angles[bank_id - 1])
                    # END-IF
                # END-IF-ELSE
            # END-FOR

            # clear all previous lines
            self.ui.graphicsView_bragg.reset()

            # banks
            self._onCanvasGSSBankList = self.get_bragg_banks_selected()
            if len(self._onCanvasGSSBankList) == 0:
                # select bank 1 as default
                self._noEventBankWidgets = True
                self.ui.checkBox_bank1.setChecked(True)
                self._noEventBankWidgets = False
                self._onCanvasGSSBankList = self.get_bragg_banks_selected()
        # END-IF
        # while in multiple-gss mode, no change will be made on the canvas at all

        # prepare to plot new Bragg
        # change unit
        ws_data_dict = dict()
        gss_group_name = gss_ws_name + '_group'
        for bank_id in self._onCanvasGSSBankList:
            vec_x, vec_y, vec_e = self._myController.get_bragg_data(gss_group_name, bank_id, self._currBraggXUnit)
            ws_data_dict[bank_id] = (vec_x, vec_y, vec_e)
        plot_data_dict = {gss_group_name: ws_data_dict}

        # plot
        self.ui.graphicsView_bragg.plot_banks(plot_data_dict, self._currBraggXUnit)

        # reset unit
        self.reset_bragg_data_range(self._currBraggXUnit)

        return

    def do_load_gr(self):
        """
        Load an ASCII file containing G(r)
        Returns:
        """
        # get default dir
        if self._currDataDir is None:
            default_dir = os.getcwd()
        else:
            default_dir = self._currDataDir

        # pop out file
        file_filter = 'Data Files (*.data);;All Files (*.*)'
        g_file_name = str(QtGui.QFileDialog.getOpenFileName(self, 'Open a G(r) file', default_dir, file_filter))

        # return if operation is cancelled
        if g_file_name is None or g_file_name == '':
            return
        else:
            # update current data directory
            self._currDataDir = os.path.abspath(g_file_name)

        # read file
        status, ret_obj = self._myController.load_gr(g_file_name)
        if not status:
            err_msg = ret_obj
	    print '[Error]: %s' % err_msg
            return
        else:
            gr_ws_name = ret_obj

        # plot
        self.plot_gr([gr_ws_name])

        # put the loaded G(r) workspace to tree 'workspaces'
        self.ui.treeWidget_grWsList.add_child_main_item('workspaces', gr_ws_name)

        return

    def do_load_sq(self):
        """
        Load S(Q) from file
        Returns
        -------

        """
        # get default dir
        if self._currDataDir is None:
            default_dir = os.getcwd()
        else:
            default_dir = self._currDataDir

        # get the file
        ext = 'DAT (*.dat);;All (*.*)'
        sq_file_name = str(QtGui.QFileDialog.getOpenFileName(self, 'Choose S(Q) File', default_dir, ext))
        if sq_file_name is None or sq_file_name == '':
            return
        else:
            # update current data directory
            self._currDataDir = os.path.abspath(sq_file_name)

        # load S(q)
        sq_ws_name, q_min, q_max = self._myController.load_sq(sq_file_name)

        # set to the tree and combo box
        self.ui.treeWidget_grWsList.add_sq(sq_ws_name)
        self.ui.comboBox_SofQ.addItem(sq_ws_name)
        self.ui.comboBox_SofQ.setCurrentIndex(self.ui.comboBox_SofQ.count()-1)

        # set the UI widgets
        self.ui.doubleSpinBoxQmin.setValue(q_min)
        self.ui.doubleSpinBoxQmax.setValue(q_max)

        # plot the figure
        self.evt_plot_sq()

        # calculate and calculate G(R)
        self.do_generate_gr()

        return

    def do_save_gr(self):
        """
        Save the selected the G(r) from menu to ASCII file
        Returns
        -------

        """
        # read the selected item from the tree
        gr_name_list = self.ui.treeWidget_grWsList.get_selected_items_of_level(2, excluded_parent='SofQ',
                                                                               return_item_text=True)
        if len(gr_name_list) != 1:
            err_msg = 'Error! Only 1 workspace of G(r) that can be selected.  So far %d is selected.' \
                      'They are %s.' % (len(gr_name_list), str(gr_name_list))
            QtGui.QMessageBox.warning(self, 'Error', err_msg)
            return
        else:
            gr_ws_name = gr_name_list[0]

        # pop-up a dialog for the file to save
        default_dir = os.getcwd()
        file_ext = 'Data (*.dat)'
        gr_file_name = str(QtGui.QFileDialog.getSaveFileName(self, caption='Save G(r)',
                                                             directory=default_dir, filter=file_ext))

        # save!
        self._myController.save_ascii(gr_ws_name, gr_file_name)

        return

    def do_show_sq_bound(self):
        """
        Show or hide the left and right boundary of the S(Q)
        Returns
        -------

        """
        q_left = self.ui.doubleSpinBoxQmin.value()
        q_right = self.ui.doubleSpinBoxQmax.value()
        self.ui.graphicsView_sq.toggle_boundary(q_left, q_right)

        return

    def get_bragg_banks_selected(self):
        """
        Find out the banks of bragg-tab that are selected.
        Returns:

        """
        bank_id_list = list()
        for bank_id in self._braggBankWidgets.keys():
            # access the checkbox
            bank_checkbox = self._braggBankWidgets[bank_id]
            # append
            if bank_checkbox.isChecked():
                bank_id_list.append(bank_id)
        # END-FOR

        return bank_id_list

    def evt_change_gss_mode(self):
        """
        switch between multi-gss/single-bank mode and singl-gss/multiple-bank mode
        Returns
        -------

        """
        # check the mode (multiple bank or multiple GSS)
        single_gss_mode = self.ui.radioButton_multiBank.isChecked()
        assert single_gss_mode != self.ui.radioButton_multiGSS.isChecked()

        # get the banks that are selected
        to_plot_bank_list = self.get_bragg_banks_selected()
        on_canvas_ws_list = self.ui.graphicsView_bragg.get_workspaces()
        # return with doing anything if the canvas is empty, i.e., no bank is selected
        if len(to_plot_bank_list) == 0:
            return
        # return if there is no workspace that is plotted on canvas now
        if len(on_canvas_ws_list) == 0:
            return

        # set to single GSS
        self.ui.graphicsView_bragg.set_to_single_gss(single_gss_mode)

        # process the plot with various situation
        if single_gss_mode:
            # switch to single GSAS mode from multiple GSAS mode.
            #  select the arbitrary gsas file to
            assert len(to_plot_bank_list) == 1, 'From multi-GSS-single-Bank mode, only 1 bank can be selected.'

            # skip if there is one and only one workspace
            if len(on_canvas_ws_list) == 1:
                return
            else:
                status, ws_name_list = self.ui.treeWidget_braggWSList.get_current_main_nodes()
                if not status:
                    raise RuntimeError(str(ws_name_list))
                else:
                    plot_ws_name = ws_name_list[0]

            # plot
            plot_ws_name = plot_ws_name.split('_group')[0]
            bragg_bank_ws = '%s_bank%d' % (plot_ws_name, to_plot_bank_list[0])
            self.plot_bragg(bragg_ws_list=[bragg_bank_ws], clear_canvas=True)

        else:
            # multiple GSAS mode. as currently there is one GSAS file that is plot, then the first bank
            # that is plotted will be kept on the canvas
            # assumption: switched from single-bank mode
            assert len(self.ui.graphicsView_bragg.get_workspaces()) == 1

            # skip if there is one and only 1 bank that is selected
            if len(to_plot_bank_list) == 1:
                return
            else:
                # choose first bank
                bank_on_canvas = to_plot_bank_list[0]

            # disable all the banks except the one to plot. Notice the mutex must be on
            self._noEventBankWidgets = True
            for bank_id in self._braggBankWidgets.keys():
                if bank_id != bank_on_canvas:
                    self._braggBankWidgets[bank_id].setChecked(False)
            self._noEventBankWidgets = False

            # plot
            plot_ws_name = on_canvas_ws_list[0]
            bragg_bank_ws = '%s_bank%d' % (plot_ws_name, bank_on_canvas)
            self.plot_bragg(bragg_ws_list=[bragg_bank_ws], clear_canvas=True)

            # set
            self._onCanvasGSSBankList = [bank_on_canvas]

        # END-IF-ELSE

        return

    def evt_plot_bragg_bank(self):
        """
        Find out which bank will be plot

        cases to trigger this event:
        1. select more banks
        2. deselect some banks

        Returns
        -------

        """
        # check mutex for not responding the event
        if self._noEventBankWidgets:
            return
        # check
        assert self._gssGroupName is not None, 'GSAS group name cannot be None'

        # get mode for plotting
        plot_multi_gss = self.ui.radioButton_multiGSS.isChecked()

        # find the change of the banks
        current_bank_set = set(self.get_bragg_banks_selected())
        prev_bank_set = set(self._onCanvasGSSBankList)

        if plot_multi_gss:
            # multi-gss/single-bank mode
            # get the banks to remove
            rm_bank_list = self._onCanvasGSSBankList[:]

            # deselect all the old banks and thus turn on the mutex
            self._noEventBankWidgets = True
            # turn off the
            self.set_bragg_banks_selected(self._onCanvasGSSBankList, False)
            # turn off mutex
            self._noEventBankWidgets = False

            # set banks to add
            new_bank_list = list(current_bank_set - prev_bank_set)
            assert len(new_bank_list) <= 1, 'Impossible to have more than 1 banks selected in multi-GSS mode.'

            # set the current on canvas
            self._onCanvasGSSBankList = new_bank_list

            print '[DB...BAT] Multi-GSS-Mode: New ... ', new_bank_list, '; Remove... ', rm_bank_list

        else:
            # single-gss/multi-bank mode
            # determine the banks to add
            new_bank_list = list(current_bank_set - prev_bank_set)
            rm_bank_list = list(prev_bank_set - current_bank_set)

            print '[DB...BAT] Single-GSS-Mode: New ... ', new_bank_list, '; Remove... ', rm_bank_list

            # set the current on-canvas
            self._onCanvasGSSBankList = list(current_bank_set)

        # END-IF-ELSE

        # get GSS data (group)
        gss_group_list = self.ui.treeWidget_braggWSList.get_main_nodes()
        gss_group_list.remove('workspaces')

        # remove banks
        for gss_group_name in gss_group_list:
            self.ui.graphicsView_bragg.remove_gss_banks(gss_group_name, rm_bank_list)

        # get new bank data
        plot_data_dict = dict()
        for ws_group in gss_group_list:
            ws_data_dict = dict()
            for bank_id in new_bank_list:
                vec_x, vec_y, vec_e = self._myController.get_bragg_data(ws_group, bank_id, self._currBraggXUnit)
                ws_data_dict[bank_id] = (vec_x, vec_y, vec_e)
            # END-FOR
            plot_data_dict[ws_group] = ws_data_dict
        # END-FOR

        if plot_multi_gss:
            self.ui.graphicsView_bragg.set_to_single_gss(False)
        else:
            self.ui.graphicsView_bragg.set_to_single_gss(True)

        # plot new
        self.ui.graphicsView_bragg.plot_banks(plot_data_dict, self._currBraggXUnit)

        # reset
        self.reset_bragg_data_range(self._currBraggXUnit)

        return

    def evt_switch_bragg_unit(self):
        """
        Unit of Bragg plot is changed.
        Requirements:
        1. clear the canvas
        2. plot all the banks in the new units
        3. reset the limit
        Returns
        -------

        """
        # get current unit and check whether re-plot all banks is not a choice
        x_unit = str(self.ui.comboBox_xUnit.currentText())
        # convert Q to MomentumTransfer by Mantid standard
        if x_unit == 'Q':
            x_unit = 'MomentumTransfer'

        if x_unit == self._currBraggXUnit:
            # return if no change. then this cannot happen
            raise RuntimeError('New unit %s is same as original unit %s.' % (x_unit, self._currBraggXUnit))
        else:
            self._currBraggXUnit = x_unit

        # reset canvas
        self.ui.graphicsView_bragg.reset()

        # get bank to plot
        bank_list = self.get_bragg_banks_selected()

        # get data sets
        #  = self.ui.treeWidget_braggWSList.get_main_nodes()
        ws_group_list = self.ui.treeWidget_braggWSList.get_selected_items_of_level(
            target_item_level=1, excluded_parent=None, return_item_text=True)
        if 'workspace' in ws_group_list:
            ws_group_list.remove('workspaces')
        assert len(ws_group_list) > 0, 'At least 1 GSS file must be selected.'

        # check
        assert len(bank_list) == 1 or len(ws_group_list) == 1, 'Must be either single bank (%d now) or ' \
                                                               'single GSS (%d now).' % (len(bank_list),
                                                                                         len(ws_group_list))

        # get data and plot
        plot_data_dict = dict()
        for ws_group in ws_group_list:
            ws_data_dict = dict()
            for bank_id in bank_list:
                vec_x, vec_y, vec_e = self._myController.get_bragg_data(ws_group, bank_id, self._currBraggXUnit)
                ws_data_dict[bank_id] = (vec_x, vec_y, vec_e)
            # END-FOR
            plot_data_dict[ws_group] = ws_data_dict
        # END-FOR

        # plot
        self.ui.graphicsView_bragg.plot_banks(plot_data_dict, self._currBraggXUnit)

        # reset unit
        self.reset_bragg_data_range(x_unit)

        return

    def reset_bragg_data_range(self, x_unit):
        """

        Parameters
        ----------
        x_unit

        Returns
        -------

        """
        if x_unit == 'TOF':
            self.ui.graphicsView_bragg.setXYLimit(xmin=0, xmax=20000, ymin=None, ymax=None)
        elif x_unit == 'MomentumTransfer':
            self.ui.graphicsView_bragg.setXYLimit(xmin=0, xmax=20, ymin=None, ymax=None)
        elif x_unit == 'dSpacing':
            self.ui.graphicsView_bragg.setXYLimit(xmin=0, xmax=7, ymin=None, ymax=None)
        else:
            raise RuntimeError('Unit %s unknown' % x_unit)

        return

    def evt_plot_sq(self):
        """ Event handling to plot S(Q)
        Returns
        -------

        """
        # get the raw S(Q)
        sq_name = self._myController.get_current_sq_name()

        # plot S(Q)
        self.plot_sq(sq_name, clear_prev=True)

        return

    def evt_qmax_changed(self):
        """
        Handle if the user change the value of Qmax of S(Q) including
        1. moving the right boundary in S(q) figure
        Returns:

        """
        q_min = self.ui.doubleSpinBoxQmin.value()
        q_max = self.ui.doubleSpinBoxQmax.value()

        if q_min < q_max and self.ui.graphicsView_sq.is_boundary_shown():
            self.ui.graphicsView_sq.move_right_indicator(q_max, relative=False)

        return

    def evt_qmin_changed(self):
        """

        Returns:

        """
        q_min = self.ui.doubleSpinBoxQmin.value()
        q_max = self.ui.doubleSpinBoxQmax.value()

        if q_min < q_max and self.ui.graphicsView_sq.is_boundary_shown():
            self.ui.graphicsView_sq.move_left_indicator(q_min, relative=False)

        return

    def evt_quit(self):
        """
        Quit the application
        Returns:

        """
        self.close()

    def get_default_data_dir(self):
        """
        Get default data directory
        Returns:

        """
        return self._currDataDir

    def get_workflow(self):
        """
        Return the reference to the main workflow controller
        Returns: workflow controller

        """
        return self._myController

    def process_workspace_change(self, new_ws_list):
        """
        Process (including
        1. add workspace name to tree list and etc) when detecting that
        there is some change to any workspace

        Parameters
        ----------
        new_ws_list :: list of new workspaces' names

        Returns
        -------

        """
        # check input
        assert isinstance(new_ws_list, list), 'Input workspace list must be a list of string' \
                                              'but not %s.' % str(type(new_ws_list))

        # TODO - Figure out what to do!
        # print 'current tab = ', self.ui.tabWidget_2.currentIndex(), self.ui.tabWidget_2.currentWidget(),
        # print self.ui.tabWidget_2.currentWidget().objectName()
        # print 'current workspaces: ', self._myController.get_current_workspaces()

        # add to tree
        if len(new_ws_list) > 0:
            if self.ui.tabWidget_2.currentWidget().objectName() == 'tab_gR':
                for new_ws in new_ws_list:
                    ws_unit = self._myController.get_ws_unit(new_ws)
                    if ws_unit != 'MomentumTransfer':
                        is_gr = True
                    else:
                        is_gr = False
                    self.ui.treeWidget_grWsList.add_arb_gr(new_ws, is_gr)
            elif self.ui.tabWidget_2.currentWidget().objectName() == 'tab_bragg':
                for new_ws in new_ws_list:
                    self.ui.treeWidget_braggWSList.add_arb_gr(new_ws)

        return

    def remove_gr_from_plot(self, gr_name):
        """
        Remove a GofR line from GofR canvas
        Args:
            gr_name: supposed to the G(r) name that is same as workspace name and plot key on canvas as well

        Returns:

        """
        # check
        assert isinstance(gr_name, str)

        # remove
        self.ui.graphicsView_gr.remove_gr(plot_key=gr_name)

        return

    def remove_gss_from_plot(self, gss_group_name, gss_bank_ws_name_list):
        """
        Remove a GSAS group from canvas if they exits

        Args:
            gss_group_name: name of the GSS node, i.e., GSS workspace group's name
            gss_bank_ws_name_list: list of names of GSS single banks' workspace name

        Returns:

        """
        # check
        assert isinstance(gss_group_name, str), 'GSS group workspace name must be a string but not %s.' \
                                                '' % str(type(gss_group_name))
        assert isinstance(gss_bank_ws_name_list, list) and len(gss_bank_ws_name_list) > 0

        # get bank IDs
        bank_ids = list()
        for gss_bank_ws in gss_bank_ws_name_list:
            bank_id = int(gss_bank_ws.split('_bank')[-1])
            bank_ids.append(bank_id)

        # remove
        self.ui.graphicsView_bragg.remove_gss_banks(gss_group_name, bank_ids)

        # check if there is no such bank's plot on figure, make sure the checkbox is unselected
        # turn on the mutex lock
        self._noEventBankWidgets = True

        for bank_id in range(1, 7):
            has_plot_on_canvas = len(self.ui.graphicsView_bragg.get_ws_name_on_canvas(bank_id)) > 0
            self._braggBankWidgets[bank_id].setChecked(has_plot_on_canvas)

        # turn off the mutex lock
        self._noEventBankWidgets = False


        return

    def remove_sq_from_plot(self, sq_name):
        """
        Remove an SofQ line from SofQ canvas
        Args:
            sq_name: supposed to be the S(Q) name which is same as workspace name and plot key of canvas

        Returns:

        """
        # check
        assert isinstance(sq_name, str)

        # remove
        if self.ui.graphicsView_sq.is_on_canvas(sq_name):
            self.ui.graphicsView_sq.remove_sq(plot_key=sq_name)

        return

    def set_bragg_banks_selected(self, bank_id_list, status):
        """
        set the status of selected bank IDs
        Parameters
        ----------
        bank_id_list
        status

        Returns
        -------

        """
        # check ...
        # TODO/NOW - finish it

        #
        print '[DB...BAT] Banks ', bank_id_list, ' are set to ', status, ' without mutex locked'

        # set
        for bank_id in bank_id_list:
            self._braggBankWidgets[bank_id].setChecked(status)

        return

    def set_bragg_ws_to_plot(self, gss_group_name):
        """
        Set a Bragg workspace group to plot.  If the Bragg-tab is in
        (1) single-GSS mode, then switch to plot this gss_group
        (2) multiple-GSS mode, then add this group to current canvas
        Parameters
        ----------
        gss_group_name

        Returns
        -------

        """
        # check
        assert isinstance(gss_group_name, str), 'GSS workspace group name is expected to be a string, but not' \
                                                ' %s.' % str(type(gss_group_name))

        # rule out the unsupported situation
        assert gss_group_name.endswith('_group'), 'GSAS workspace group\' name must be ends with _group, ' \
                                                  'but not as %s.' % gss_group_name
        root_ws_name = gss_group_name.split('_group')[0]

        # process
        if self.ui.radioButton_multiBank.isChecked():
            # single-GSS/multi-bank mode
            # reset canvas
            self.ui.graphicsView_bragg.reset()

            # get the banks to plot
            selected_banks = self.get_bragg_banks_selected()

            bragg_ws_list = ['%s_bank%d' % (root_ws_name, bank_id) for bank_id in selected_banks]
            self.plot_bragg(bragg_ws_list=bragg_ws_list, clear_canvas=False)

        else:
            # multiple-GSS/single-bank mode
            # canvas is not be reset

            # get the bank to plot
            selected_banks = self.get_bragg_banks_selected()
            assert len(selected_banks) <= 1, 'At most 1 bank can be plot in multiple-GSS mode.'

            # form the workspace
            bragg_ws = '%s_bank%d' % (root_ws_name, selected_banks[0])

            self.plot_bragg(bragg_ws_list=[bragg_ws], clear_canvas=False)

        # END-IF-ELSE

        return

    def set_ipython_script(self, script):
        """
        Write a command (python script) to ipython console
        Parameters
        ----------
        script

        Returns
        -------

        """
        # check
        assert isinstance(script, str)

        #
        if len(script) == 0:
            # ignore
            return
        else:
            # write to the console
            self.ui.dockWidget_ipython.iPythonWidget.write_command(script)

        return

    def update_sq_boundary(self, boundary_index, new_position):
        """
        Update the S(Q) range at the main app inputs
        Returns
        -------

        """
        # check
        assert isinstance(boundary_index, int)
        assert isinstance(new_position, float)

        # set value
        if boundary_index == 1:
            # left boundary
            self.ui.doubleSpinBoxQmin.setValue(new_position)
        elif boundary_index == 2:
            # right boundary
            self.ui.doubleSpinBoxQmax.setValue(new_position)
        else:
            # exception
            raise RuntimeError('Boundary index %f in method update_sq_boundary() is not '
                               'supported.' % new_position)

        return

    # menu
    def action_preview_ascii_clicked(self):
        o_gui = Step3GuiHandler(parent = self)
        o_gui.browse_file()

    def action_load_configuration_clicked(self):
	o_import_config = ImportConfiguration(parent = self)
	o_import_config.run()
	
    def action_save_configuration_clicked(self):
	o_export_config = ExportConfiguration(parent = self)
	o_export_config.run()

    def help_about_clicked(self):
        _about = AboutDialog(parent=self)
        _about.display()

    def advanced_option_clicked(self):
	_advanced = AdvancedWindow(parent = self)
	_advanced.show()
	
    def main_tab_widget_changed(self, tab_selected):
	if tab_selected == 0:
	    o_gui = Step1GuiHandler(parent = self)
	    self.check_step1_gui()
	if tab_selected == 1:
	    _o_gui = Step2GuiHandler(parent = self)
	    _o_gui.check_gui()

    def help_button_clicked(self, button_name='autonom'):
	help_button_activator(parent=self, button_name=button_name)
	
    # tab1
    def select_current_folder_clicked(self):
        o_gui = Step1GuiHandler(parent = self)
        o_gui.select_working_folder()
        self.check_step1_gui()

    def diamond_edited(self):
        self.check_step1_gui()
        
    def diamond_background_edited(self):
        self.check_step1_gui()
        
    def vanadium_edited(self):
        self.check_step1_gui()
        
    def vanadium_background_edited(self):
        self.check_step1_gui()
        
    def sample_background_edited(self):
        self.check_step1_gui()

    def create_new_autonom_folder_button_clicked(self, status):
	o_gui_handler = Step1GuiHandler(parent = self)
	o_gui_handler.new_autonom_group_box(status = status)
        
    def output_folder_radio_buttons(self):
        o_gui_handler = Step1GuiHandler(parent=self)
        o_gui_handler.manual_output_folder_button_handler()
        o_gui_handler.check_go_button()

    def manual_output_folder_field_edited(self):
        self.check_step1_gui()

    def manual_output_folder_button_clicked(self):
        o_gui = Step1GuiHandler(parent = self)
        o_gui.select_manual_output_folder()
        self.check_step1_gui()
        
    def check_step1_gui(self):
        '''check the status of the step1 GUI in order to enable or not the GO BUTTON at the bottom'''
        o_gui_handler = Step1GuiHandler(parent=self)
        o_gui_handler.check_go_button()
        
    def run_autonom(self):
        """Will first create the output folder, then create the exp.ini file"""
        _run_autonom = RunStep1(parent = self)
        _run_autonom.create_folder()
        _run_autonom.create_exp_ini_file()

    def help_button_clicked_autonom(self):
	self.help_button_clicked(button_name = 'autonom')

    # tab2
    def move_to_folder_clicked(self):
        o_gui = Step2GuiHandler(parent = self)
        o_gui.move_to_folder()
        self.populate_table_clicked()
        
    def populate_table_clicked(self):
        _pop_table = PopulateMasterTable(parent = self)
        _pop_table.run()
        _error_reported = _pop_table.error_reported
        
        if _error_reported:
            return
        
        _pop_back_wdg = PopulateBackgroundWidgets(parent = self)
        _pop_back_wdg.run()
        
        _o_gui = Step2GuiHandler(parent = self)
        _o_gui.check_gui()

    def import_table_clicked(self):
	_o_table = TableHandler(parent = self)
	_o_table._import()
    
    def export_table_clicked(self):
	_o_table = TableHandler(parent = self)
	_o_table._export()

    def table_select_state_changed(self, state, row):
        _o_gui = Step2GuiHandler(parent = self)
        _o_gui.check_gui()
	_o_gui.define_new_ndabs_output_file_name()
	
	_o_table_handler = TableHandler(parent=self)
	_o_table_handler.check_selection_status(state, row)

    def check_step2_gui(self, row, column):
        _o_gui = Step2GuiHandler(parent = self)
        _o_gui.check_gui()
		
	_o_gui.step2_background_flag()
	_o_gui.step2_update_background_dropdown()

	if column == 1:
	    o_pop = PopulateBackgroundWidgets(parent=self)
	    o_pop.refresh_contain()

    # PDF
	
    def check_q_range(self):
        _o_gui = Step2GuiHandler(parent = self)
        _o_gui.check_gui()
            
    def hidrogen_clicked(self):
        o_gui = Step2GuiHandler(parent = self)
        o_gui.hidrogen_clicked()
    
    def no_hidrogen_clicked(self):
        o_gui = Step2GuiHandler(parent = self)
        o_gui.no_hidrogen_clicked()
    
    def yes_background_clicked(self):
        o_gui = Step2GuiHandler(parent = self)
        o_gui.yes_background_clicked()
    
    def no_background_clicked(self):
        o_gui = Step2GuiHandler(parent = self)
        o_gui.no_background_clicked()
        
    def background_combobox_changed(self, index):
        o_gui = Step2GuiHandler(parent = self)
        o_gui.background_index_changed(row_index = index)

    def reset_q_range(self):
        o_gui = Step2GuiHandler(parent = self)
        o_gui.reset_q_range()

    def run_ndabs_clicked(self):
        o_create_sample_files = CreateSampleFiles(parent = self)
        o_create_sample_files.run()
        
        list_sample_files = o_create_sample_files.list_sample_files
        
        o_create_ndsum_file = CreateNdsumFile(parent = self)
        o_create_ndsum_file.run()

        o_run_ndsum = RunNDabs(parent = self, list_sample_files = list_sample_files)
        o_run_ndsum.run()
        
    def check_fourier_filter_widgets(self):
        o_gui = Step2GuiHandler(parent = self)
        o_gui.check_gui()

    def check_plazcek_widgets(self):
        o_gui = Step2GuiHandler(parent = self)
        o_gui.check_gui()
        
    def table_right_click(self, position):
        _o_table = TableHandler(parent = self)
        _o_table.right_click(position = position)

    def run_sum_scans_clicked(self):
        o_run_sum_scans = RunSumScans(parent = self)
        o_run_sum_scans.run()

    def output_file_name_changed(self):
	o_gui = Step2GuiHandler(parent = self)
	o_gui.check_gui()

    def pdf_qmax_line_edit_changed(self):
	o_gui = Step2GuiHandler(parent = self)
	o_gui.check_gui()	

    def sum_scans_output_file_name_changed(self):
	o_gui = Step2GuiHandler(parent = self)
	o_gui.check_gui()	
	
    def help_button_clicked_ndabs(self):
	self.help_button_clicked(button_name = 'ndabs')
	
    def help_button_clicked_scans(self):
	self.help_button_clicked(button_name = 'scans')

    # Rietveld
    
    def mantid_browse_calibration_clicked(self):
	o_mantid_gui = BrowseFileFolderHandler(parent = self)
	o_mantid_gui.browse_file(type = 'calibration')
    
    def mantid_browse_characterization_clicked(self):
	o_mantid_gui = BrowseFileFolderHandler(parent = self)
	o_mantid_gui.browse_file(type = 'characterization')

    def mantid_output_directory_clicked(self):
	o_mantid_gui = BrowseFileFolderHandler(parent = self)
	o_mantid_gui.browse_folder()

    def mantid_run_reduction(self):
	o_mantid_run = GlobalMantidReduction(parent = self)
	o_mantid_run.run()

    def check_mantid_gui(self):
	o_gui = Step2GuiHandler(parent = self)
	o_gui.check_gui()

    def help_button_clicked_mantid(self):
	self.help_button_clicked(button_name = 'mantid')

def main():
    app = PyQt4.QtGui.QApplication(sys.argv)
    app.setOrganizationName("Qtrac Ltd.")
    app.setOrganizationDomain("qtrac.eu")
    app.setApplicationName("Image Changer")
    app.setWindowIcon(PyQt4.QtGui.QIcon(":/icon.png"))
    form = MainWindow()
    form.show()
    app.exec_()

if __name__ == '__main__':
    main()
