def run(main_window=None):
    main_window.postprocessing_ui_m.pushButton_loadWorkspaces.clicked.connect(main_window.open_and_load_workspaces)
    main_window.postprocessing_ui_m.pushButton_savemc.clicked.connect(main_window.save_mconfig)
    main_window.postprocessing_ui_m.pushButton_loadmc.clicked.connect(main_window.load_mconfig)
    main_window.postprocessing_ui_m.pushButton_savesc.clicked.connect(main_window.save_sconfig)
    main_window.postprocessing_ui_m.pushButton_loadsc.clicked.connect(main_window.load_sconfig)
    main_window.postprocessing_ui_m.pushButton_extract.clicked.connect(main_window.extract_button)
    main_window.postprocessing_ui_m.pushButton_clearPostProcessingCanvas.clicked.connect(main_window.clear_post_processing_canvas)
    main_window.postprocessing_ui_m.comboBox_banks.currentTextChanged.connect(main_window.change_bank)
    main_window.postprocessing_ui_m.doubleSpinBox_Qmin.valueChanged.connect(main_window.set_merge_values)
    main_window.postprocessing_ui_m.doubleSpinBox_Qmax.valueChanged.connect(main_window.set_merge_values)
    main_window.postprocessing_ui_m.lineEdit_Yoffset.textChanged.connect(main_window.set_merge_values)
    main_window.postprocessing_ui_m.lineEdit_Yscale.textChanged.connect(main_window.set_merge_values)
    main_window.postprocessing_ui_m.pushButton_mergeBanks.clicked.connect(main_window.merge_banks)
    main_window.postprocessing_ui_m.pushButton_StoG.clicked.connect(main_window.execute_stog)

    main_window.postprocessing_ui_m.lineEdit_Yoffset_stog.textChanged.connect(main_window.set_stog_values)
    main_window.postprocessing_ui_m.lineEdit_Yscale_stog.textChanged.connect(main_window.set_stog_values)
    main_window.postprocessing_ui_m.lineEdit_Qoffset.textChanged.connect(main_window.set_stog_values)
    main_window.postprocessing_ui_m.doubleSpinBox_Rmax.valueChanged.connect(main_window.set_stog_values)
    main_window.postprocessing_ui_m.doubleSpinBox_Rstep.valueChanged.connect(main_window.set_stog_values)
    main_window.postprocessing_ui_m.lineEdit_numberDensity.textChanged.connect(main_window.set_stog_values)
    main_window.postprocessing_ui_m.lineEdit_faberZiman.textChanged.connect(main_window.set_stog_values)
    main_window.postprocessing_ui_m.buttonGroup_FF.buttonClicked.connect(main_window.set_stog_values)
    main_window.postprocessing_ui_m.buttonGroup_Lorch.buttonClicked.connect(main_window.set_stog_values)
    main_window.postprocessing_ui_m.lineEdit_rippleParams.textChanged.connect(main_window.set_stog_values)
