# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/gui_fgr3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../d5o/useful_scripts/bg/me2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLoadSQ = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadSQ.setObjectName("btnLoadSQ")
        self.horizontalLayout.addWidget(self.btnLoadSQ)
        self.comboRecipType = QtWidgets.QComboBox(self.centralwidget)
        self.comboRecipType.setObjectName("comboRecipType")
        self.comboRecipType.addItem("")
        self.comboRecipType.addItem("")
        self.comboRecipType.addItem("")
        self.horizontalLayout.addWidget(self.comboRecipType)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelQmin = QtWidgets.QLabel(self.centralwidget)
        self.labelQmin.setObjectName("labelQmin")
        self.verticalLayout.addWidget(self.labelQmin)
        self.doubleSpinBoxQmin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxQmin.setMinimum(0.01)
        self.doubleSpinBoxQmin.setMaximum(10.0)
        self.doubleSpinBoxQmin.setSingleStep(0.01)
        self.doubleSpinBoxQmin.setObjectName("doubleSpinBoxQmin")
        self.verticalLayout.addWidget(self.doubleSpinBoxQmin)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelQmax = QtWidgets.QLabel(self.centralwidget)
        self.labelQmax.setObjectName("labelQmax")
        self.verticalLayout_2.addWidget(self.labelQmax)
        self.doubleSpinBoxQmax = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxQmax.setMinimum(1.0)
        self.doubleSpinBoxQmax.setMaximum(50.0)
        self.doubleSpinBoxQmax.setSingleStep(0.5)
        self.doubleSpinBoxQmax.setObjectName("doubleSpinBoxQmax")
        self.verticalLayout_2.addWidget(self.doubleSpinBoxQmax)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnGenerateGR = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerateGR.setObjectName("btnGenerateGR")
        self.horizontalLayout_2.addWidget(self.btnGenerateGR)
        self.btnSaveGR = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveGR.setObjectName("btnSaveGR")
        self.horizontalLayout_2.addWidget(self.btnSaveGR)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelRmin = QtWidgets.QLabel(self.centralwidget)
        self.labelRmin.setObjectName("labelRmin")
        self.verticalLayout_3.addWidget(self.labelRmin)
        self.doubleSpinBoxRmin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxRmin.setMinimum(0.1)
        self.doubleSpinBoxRmin.setMaximum(4.0)
        self.doubleSpinBoxRmin.setSingleStep(0.1)
        self.doubleSpinBoxRmin.setObjectName("doubleSpinBoxRmin")
        self.verticalLayout_3.addWidget(self.doubleSpinBoxRmin)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelRmax = QtWidgets.QLabel(self.centralwidget)
        self.labelRmax.setObjectName("labelRmax")
        self.verticalLayout_4.addWidget(self.labelRmax)
        self.doubleSpinBoxRmax = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxRmax.setMinimum(5.0)
        self.doubleSpinBoxRmax.setMaximum(100.0)
        self.doubleSpinBoxRmax.setProperty("value", 20.0)
        self.doubleSpinBoxRmax.setObjectName("doubleSpinBoxRmax")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxRmax)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labeldelR = QtWidgets.QLabel(self.centralwidget)
        self.labeldelR.setObjectName("labeldelR")
        self.verticalLayout_5.addWidget(self.labeldelR)
        self.doubleSpinBoxDelR = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxDelR.setMinimum(0.01)
        self.doubleSpinBoxDelR.setMaximum(1.0)
        self.doubleSpinBoxDelR.setSingleStep(0.01)
        self.doubleSpinBoxDelR.setProperty("value", 0.1)
        self.doubleSpinBoxDelR.setObjectName("doubleSpinBoxDelR")
        self.verticalLayout_5.addWidget(self.doubleSpinBoxDelR)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_6.addWidget(self.progressBar)
        self.top_plot = MPLWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_plot.sizePolicy().hasHeightForWidth())
        self.top_plot.setSizePolicy(sizePolicy)
        self.top_plot.setObjectName("top_plot")
        self.verticalLayout_6.addWidget(self.top_plot)
        self.bottom_plot = MPLWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom_plot.sizePolicy().hasHeightForWidth())
        self.bottom_plot.setSizePolicy(sizePolicy)
        self.bottom_plot.setObjectName("bottom_plot")
        self.verticalLayout_6.addWidget(self.bottom_plot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboRecipType.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FastGR"))
        self.btnLoadSQ.setText(_translate("MainWindow", "Load SQ"))
        self.comboRecipType.setItemText(0, _translate("MainWindow", "Plot S(Q)"))
        self.comboRecipType.setItemText(1, _translate("MainWindow", "Plot S(Q)-1"))
        self.comboRecipType.setItemText(2, _translate("MainWindow", "Plot Q[S(Q)-1]"))
        self.labelQmin.setText(_translate("MainWindow", "Qmin"))
        self.labelQmax.setText(_translate("MainWindow", "Qmax"))
        self.btnGenerateGR.setText(_translate("MainWindow", "Generate GR"))
        self.btnSaveGR.setText(_translate("MainWindow", "Save GR"))
        self.labelRmin.setText(_translate("MainWindow", "Rmin"))
        self.labelRmax.setText(_translate("MainWindow", "Rmax"))
        self.labeldelR.setText(_translate("MainWindow", "deltaR"))

from mplwidget import MPLWidget
import icons_rc
