# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/step2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.populate_table = QtWidgets.QPushButton(self.centralwidget)
        self.populate_table.setObjectName("populate_table")
        self.horizontalLayout.addWidget(self.populate_table)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.table.setAlternatingRowColors(True)
        self.table.setObjectName("table")
        self.table.setColumnCount(9)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.table)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.background_no = QtWidgets.QRadioButton(self.groupBox_3)
        self.background_no.setMinimumSize(QtCore.QSize(50, 0))
        self.background_no.setMaximumSize(QtCore.QSize(50, 16777215))
        self.background_no.setChecked(True)
        self.background_no.setObjectName("background_no")
        self.horizontalLayout_12.addWidget(self.background_no)
        self.background_no_field = QtWidgets.QLabel(self.groupBox_3)
        self.background_no_field.setMinimumSize(QtCore.QSize(300, 0))
        self.background_no_field.setObjectName("background_no_field")
        self.horizontalLayout_12.addWidget(self.background_no_field)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.background_yes = QtWidgets.QRadioButton(self.groupBox_3)
        self.background_yes.setObjectName("background_yes")
        self.horizontalLayout_10.addWidget(self.background_yes)
        self.background_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.background_comboBox.setEnabled(False)
        self.background_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.background_comboBox.setObjectName("background_comboBox")
        self.horizontalLayout_10.addWidget(self.background_comboBox)
        self.background_line_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.background_line_edit.setEnabled(False)
        self.background_line_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.background_line_edit.setObjectName("background_line_edit")
        self.horizontalLayout_10.addWidget(self.background_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fourier_filter_from = QtWidgets.QLineEdit(self.groupBox)
        self.fourier_filter_from.setObjectName("fourier_filter_from")
        self.horizontalLayout_8.addWidget(self.fourier_filter_from)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.fourier_filter_to = QtWidgets.QLineEdit(self.groupBox)
        self.fourier_filter_to.setObjectName("fourier_filter_to")
        self.horizontalLayout_8.addWidget(self.fourier_filter_to)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.horizontalLayout_9.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.hydrogen_yes = QtWidgets.QRadioButton(self.groupBox_7)
        self.hydrogen_yes.setChecked(False)
        self.hydrogen_yes.setObjectName("hydrogen_yes")
        self.horizontalLayout_2.addWidget(self.hydrogen_yes)
        self.hydrogen_no = QtWidgets.QRadioButton(self.groupBox_7)
        self.hydrogen_no.setChecked(True)
        self.hydrogen_no.setObjectName("hydrogen_no")
        self.horizontalLayout_2.addWidget(self.hydrogen_no)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.plazcek_fit_range_min = QtWidgets.QLineEdit(self.groupBox_7)
        self.plazcek_fit_range_min.setMinimumSize(QtCore.QSize(50, 0))
        self.plazcek_fit_range_min.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plazcek_fit_range_min.setObjectName("plazcek_fit_range_min")
        self.horizontalLayout_11.addWidget(self.plazcek_fit_range_min)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.plazcek_fit_range_max = QtWidgets.QLineEdit(self.groupBox_7)
        self.plazcek_fit_range_max.setMinimumSize(QtCore.QSize(50, 0))
        self.plazcek_fit_range_max.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plazcek_fit_range_max.setObjectName("plazcek_fit_range_max")
        self.horizontalLayout_11.addWidget(self.plazcek_fit_range_max)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addWidget(self.groupBox_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.muscat_yes = QtWidgets.QRadioButton(self.groupBox_4)
        self.muscat_yes.setObjectName("muscat_yes")
        self.horizontalLayout_3.addWidget(self.muscat_yes)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_12.setChecked(True)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_3.addWidget(self.radioButton_12)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scale_data_yes = QtWidgets.QRadioButton(self.groupBox_5)
        self.scale_data_yes.setChecked(True)
        self.scale_data_yes.setObjectName("scale_data_yes")
        self.horizontalLayout_4.addWidget(self.scale_data_yes)
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_14.setChecked(False)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_4.addWidget(self.radioButton_14)
        self.horizontalLayout_6.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.run_rmc_yes = QtWidgets.QRadioButton(self.groupBox_6)
        self.run_rmc_yes.setChecked(True)
        self.run_rmc_yes.setObjectName("run_rmc_yes")
        self.horizontalLayout_5.addWidget(self.run_rmc_yes)
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_16.setChecked(False)
        self.radioButton_16.setObjectName("radioButton_16")
        self.horizontalLayout_5.addWidget(self.radioButton_16)
        self.horizontalLayout_6.addWidget(self.groupBox_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_21.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_7.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_7.addWidget(self.label_22)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.create_sample_properties_files_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_sample_properties_files_button.setEnabled(False)
        self.create_sample_properties_files_button.setObjectName("create_sample_properties_files_button")
        self.horizontalLayout_7.addWidget(self.create_sample_properties_files_button)
        self.run_ndabs_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_ndabs_button.setEnabled(False)
        self.run_ndabs_button.setObjectName("run_ndabs_button")
        self.horizontalLayout_7.addWidget(self.run_ndabs_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.populate_table.clicked.connect(MainWindow.populate_table_clicked)
        self.hydrogen_yes.clicked.connect(MainWindow.hidrogen_clicked)
        self.hydrogen_no.clicked.connect(MainWindow.no_hidrogen_clicked)
        self.background_yes.clicked.connect(MainWindow.yes_background_clicked)
        self.background_comboBox.currentIndexChanged['int'].connect(MainWindow.background_combobox_changed)
        self.create_sample_properties_files_button.clicked.connect(MainWindow.create_sample_properties_files_clicked)
        self.run_ndabs_button.clicked.connect(MainWindow.run_ndabs_clicked)
        self.fourier_filter_from.editingFinished.connect(MainWindow.check_fourier_filter_widgets)
        self.fourier_filter_to.editingFinished.connect(MainWindow.check_fourier_filter_widgets)
        self.plazcek_fit_range_min.editingFinished.connect(MainWindow.check_plazcek_widgets)
        self.plazcek_fit_range_max.editingFinished.connect(MainWindow.check_plazcek_widgets)
        self.table.customContextMenuRequested['QPoint'].connect(MainWindow.table_right_click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.populate_table.setText(_translate("MainWindow", "Populate Table"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Select"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Runs"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sample Formula"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mass Density (g/cc)"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Radius (cm)"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Packing Fraction"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sample Shape"))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Do Abs. Corr. ?"))
        self.label_3.setText(_translate("MainWindow", "Sample formula example: H 2 O 1, 2H 2 O 1, 238U 1 O 2"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Background"))
        self.background_no.setText(_translate("MainWindow", "No"))
        self.background_no_field.setText(_translate("MainWindow", "N/A"))
        self.label_7.setText(_translate("MainWindow", "(from exp.ini file)"))
        self.background_yes.setText(_translate("MainWindow", "Yes"))
        self.groupBox.setTitle(_translate("MainWindow", "Fourier Filter (ex: 1.5, 50)"))
        self.fourier_filter_from.setText(_translate("MainWindow", "1.5"))
        self.label_8.setText(_translate("MainWindow", "*"))
        self.label_2.setText(_translate("MainWindow", ","))
        self.fourier_filter_to.setText(_translate("MainWindow", "50"))
        self.label_6.setText(_translate("MainWindow", "*"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Plazcek"))
        self.label.setText(_translate("MainWindow", "Type"))
        self.hydrogen_yes.setText(_translate("MainWindow", "hydrogen"))
        self.hydrogen_no.setText(_translate("MainWindow", "no hydrogren"))
        self.label_4.setText(_translate("MainWindow", "Fit Range"))
        self.plazcek_fit_range_min.setText(_translate("MainWindow", "10"))
        self.label_9.setText(_translate("MainWindow", "*"))
        self.label_5.setText(_translate("MainWindow", ","))
        self.plazcek_fit_range_max.setText(_translate("MainWindow", "50"))
        self.label_10.setText(_translate("MainWindow", "*"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Muscat"))
        self.muscat_yes.setText(_translate("MainWindow", "Yes"))
        self.radioButton_12.setText(_translate("MainWindow", "No"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Scale Data"))
        self.scale_data_yes.setText(_translate("MainWindow", "Yes"))
        self.radioButton_14.setText(_translate("MainWindow", "No"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Run RMC"))
        self.run_rmc_yes.setText(_translate("MainWindow", "Yes"))
        self.radioButton_16.setText(_translate("MainWindow", "No"))
        self.label_21.setText(_translate("MainWindow", "*"))
        self.label_22.setText(_translate("MainWindow", ": Mandatory field"))
        self.create_sample_properties_files_button.setText(_translate("MainWindow", "Create Sample Properties Files"))
        self.run_ndabs_button.setText(_translate("MainWindow", "Run NDabs"))

