# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/step1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1102, 572)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.diamond_background = QtGui.QLineEdit(self.groupBox_5)
        self.diamond_background.setToolTip(_fromUtf8(""))
        self.diamond_background.setStatusTip(_fromUtf8(""))
        self.diamond_background.setAccessibleDescription(_fromUtf8(""))
        self.diamond_background.setInputMask(_fromUtf8(""))
        self.diamond_background.setPlaceholderText(_fromUtf8(""))
        self.diamond_background.setObjectName(_fromUtf8("diamond_background"))
        self.gridLayout.addWidget(self.diamond_background, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sample_background = QtGui.QLineEdit(self.groupBox_5)
        self.sample_background.setToolTip(_fromUtf8(""))
        self.sample_background.setStatusTip(_fromUtf8(""))
        self.sample_background.setAccessibleDescription(_fromUtf8(""))
        self.sample_background.setInputMask(_fromUtf8(""))
        self.sample_background.setPlaceholderText(_fromUtf8(""))
        self.sample_background.setObjectName(_fromUtf8("sample_background"))
        self.gridLayout.addWidget(self.sample_background, 4, 1, 1, 1)
        self.vanadium = QtGui.QLineEdit(self.groupBox_5)
        self.vanadium.setToolTip(_fromUtf8(""))
        self.vanadium.setStatusTip(_fromUtf8(""))
        self.vanadium.setAccessibleDescription(_fromUtf8(""))
        self.vanadium.setInputMask(_fromUtf8(""))
        self.vanadium.setPlaceholderText(_fromUtf8(""))
        self.vanadium.setObjectName(_fromUtf8("vanadium"))
        self.gridLayout.addWidget(self.vanadium, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.vanadium_background = QtGui.QLineEdit(self.groupBox_5)
        self.vanadium_background.setToolTip(_fromUtf8(""))
        self.vanadium_background.setStatusTip(_fromUtf8(""))
        self.vanadium_background.setAccessibleDescription(_fromUtf8(""))
        self.vanadium_background.setInputMask(_fromUtf8(""))
        self.vanadium_background.setPlaceholderText(_fromUtf8(""))
        self.vanadium_background.setObjectName(_fromUtf8("vanadium_background"))
        self.gridLayout.addWidget(self.vanadium_background, 3, 1, 1, 1)
        self.diamond = QtGui.QLineEdit(self.groupBox_5)
        self.diamond.setToolTip(_fromUtf8(""))
        self.diamond.setStatusTip(_fromUtf8(""))
        self.diamond.setAccessibleDescription(_fromUtf8(""))
        self.diamond.setInputMask(_fromUtf8(""))
        self.diamond.setPlaceholderText(_fromUtf8(""))
        self.diamond.setObjectName(_fromUtf8("diamond"))
        self.gridLayout.addWidget(self.diamond, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_21.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_5.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_5.addWidget(self.label_22)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.last_scan = QtGui.QLineEdit(self.centralwidget)
        self.last_scan.setObjectName(_fromUtf8("last_scan"))
        self.gridLayout_3.addWidget(self.last_scan, 1, 1, 1, 1)
        self.first_scan = QtGui.QLineEdit(self.centralwidget)
        self.first_scan.setObjectName(_fromUtf8("first_scan"))
        self.gridLayout_3.addWidget(self.first_scan, 0, 1, 1, 1)
        self.frequency = QtGui.QComboBox(self.centralwidget)
        self.frequency.setObjectName(_fromUtf8("frequency"))
        self.frequency.addItem(_fromUtf8(""))
        self.frequency.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.frequency, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.recalibration_yes = QtGui.QRadioButton(self.groupBox_2)
        self.recalibration_yes.setObjectName(_fromUtf8("recalibration_yes"))
        self.horizontalLayout.addWidget(self.recalibration_yes)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.renormalization_yes = QtGui.QRadioButton(self.groupBox_3)
        self.renormalization_yes.setObjectName(_fromUtf8("renormalization_yes"))
        self.horizontalLayout_2.addWidget(self.renormalization_yes)
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.horizontalLayout_2.addWidget(self.radioButton_10)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.autotemplate_yes = QtGui.QRadioButton(self.groupBox_4)
        self.autotemplate_yes.setChecked(True)
        self.autotemplate_yes.setObjectName(_fromUtf8("autotemplate_yes"))
        self.horizontalLayout_3.addWidget(self.autotemplate_yes)
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_12.setChecked(False)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.horizontalLayout_3.addWidget(self.radioButton_12)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_10.addWidget(self.label_12)
        self.comments = QtGui.QLineEdit(self.centralwidget)
        self.comments.setObjectName(_fromUtf8("comments"))
        self.horizontalLayout_10.addWidget(self.comments)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.auto_manual_folder = QtGui.QRadioButton(self.groupBox)
        self.auto_manual_folder.setChecked(True)
        self.auto_manual_folder.setObjectName(_fromUtf8("auto_manual_folder"))
        self.verticalLayout_4.addWidget(self.auto_manual_folder)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.manual_output_folder = QtGui.QRadioButton(self.groupBox)
        self.manual_output_folder.setObjectName(_fromUtf8("manual_output_folder"))
        self.horizontalLayout_8.addWidget(self.manual_output_folder)
        self.manual_output_folder_field = QtGui.QLineEdit(self.groupBox)
        self.manual_output_folder_field.setEnabled(False)
        self.manual_output_folder_field.setObjectName(_fromUtf8("manual_output_folder_field"))
        self.horizontalLayout_8.addWidget(self.manual_output_folder_field)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.run_autonom_script = QtGui.QPushButton(self.centralwidget)
        self.run_autonom_script.setEnabled(False)
        self.run_autonom_script.setObjectName(_fromUtf8("run_autonom_script"))
        self.verticalLayout_3.addWidget(self.run_autonom_script)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.diamond, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.diamond_edited)
        QtCore.QObject.connect(self.diamond_background, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.diamond_background_edited)
        QtCore.QObject.connect(self.vanadium, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.vanadium_edited)
        QtCore.QObject.connect(self.vanadium_background, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.vanadium_background_edited)
        QtCore.QObject.connect(self.sample_background, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.sample_background_edited)
        QtCore.QObject.connect(self.auto_manual_folder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.output_folder_radio_buttons)
        QtCore.QObject.connect(self.manual_output_folder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.output_folder_radio_buttons)
        QtCore.QObject.connect(self.manual_output_folder_field, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.manual_output_folder_field_edited)
        QtCore.QObject.connect(self.run_autonom_script, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.run_autonom)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.diamond, self.diamond_background)
        MainWindow.setTabOrder(self.diamond_background, self.vanadium)
        MainWindow.setTabOrder(self.vanadium, self.vanadium_background)
        MainWindow.setTabOrder(self.vanadium_background, self.sample_background)
        MainWindow.setTabOrder(self.sample_background, self.first_scan)
        MainWindow.setTabOrder(self.first_scan, self.last_scan)
        MainWindow.setTabOrder(self.last_scan, self.frequency)
        MainWindow.setTabOrder(self.frequency, self.recalibration_yes)
        MainWindow.setTabOrder(self.recalibration_yes, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.renormalization_yes)
        MainWindow.setTabOrder(self.renormalization_yes, self.radioButton_10)
        MainWindow.setTabOrder(self.radioButton_10, self.autotemplate_yes)
        MainWindow.setTabOrder(self.autotemplate_yes, self.radioButton_12)
        MainWindow.setTabOrder(self.radioButton_12, self.run_autonom_script)
        MainWindow.setTabOrder(self.run_autonom_script, self.auto_manual_folder)
        MainWindow.setTabOrder(self.auto_manual_folder, self.manual_output_folder)
        MainWindow.setTabOrder(self.manual_output_folder, self.manual_output_folder_field)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Scan Numbers  (ex: 1234, 1300-1305, 1310)", None))
        self.label_8.setText(_translate("MainWindow", "*", None))
        self.label_7.setText(_translate("MainWindow", "Vanadium background", None))
        self.diamond_background.setText(_translate("MainWindow", "65456", None))
        self.label.setText(_translate("MainWindow", "Diamond", None))
        self.sample_background.setText(_translate("MainWindow", "65472", None))
        self.vanadium.setText(_translate("MainWindow", "65458", None))
        self.label_5.setText(_translate("MainWindow", "Vanadium", None))
        self.label_4.setText(_translate("MainWindow", "*", None))
        self.label_2.setText(_translate("MainWindow", "*", None))
        self.label_6.setText(_translate("MainWindow", "*", None))
        self.label_10.setText(_translate("MainWindow", "*", None))
        self.label_3.setText(_translate("MainWindow", "Diamond background", None))
        self.label_9.setText(_translate("MainWindow", "Sample background", None))
        self.vanadium_background.setText(_translate("MainWindow", "65470", None))
        self.diamond.setText(_translate("MainWindow", "65454", None))
        self.label_21.setText(_translate("MainWindow", "*", None))
        self.label_22.setText(_translate("MainWindow", ": Mandatory field", None))
        self.label_18.setText(_translate("MainWindow", "First scan to be analyzed", None))
        self.label_20.setText(_translate("MainWindow", "Frequency (Hz)", None))
        self.label_19.setText(_translate("MainWindow", "Last scan to be analyzed", None))
        self.last_scan.setText(_translate("MainWindow", "65452", None))
        self.first_scan.setText(_translate("MainWindow", "65450", None))
        self.frequency.setItemText(0, _translate("MainWindow", "60", None))
        self.frequency.setItemText(1, _translate("MainWindow", "30", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Recalibration", None))
        self.recalibration_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_2.setText(_translate("MainWindow", "No", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Renormalization", None))
        self.renormalization_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_10.setText(_translate("MainWindow", "No", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Autotemplate", None))
        self.autotemplate_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_12.setText(_translate("MainWindow", "No", None))
        self.label_12.setText(_translate("MainWindow", "Comments:", None))
        self.groupBox.setTitle(_translate("MainWindow", "Name of Output Folder", None))
        self.auto_manual_folder.setText(_translate("MainWindow", "Automatic (autoNOM_##)", None))
        self.manual_output_folder.setText(_translate("MainWindow", "Manual", None))
        self.run_autonom_script.setText(_translate("MainWindow", "Run autoNOM script", None))

