# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_editSq.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(859, 298)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_workspaces = QtWidgets.QComboBox(Dialog)
        self.comboBox_workspaces.setObjectName("comboBox_workspaces")
        self.comboBox_workspaces.addItem("")
        self.comboBox_workspaces.addItem("")
        self.verticalLayout.addWidget(self.comboBox_workspaces)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_shift = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_shift.sizePolicy().hasHeightForWidth())
        self.lineEdit_shift.setSizePolicy(sizePolicy)
        self.lineEdit_shift.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_shift.setObjectName("lineEdit_shift")
        self.gridLayout.addWidget(self.lineEdit_shift, 0, 1, 1, 1)
        self.lineEdit_scaleFactor = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_scaleFactor.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_scaleFactor.setObjectName("lineEdit_scaleFactor")
        self.gridLayout.addWidget(self.lineEdit_scaleFactor, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSlider_shift = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_shift.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_shift.setObjectName("horizontalSlider_shift")
        self.horizontalLayout.addWidget(self.horizontalSlider_shift)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_scale = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_scale.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_scale.setObjectName("horizontalSlider_scale")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_scale)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_editSQ = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_editSQ.setFont(font)
        self.pushButton_editSQ.setObjectName("pushButton_editSQ")
        self.gridLayout.addWidget(self.pushButton_editSQ, 0, 2, 1, 1)
        self.pushButton_cache = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cache.setFont(font)
        self.pushButton_cache.setObjectName("pushButton_cache")
        self.gridLayout.addWidget(self.pushButton_cache, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_shiftMin = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_shiftMin.sizePolicy().hasHeightForWidth())
        self.lineEdit_shiftMin.setSizePolicy(sizePolicy)
        self.lineEdit_shiftMin.setMaximumSize(QtCore.QSize(80, 80))
        self.lineEdit_shiftMin.setObjectName("lineEdit_shiftMin")
        self.gridLayout_2.addWidget(self.lineEdit_shiftMin, 0, 1, 1, 1)
        self.lineEdit_shiftMax = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_shiftMax.sizePolicy().hasHeightForWidth())
        self.lineEdit_shiftMax.setSizePolicy(sizePolicy)
        self.lineEdit_shiftMax.setMaximumSize(QtCore.QSize(80, 80))
        self.lineEdit_shiftMax.setObjectName("lineEdit_shiftMax")
        self.gridLayout_2.addWidget(self.lineEdit_shiftMax, 0, 2, 1, 1)
        self.pushButton_setShiftRange = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_setShiftRange.setObjectName("pushButton_setShiftRange")
        self.gridLayout_2.addWidget(self.pushButton_setShiftRange, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.lineEdit_scaleMin = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_scaleMin.sizePolicy().hasHeightForWidth())
        self.lineEdit_scaleMin.setSizePolicy(sizePolicy)
        self.lineEdit_scaleMin.setMaximumSize(QtCore.QSize(80, 80))
        self.lineEdit_scaleMin.setObjectName("lineEdit_scaleMin")
        self.gridLayout_2.addWidget(self.lineEdit_scaleMin, 1, 1, 1, 1)
        self.lineEdit_scaleMax = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_scaleMax.sizePolicy().hasHeightForWidth())
        self.lineEdit_scaleMax.setSizePolicy(sizePolicy)
        self.lineEdit_scaleMax.setMaximumSize(QtCore.QSize(80, 80))
        self.lineEdit_scaleMax.setObjectName("lineEdit_scaleMax")
        self.gridLayout_2.addWidget(self.lineEdit_scaleMax, 1, 2, 1, 1)
        self.pushButton_setScaleRange = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_setScaleRange.setObjectName("pushButton_setScaleRange")
        self.gridLayout_2.addWidget(self.pushButton_setScaleRange, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_saveNewSq = QtWidgets.QPushButton(Dialog)
        self.pushButton_saveNewSq.setObjectName("pushButton_saveNewSq")
        self.horizontalLayout_3.addWidget(self.pushButton_saveNewSq)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_quit = QtWidgets.QPushButton(Dialog)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout_3.addWidget(self.pushButton_quit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox_workspaces.setItemText(0, _translate("Dialog", "workspace 1"))
        self.comboBox_workspaces.setItemText(1, _translate("Dialog", "workspace 2"))
        self.groupBox.setTitle(_translate("Dialog", "Edit S(Q)"))
        self.lineEdit_shift.setText(_translate("Dialog", "0"))
        self.lineEdit_scaleFactor.setText(_translate("Dialog", "1"))
        self.label_2.setText(_translate("Dialog", "Scale"))
        self.label.setText(_translate("Dialog", "Shift"))
        self.pushButton_editSQ.setText(_translate("Dialog", "Edit S(Q)"))
        self.pushButton_cache.setToolTip(_translate("Dialog", "<html><head/><body><p>Cache the edited S(Q)</p></body></html>"))
        self.pushButton_cache.setText(_translate("Dialog", "Cache Edited"))
        self.groupBox_2.setTitle(_translate("Dialog", "Setup"))
        self.label_3.setText(_translate("Dialog", "Shift Range"))
        self.label_4.setText(_translate("Dialog", "Scale Range"))
        self.pushButton_setShiftRange.setText(_translate("Dialog", "Set Range"))
        self.pushButton_setScaleRange.setText(_translate("Dialog", "Set Range"))
        self.pushButton_saveNewSq.setText(_translate("Dialog", "Save As"))
        self.pushButton_quit.setText(_translate("Dialog", "Quit"))

