# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_mainWindow_no_scroll_bars.ui'
#
# Created: Tue May  2 09:12:39 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1038, 778)
        MainWindow.setMinimumSize(QtCore.QSize(500, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.diamond_background = QtGui.QLineEdit(self.groupBox_5)
        self.diamond_background.setToolTip(_fromUtf8(""))
        self.diamond_background.setStatusTip(_fromUtf8(""))
        self.diamond_background.setAccessibleDescription(_fromUtf8(""))
        self.diamond_background.setInputMask(_fromUtf8(""))
        self.diamond_background.setText(_fromUtf8(""))
        self.diamond_background.setPlaceholderText(_fromUtf8(""))
        self.diamond_background.setObjectName(_fromUtf8("diamond_background"))
        self.gridLayout.addWidget(self.diamond_background, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sample_background = QtGui.QLineEdit(self.groupBox_5)
        self.sample_background.setToolTip(_fromUtf8(""))
        self.sample_background.setStatusTip(_fromUtf8(""))
        self.sample_background.setAccessibleDescription(_fromUtf8(""))
        self.sample_background.setInputMask(_fromUtf8(""))
        self.sample_background.setText(_fromUtf8(""))
        self.sample_background.setPlaceholderText(_fromUtf8(""))
        self.sample_background.setObjectName(_fromUtf8("sample_background"))
        self.gridLayout.addWidget(self.sample_background, 4, 1, 1, 1)
        self.vanadium = QtGui.QLineEdit(self.groupBox_5)
        self.vanadium.setToolTip(_fromUtf8(""))
        self.vanadium.setStatusTip(_fromUtf8(""))
        self.vanadium.setAccessibleDescription(_fromUtf8(""))
        self.vanadium.setInputMask(_fromUtf8(""))
        self.vanadium.setText(_fromUtf8(""))
        self.vanadium.setPlaceholderText(_fromUtf8(""))
        self.vanadium.setObjectName(_fromUtf8("vanadium"))
        self.gridLayout.addWidget(self.vanadium, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.vanadium_background = QtGui.QLineEdit(self.groupBox_5)
        self.vanadium_background.setToolTip(_fromUtf8(""))
        self.vanadium_background.setStatusTip(_fromUtf8(""))
        self.vanadium_background.setAccessibleDescription(_fromUtf8(""))
        self.vanadium_background.setInputMask(_fromUtf8(""))
        self.vanadium_background.setText(_fromUtf8(""))
        self.vanadium_background.setPlaceholderText(_fromUtf8(""))
        self.vanadium_background.setObjectName(_fromUtf8("vanadium_background"))
        self.gridLayout.addWidget(self.vanadium_background, 3, 1, 1, 1)
        self.diamond = QtGui.QLineEdit(self.groupBox_5)
        self.diamond.setToolTip(_fromUtf8(""))
        self.diamond.setStatusTip(_fromUtf8(""))
        self.diamond.setAccessibleDescription(_fromUtf8(""))
        self.diamond.setInputMask(_fromUtf8(""))
        self.diamond.setText(_fromUtf8(""))
        self.diamond.setPlaceholderText(_fromUtf8(""))
        self.diamond.setObjectName(_fromUtf8("diamond"))
        self.gridLayout.addWidget(self.diamond, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_21.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_5.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_5.addWidget(self.label_22)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_14.addWidget(self.groupBox_5)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_14.addWidget(self.line)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_6.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_6.addWidget(self.label_19, 1, 0, 1, 1)
        self.last_scan = QtGui.QLineEdit(self.tab)
        self.last_scan.setText(_fromUtf8(""))
        self.last_scan.setObjectName(_fromUtf8("last_scan"))
        self.gridLayout_6.addWidget(self.last_scan, 1, 1, 1, 1)
        self.first_scan = QtGui.QLineEdit(self.tab)
        self.first_scan.setText(_fromUtf8(""))
        self.first_scan.setObjectName(_fromUtf8("first_scan"))
        self.gridLayout_6.addWidget(self.first_scan, 0, 1, 1, 1)
        self.frequency = QtGui.QComboBox(self.tab)
        self.frequency.setObjectName(_fromUtf8("frequency"))
        self.frequency.addItem(_fromUtf8(""))
        self.frequency.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.frequency, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.recalibration_yes = QtGui.QRadioButton(self.groupBox_6)
        self.recalibration_yes.setObjectName(_fromUtf8("recalibration_yes"))
        self.horizontalLayout_14.addWidget(self.recalibration_yes)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.horizontalLayout_14.addWidget(self.radioButton_3)
        self.horizontalLayout_13.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.renormalization_yes = QtGui.QRadioButton(self.groupBox_7)
        self.renormalization_yes.setObjectName(_fromUtf8("renormalization_yes"))
        self.horizontalLayout_15.addWidget(self.renormalization_yes)
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_11.setChecked(True)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.horizontalLayout_15.addWidget(self.radioButton_11)
        self.horizontalLayout_13.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.autotemplate_yes = QtGui.QRadioButton(self.groupBox_8)
        self.autotemplate_yes.setChecked(True)
        self.autotemplate_yes.setObjectName(_fromUtf8("autotemplate_yes"))
        self.horizontalLayout_16.addWidget(self.autotemplate_yes)
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_13.setChecked(False)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.horizontalLayout_16.addWidget(self.radioButton_13)
        self.horizontalLayout_13.addWidget(self.groupBox_8)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_19.addWidget(self.label_14)
        self.comments = QtGui.QLineEdit(self.tab)
        self.comments.setObjectName(_fromUtf8("comments"))
        self.horizontalLayout_19.addWidget(self.comments)
        self.verticalLayout_14.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.groupBox_9 = QtGui.QGroupBox(self.tab)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.auto_manual_folder = QtGui.QRadioButton(self.groupBox_9)
        self.auto_manual_folder.setChecked(True)
        self.auto_manual_folder.setObjectName(_fromUtf8("auto_manual_folder"))
        self.verticalLayout_12.addWidget(self.auto_manual_folder)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.manual_output_folder = QtGui.QRadioButton(self.groupBox_9)
        self.manual_output_folder.setObjectName(_fromUtf8("manual_output_folder"))
        self.horizontalLayout_18.addWidget(self.manual_output_folder)
        self.manual_output_folder_field = QtGui.QLineEdit(self.groupBox_9)
        self.manual_output_folder_field.setEnabled(False)
        self.manual_output_folder_field.setObjectName(_fromUtf8("manual_output_folder_field"))
        self.horizontalLayout_18.addWidget(self.manual_output_folder_field)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.verticalLayout_11.addWidget(self.groupBox_9)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem4)
        self.run_autonom_script = QtGui.QPushButton(self.tab)
        self.run_autonom_script.setEnabled(False)
        self.run_autonom_script.setObjectName(_fromUtf8("run_autonom_script"))
        self.verticalLayout_13.addWidget(self.run_autonom_script)
        self.horizontalLayout_17.addLayout(self.verticalLayout_13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.move_to_button = QtGui.QPushButton(self.tab_2)
        self.move_to_button.setMaximumSize(QtCore.QSize(130, 16777215))
        self.move_to_button.setObjectName(_fromUtf8("move_to_button"))
        self.horizontalLayout_20.addWidget(self.move_to_button)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_20.addWidget(self.label_13)
        self.current_folder_label = QtGui.QLabel(self.tab_2)
        self.current_folder_label.setObjectName(_fromUtf8("current_folder_label"))
        self.horizontalLayout_20.addWidget(self.current_folder_label)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.populate_table = QtGui.QPushButton(self.tab_2)
        self.populate_table.setObjectName(_fromUtf8("populate_table"))
        self.verticalLayout_17.addWidget(self.populate_table)
        self.table = QtGui.QTableWidget(self.tab_2)
        self.table.setMinimumSize(QtCore.QSize(50, 0))
        self.table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.table.setAlternatingRowColors(True)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(9)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_17.addWidget(self.table)
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_17.addWidget(self.label_29)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.background_no = QtGui.QRadioButton(self.groupBox_10)
        self.background_no.setMinimumSize(QtCore.QSize(50, 0))
        self.background_no.setMaximumSize(QtCore.QSize(50, 16777215))
        self.background_no.setChecked(True)
        self.background_no.setObjectName(_fromUtf8("background_no"))
        self.horizontalLayout_22.addWidget(self.background_no)
        self.background_no_field = QtGui.QLabel(self.groupBox_10)
        self.background_no_field.setMinimumSize(QtCore.QSize(300, 0))
        self.background_no_field.setObjectName(_fromUtf8("background_no_field"))
        self.horizontalLayout_22.addWidget(self.background_no_field)
        self.label_15 = QtGui.QLabel(self.groupBox_10)
        self.label_15.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_22.addWidget(self.label_15)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.background_yes = QtGui.QRadioButton(self.groupBox_10)
        self.background_yes.setObjectName(_fromUtf8("background_yes"))
        self.horizontalLayout_23.addWidget(self.background_yes)
        self.background_comboBox = QtGui.QComboBox(self.groupBox_10)
        self.background_comboBox.setEnabled(False)
        self.background_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.background_comboBox.setObjectName(_fromUtf8("background_comboBox"))
        self.horizontalLayout_23.addWidget(self.background_comboBox)
        self.background_line_edit = QtGui.QLineEdit(self.groupBox_10)
        self.background_line_edit.setEnabled(False)
        self.background_line_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.background_line_edit.setObjectName(_fromUtf8("background_line_edit"))
        self.horizontalLayout_23.addWidget(self.background_line_edit)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_21.addWidget(self.groupBox_10)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.fourier_filter_from = QtGui.QLineEdit(self.groupBox_11)
        self.fourier_filter_from.setObjectName(_fromUtf8("fourier_filter_from"))
        self.horizontalLayout_24.addWidget(self.fourier_filter_from)
        self.label_16 = QtGui.QLabel(self.groupBox_11)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_16.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_24.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.groupBox_11)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_24.addWidget(self.label_17)
        self.fourier_filter_to = QtGui.QLineEdit(self.groupBox_11)
        self.fourier_filter_to.setObjectName(_fromUtf8("fourier_filter_to"))
        self.horizontalLayout_24.addWidget(self.fourier_filter_to)
        self.label_23 = QtGui.QLabel(self.groupBox_11)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_23.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_24.addWidget(self.label_23)
        self.horizontalLayout_21.addWidget(self.groupBox_11)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_24 = QtGui.QLabel(self.groupBox_12)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_25.addWidget(self.label_24)
        self.hydrogen_yes = QtGui.QRadioButton(self.groupBox_12)
        self.hydrogen_yes.setChecked(False)
        self.hydrogen_yes.setObjectName(_fromUtf8("hydrogen_yes"))
        self.horizontalLayout_25.addWidget(self.hydrogen_yes)
        self.hydrogen_no = QtGui.QRadioButton(self.groupBox_12)
        self.hydrogen_no.setChecked(True)
        self.hydrogen_no.setObjectName(_fromUtf8("hydrogen_no"))
        self.horizontalLayout_25.addWidget(self.hydrogen_no)
        self.verticalLayout_16.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_25 = QtGui.QLabel(self.groupBox_12)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_26.addWidget(self.label_25)
        self.plazcek_fit_range_min = QtGui.QLineEdit(self.groupBox_12)
        self.plazcek_fit_range_min.setMinimumSize(QtCore.QSize(50, 0))
        self.plazcek_fit_range_min.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plazcek_fit_range_min.setObjectName(_fromUtf8("plazcek_fit_range_min"))
        self.horizontalLayout_26.addWidget(self.plazcek_fit_range_min)
        self.label_26 = QtGui.QLabel(self.groupBox_12)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_26.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_26.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(self.groupBox_12)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_26.addWidget(self.label_27)
        self.plazcek_fit_range_max = QtGui.QLineEdit(self.groupBox_12)
        self.plazcek_fit_range_max.setMinimumSize(QtCore.QSize(50, 0))
        self.plazcek_fit_range_max.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plazcek_fit_range_max.setObjectName(_fromUtf8("plazcek_fit_range_max"))
        self.horizontalLayout_26.addWidget(self.plazcek_fit_range_max)
        self.label_28 = QtGui.QLabel(self.groupBox_12)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_28.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_26.addWidget(self.label_28)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem5)
        self.verticalLayout_16.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_21.addWidget(self.groupBox_12)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_13.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.muscat_yes = QtGui.QRadioButton(self.groupBox_13)
        self.muscat_yes.setObjectName(_fromUtf8("muscat_yes"))
        self.horizontalLayout_28.addWidget(self.muscat_yes)
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox_13)
        self.radioButton_14.setChecked(True)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.horizontalLayout_28.addWidget(self.radioButton_14)
        self.horizontalLayout_27.addWidget(self.groupBox_13)
        self.groupBox_14 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_14.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.scale_data_yes = QtGui.QRadioButton(self.groupBox_14)
        self.scale_data_yes.setChecked(True)
        self.scale_data_yes.setObjectName(_fromUtf8("scale_data_yes"))
        self.horizontalLayout_29.addWidget(self.scale_data_yes)
        self.radioButton_15 = QtGui.QRadioButton(self.groupBox_14)
        self.radioButton_15.setChecked(False)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.horizontalLayout_29.addWidget(self.radioButton_15)
        self.horizontalLayout_27.addWidget(self.groupBox_14)
        self.groupBox_15 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_15.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.run_rmc_yes = QtGui.QRadioButton(self.groupBox_15)
        self.run_rmc_yes.setChecked(True)
        self.run_rmc_yes.setObjectName(_fromUtf8("run_rmc_yes"))
        self.horizontalLayout_30.addWidget(self.run_rmc_yes)
        self.radioButton_16 = QtGui.QRadioButton(self.groupBox_15)
        self.radioButton_16.setChecked(False)
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.horizontalLayout_30.addWidget(self.radioButton_16)
        self.horizontalLayout_27.addWidget(self.groupBox_15)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem6)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_27)
        self.verticalLayout_17.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_30 = QtGui.QLabel(self.tab_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_30.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_31.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.tab_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_31.addWidget(self.label_31)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem7)
        self.create_sample_properties_files_button = QtGui.QPushButton(self.tab_2)
        self.create_sample_properties_files_button.setEnabled(False)
        self.create_sample_properties_files_button.setObjectName(_fromUtf8("create_sample_properties_files_button"))
        self.horizontalLayout_31.addWidget(self.create_sample_properties_files_button)
        self.run_ndabs_button = QtGui.QPushButton(self.tab_2)
        self.run_ndabs_button.setEnabled(False)
        self.run_ndabs_button.setObjectName(_fromUtf8("run_ndabs_button"))
        self.horizontalLayout_31.addWidget(self.run_ndabs_button)
        self.verticalLayout_17.addLayout(self.horizontalLayout_31)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_bragg = QtGui.QWidget()
        self.tab_bragg.setObjectName(_fromUtf8("tab_bragg"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_bragg)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.tab_bragg)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.graphicsView_bragg = BraggView(self.tab_bragg)
        self.graphicsView_bragg.setObjectName(_fromUtf8("graphicsView_bragg"))
        self.verticalLayout_5.addWidget(self.graphicsView_bragg)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comboBox_xUnit = QtGui.QComboBox(self.tab_bragg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_xUnit.sizePolicy().hasHeightForWidth())
        self.comboBox_xUnit.setSizePolicy(sizePolicy)
        self.comboBox_xUnit.setObjectName(_fromUtf8("comboBox_xUnit"))
        self.comboBox_xUnit.addItem(_fromUtf8(""))
        self.comboBox_xUnit.addItem(_fromUtf8(""))
        self.comboBox_xUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_xUnit)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.pushButton_combineBanks = QtGui.QPushButton(self.tab_bragg)
        self.pushButton_combineBanks.setObjectName(_fromUtf8("pushButton_combineBanks"))
        self.horizontalLayout_3.addWidget(self.pushButton_combineBanks)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_loadBraggFile = QtGui.QPushButton(self.tab_bragg)
        self.pushButton_loadBraggFile.setObjectName(_fromUtf8("pushButton_loadBraggFile"))
        self.verticalLayout_4.addWidget(self.pushButton_loadBraggFile)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem10)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem11)
        self.checkBox_bank1 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank1.setObjectName(_fromUtf8("checkBox_bank1"))
        self.verticalLayout_4.addWidget(self.checkBox_bank1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem12)
        self.checkBox_bank2 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank2.setObjectName(_fromUtf8("checkBox_bank2"))
        self.verticalLayout_4.addWidget(self.checkBox_bank2)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem13)
        self.checkBox_bank3 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank3.setObjectName(_fromUtf8("checkBox_bank3"))
        self.verticalLayout_4.addWidget(self.checkBox_bank3)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem14)
        self.checkBox_bank4 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank4.setObjectName(_fromUtf8("checkBox_bank4"))
        self.verticalLayout_4.addWidget(self.checkBox_bank4)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem15)
        self.checkBox_bank5 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank5.setObjectName(_fromUtf8("checkBox_bank5"))
        self.verticalLayout_4.addWidget(self.checkBox_bank5)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem16)
        self.checkBox_bank6 = QtGui.QCheckBox(self.tab_bragg)
        self.checkBox_bank6.setObjectName(_fromUtf8("checkBox_bank6"))
        self.verticalLayout_4.addWidget(self.checkBox_bank6)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem17)
        self.radioButton_multiBank = QtGui.QRadioButton(self.tab_bragg)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_multiBank.setFont(font)
        self.radioButton_multiBank.setObjectName(_fromUtf8("radioButton_multiBank"))
        self.verticalLayout_4.addWidget(self.radioButton_multiBank)
        self.radioButton_multiGSS = QtGui.QRadioButton(self.tab_bragg)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_multiGSS.setFont(font)
        self.radioButton_multiGSS.setObjectName(_fromUtf8("radioButton_multiGSS"))
        self.verticalLayout_4.addWidget(self.radioButton_multiGSS)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem18)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.treeWidget_braggWSList = BraggTree(self.tab_bragg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_braggWSList.sizePolicy().hasHeightForWidth())
        self.treeWidget_braggWSList.setSizePolicy(sizePolicy)
        self.treeWidget_braggWSList.setObjectName(_fromUtf8("treeWidget_braggWSList"))
        self.horizontalLayout_4.addWidget(self.treeWidget_braggWSList)
        self.tabWidget.addTab(self.tab_bragg, _fromUtf8(""))
        self.tab_gR = QtGui.QWidget()
        self.tab_gR.setObjectName(_fromUtf8("tab_gR"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_gR)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_loadSQ = QtGui.QPushButton(self.tab_gR)
        self.pushButton_loadSQ.setObjectName(_fromUtf8("pushButton_loadSQ"))
        self.verticalLayout_2.addWidget(self.pushButton_loadSQ)
        self.radioButton_sq = QtGui.QRadioButton(self.tab_gR)
        self.radioButton_sq.setObjectName(_fromUtf8("radioButton_sq"))
        self.verticalLayout_2.addWidget(self.radioButton_sq)
        self.radioButton_sqm1 = QtGui.QRadioButton(self.tab_gR)
        self.radioButton_sqm1.setObjectName(_fromUtf8("radioButton_sqm1"))
        self.verticalLayout_2.addWidget(self.radioButton_sqm1)
        self.radioButton_qsqm1 = QtGui.QRadioButton(self.tab_gR)
        self.radioButton_qsqm1.setObjectName(_fromUtf8("radioButton_qsqm1"))
        self.verticalLayout_2.addWidget(self.radioButton_qsqm1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.labelQmax = QtGui.QLabel(self.tab_gR)
        self.labelQmax.setObjectName(_fromUtf8("labelQmax"))
        self.gridLayout_4.addWidget(self.labelQmax, 1, 0, 1, 1)
        self.doubleSpinBoxQmax = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxQmax.setMinimum(1.0)
        self.doubleSpinBoxQmax.setMaximum(50.0)
        self.doubleSpinBoxQmax.setSingleStep(0.5)
        self.doubleSpinBoxQmax.setObjectName(_fromUtf8("doubleSpinBoxQmax"))
        self.gridLayout_4.addWidget(self.doubleSpinBoxQmax, 1, 1, 1, 1)
        self.doubleSpinBoxQmin = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxQmin.setMinimum(0.01)
        self.doubleSpinBoxQmin.setMaximum(10.0)
        self.doubleSpinBoxQmin.setSingleStep(0.01)
        self.doubleSpinBoxQmin.setObjectName(_fromUtf8("doubleSpinBoxQmin"))
        self.gridLayout_4.addWidget(self.doubleSpinBoxQmin, 0, 1, 1, 1)
        self.labelQmin = QtGui.QLabel(self.tab_gR)
        self.labelQmin.setObjectName(_fromUtf8("labelQmin"))
        self.gridLayout_4.addWidget(self.labelQmin, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_gR)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.tab_gR)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_4.addWidget(self.checkBox, 3, 1, 1, 1)
        self.pushButton_showQMinMax = QtGui.QPushButton(self.tab_gR)
        self.pushButton_showQMinMax.setObjectName(_fromUtf8("pushButton_showQMinMax"))
        self.gridLayout_4.addWidget(self.pushButton_showQMinMax, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButton_generateGR = QtGui.QPushButton(self.tab_gR)
        self.pushButton_generateGR.setObjectName(_fromUtf8("pushButton_generateGR"))
        self.gridLayout_7.addWidget(self.pushButton_generateGR, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem19)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.treeWidget_grWsList = GofRTree(self.tab_gR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_grWsList.sizePolicy().hasHeightForWidth())
        self.treeWidget_grWsList.setSizePolicy(sizePolicy)
        self.treeWidget_grWsList.setObjectName(_fromUtf8("treeWidget_grWsList"))
        self.verticalLayout_3.addWidget(self.treeWidget_grWsList)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelRmin = QtGui.QLabel(self.tab_gR)
        self.labelRmin.setObjectName(_fromUtf8("labelRmin"))
        self.gridLayout_3.addWidget(self.labelRmin, 0, 0, 1, 1)
        self.labeldelR = QtGui.QLabel(self.tab_gR)
        self.labeldelR.setObjectName(_fromUtf8("labeldelR"))
        self.gridLayout_3.addWidget(self.labeldelR, 0, 2, 1, 1)
        self.labelRmax = QtGui.QLabel(self.tab_gR)
        self.labelRmax.setObjectName(_fromUtf8("labelRmax"))
        self.gridLayout_3.addWidget(self.labelRmax, 0, 4, 1, 1)
        self.doubleSpinBoxRmin = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxRmin.setMinimum(0.1)
        self.doubleSpinBoxRmin.setMaximum(4.0)
        self.doubleSpinBoxRmin.setSingleStep(0.1)
        self.doubleSpinBoxRmin.setObjectName(_fromUtf8("doubleSpinBoxRmin"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxRmin, 1, 0, 1, 1)
        self.doubleSpinBoxDelR = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxDelR.setMinimum(0.01)
        self.doubleSpinBoxDelR.setMaximum(1.0)
        self.doubleSpinBoxDelR.setSingleStep(0.01)
        self.doubleSpinBoxDelR.setProperty("value", 0.1)
        self.doubleSpinBoxDelR.setObjectName(_fromUtf8("doubleSpinBoxDelR"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxDelR, 1, 2, 1, 1)
        self.doubleSpinBoxRmax = QtGui.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxRmax.setMinimum(5.0)
        self.doubleSpinBoxRmax.setMaximum(100.0)
        self.doubleSpinBoxRmax.setProperty("value", 20.0)
        self.doubleSpinBoxRmax.setObjectName(_fromUtf8("doubleSpinBoxRmax"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxRmax, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.pushButton_clearGrCanvas = QtGui.QPushButton(self.tab_gR)
        self.pushButton_clearGrCanvas.setObjectName(_fromUtf8("pushButton_clearGrCanvas"))
        self.verticalLayout_3.addWidget(self.pushButton_clearGrCanvas)
        self.pushButton_saveGR = QtGui.QPushButton(self.tab_gR)
        self.pushButton_saveGR.setObjectName(_fromUtf8("pushButton_saveGR"))
        self.verticalLayout_3.addWidget(self.pushButton_saveGR)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 4, 2, 1, 1)
        self.graphicsView_gr = GofRView(self.tab_gR)
        self.graphicsView_gr.setMinimumSize(QtCore.QSize(50, 300))
        self.graphicsView_gr.setObjectName(_fromUtf8("graphicsView_gr"))
        self.gridLayout_5.addWidget(self.graphicsView_gr, 4, 0, 1, 1)
        self.graphicsView_sq = SofQView(self.tab_gR)
        self.graphicsView_sq.setMinimumSize(QtCore.QSize(50, 300))
        self.graphicsView_sq.setObjectName(_fromUtf8("graphicsView_sq"))
        self.gridLayout_5.addWidget(self.graphicsView_sq, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_gR, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_ipython = IPythonDockWidget(MainWindow)
        self.dockWidget_ipython.setMinimumSize(QtCore.QSize(50, 36))
        self.dockWidget_ipython.setMaximumSize(QtCore.QSize(524287, 300))
        self.dockWidget_ipython.setObjectName(_fromUtf8("dockWidget_ipython"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dockWidget_ipython.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_ipython)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionShow_Cheat_Sheet = QtGui.QAction(MainWindow)
        self.actionShow_Cheat_Sheet.setObjectName(_fromUtf8("actionShow_Cheat_Sheet"))
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionShow_Cheat_Sheet)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.diamond, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.diamond_edited)
        QtCore.QObject.connect(self.diamond_background, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.diamond_background_edited)
        QtCore.QObject.connect(self.vanadium, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.vanadium_edited)
        QtCore.QObject.connect(self.vanadium_background, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.vanadium_background_edited)
        QtCore.QObject.connect(self.sample_background, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.sample_background_edited)
        QtCore.QObject.connect(self.auto_manual_folder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.output_folder_radio_buttons)
        QtCore.QObject.connect(self.manual_output_folder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.output_folder_radio_buttons)
        QtCore.QObject.connect(self.manual_output_folder_field, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.manual_output_folder_field_edited)
        QtCore.QObject.connect(self.run_autonom_script, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.run_autonom)
        QtCore.QObject.connect(self.table, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), MainWindow.table_right_click)
        QtCore.QObject.connect(self.run_ndabs_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.run_ndabs_clicked)
        QtCore.QObject.connect(self.populate_table, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.populate_table_clicked)
        QtCore.QObject.connect(self.plazcek_fit_range_min, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_plazcek_widgets)
        QtCore.QObject.connect(self.plazcek_fit_range_max, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_plazcek_widgets)
        QtCore.QObject.connect(self.hydrogen_yes, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.hidrogen_clicked)
        QtCore.QObject.connect(self.hydrogen_no, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.no_hidrogen_clicked)
        QtCore.QObject.connect(self.fourier_filter_from, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_fourier_filter_widgets)
        QtCore.QObject.connect(self.fourier_filter_to, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.check_fourier_filter_widgets)
        QtCore.QObject.connect(self.create_sample_properties_files_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_sample_properties_files_clicked)
        QtCore.QObject.connect(self.background_yes, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.yes_background_clicked)
        QtCore.QObject.connect(self.background_comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.background_combobox_changed)
        QtCore.QObject.connect(self.move_to_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.move_to_folder_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.diamond, self.diamond_background)
        MainWindow.setTabOrder(self.diamond_background, self.vanadium)
        MainWindow.setTabOrder(self.vanadium, self.vanadium_background)
        MainWindow.setTabOrder(self.vanadium_background, self.sample_background)
        MainWindow.setTabOrder(self.sample_background, self.first_scan)
        MainWindow.setTabOrder(self.first_scan, self.last_scan)
        MainWindow.setTabOrder(self.last_scan, self.frequency)
        MainWindow.setTabOrder(self.frequency, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.renormalization_yes)
        MainWindow.setTabOrder(self.renormalization_yes, self.radioButton_11)
        MainWindow.setTabOrder(self.radioButton_11, self.autotemplate_yes)
        MainWindow.setTabOrder(self.autotemplate_yes, self.radioButton_13)
        MainWindow.setTabOrder(self.radioButton_13, self.comments)
        MainWindow.setTabOrder(self.comments, self.run_autonom_script)
        MainWindow.setTabOrder(self.run_autonom_script, self.auto_manual_folder)
        MainWindow.setTabOrder(self.auto_manual_folder, self.manual_output_folder)
        MainWindow.setTabOrder(self.manual_output_folder, self.manual_output_folder_field)
        MainWindow.setTabOrder(self.manual_output_folder_field, self.table)
        MainWindow.setTabOrder(self.table, self.background_no)
        MainWindow.setTabOrder(self.background_no, self.background_yes)
        MainWindow.setTabOrder(self.background_yes, self.background_comboBox)
        MainWindow.setTabOrder(self.background_comboBox, self.background_line_edit)
        MainWindow.setTabOrder(self.background_line_edit, self.fourier_filter_from)
        MainWindow.setTabOrder(self.fourier_filter_from, self.fourier_filter_to)
        MainWindow.setTabOrder(self.fourier_filter_to, self.hydrogen_yes)
        MainWindow.setTabOrder(self.hydrogen_yes, self.hydrogen_no)
        MainWindow.setTabOrder(self.hydrogen_no, self.plazcek_fit_range_min)
        MainWindow.setTabOrder(self.plazcek_fit_range_min, self.plazcek_fit_range_max)
        MainWindow.setTabOrder(self.plazcek_fit_range_max, self.muscat_yes)
        MainWindow.setTabOrder(self.muscat_yes, self.radioButton_14)
        MainWindow.setTabOrder(self.radioButton_14, self.scale_data_yes)
        MainWindow.setTabOrder(self.scale_data_yes, self.radioButton_15)
        MainWindow.setTabOrder(self.radioButton_15, self.run_rmc_yes)
        MainWindow.setTabOrder(self.run_rmc_yes, self.radioButton_16)
        MainWindow.setTabOrder(self.radioButton_16, self.create_sample_properties_files_button)
        MainWindow.setTabOrder(self.create_sample_properties_files_button, self.run_ndabs_button)
        MainWindow.setTabOrder(self.run_ndabs_button, self.graphicsView_bragg)
        MainWindow.setTabOrder(self.graphicsView_bragg, self.pushButton_loadBraggFile)
        MainWindow.setTabOrder(self.pushButton_loadBraggFile, self.treeWidget_braggWSList)
        MainWindow.setTabOrder(self.treeWidget_braggWSList, self.checkBox_bank1)
        MainWindow.setTabOrder(self.checkBox_bank1, self.checkBox_bank2)
        MainWindow.setTabOrder(self.checkBox_bank2, self.checkBox_bank3)
        MainWindow.setTabOrder(self.checkBox_bank3, self.checkBox_bank4)
        MainWindow.setTabOrder(self.checkBox_bank4, self.checkBox_bank5)
        MainWindow.setTabOrder(self.checkBox_bank5, self.checkBox_bank6)
        MainWindow.setTabOrder(self.checkBox_bank6, self.radioButton_multiBank)
        MainWindow.setTabOrder(self.radioButton_multiBank, self.radioButton_multiGSS)
        MainWindow.setTabOrder(self.radioButton_multiGSS, self.comboBox_xUnit)
        MainWindow.setTabOrder(self.comboBox_xUnit, self.pushButton_combineBanks)
        MainWindow.setTabOrder(self.pushButton_combineBanks, self.graphicsView_sq)
        MainWindow.setTabOrder(self.graphicsView_sq, self.graphicsView_gr)
        MainWindow.setTabOrder(self.graphicsView_gr, self.pushButton_loadSQ)
        MainWindow.setTabOrder(self.pushButton_loadSQ, self.radioButton_sq)
        MainWindow.setTabOrder(self.radioButton_sq, self.radioButton_sqm1)
        MainWindow.setTabOrder(self.radioButton_sqm1, self.radioButton_qsqm1)
        MainWindow.setTabOrder(self.radioButton_qsqm1, self.doubleSpinBoxQmin)
        MainWindow.setTabOrder(self.doubleSpinBoxQmin, self.doubleSpinBoxQmax)
        MainWindow.setTabOrder(self.doubleSpinBoxQmax, self.pushButton_showQMinMax)
        MainWindow.setTabOrder(self.pushButton_showQMinMax, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.pushButton_generateGR)
        MainWindow.setTabOrder(self.pushButton_generateGR, self.treeWidget_grWsList)
        MainWindow.setTabOrder(self.treeWidget_grWsList, self.doubleSpinBoxRmin)
        MainWindow.setTabOrder(self.doubleSpinBoxRmin, self.doubleSpinBoxDelR)
        MainWindow.setTabOrder(self.doubleSpinBoxDelR, self.doubleSpinBoxRmax)
        MainWindow.setTabOrder(self.doubleSpinBoxRmax, self.pushButton_clearGrCanvas)
        MainWindow.setTabOrder(self.pushButton_clearGrCanvas, self.pushButton_saveGR)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Scan Numbers  (ex: 1234, 1300-1305, 1310)", None))
        self.label_8.setText(_translate("MainWindow", "*", None))
        self.label_7.setText(_translate("MainWindow", "Vanadium background", None))
        self.label.setText(_translate("MainWindow", "Diamond", None))
        self.label_5.setText(_translate("MainWindow", "Vanadium", None))
        self.label_4.setText(_translate("MainWindow", "*", None))
        self.label_6.setText(_translate("MainWindow", "*", None))
        self.label_9.setText(_translate("MainWindow", "*", None))
        self.label_10.setText(_translate("MainWindow", "*", None))
        self.label_11.setText(_translate("MainWindow", "Diamond background", None))
        self.label_12.setText(_translate("MainWindow", "Sample background", None))
        self.label_21.setText(_translate("MainWindow", "*", None))
        self.label_22.setText(_translate("MainWindow", ": Mandatory field", None))
        self.label_18.setText(_translate("MainWindow", "First scan to be analyzed", None))
        self.label_20.setText(_translate("MainWindow", "Frequency (Hz)", None))
        self.label_19.setText(_translate("MainWindow", "Last scan to be analyzed", None))
        self.frequency.setItemText(0, _translate("MainWindow", "60", None))
        self.frequency.setItemText(1, _translate("MainWindow", "30", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Recalibration", None))
        self.recalibration_yes.setText(_translate("MainWindow", "yes", None))
        self.radioButton_3.setText(_translate("MainWindow", "No", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Renormalization", None))
        self.renormalization_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_11.setText(_translate("MainWindow", "No", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Autotemplate", None))
        self.autotemplate_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_13.setText(_translate("MainWindow", "No", None))
        self.label_14.setText(_translate("MainWindow", "Comments:", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Name of Output Folder", None))
        self.auto_manual_folder.setText(_translate("MainWindow", "Automatic (autoNOM_##)", None))
        self.manual_output_folder.setText(_translate("MainWindow", "Manual", None))
        self.run_autonom_script.setText(_translate("MainWindow", "Run autoNOM script", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "autoNOM", None))
        self.move_to_button.setText(_translate("MainWindow", "Move to Folder ...", None))
        self.label_13.setText(_translate("MainWindow", "Current folder:", None))
        self.current_folder_label.setText(_translate("MainWindow", "N/A", None))
        self.populate_table.setText(_translate("MainWindow", "Populate Table", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Select", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Runs", None))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sample Formula", None))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mass Density (g/cc)", None))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Radius (cm)", None))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Packing Fraction", None))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sample Shape", None))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Do Abs. Corr. ?", None))
        self.label_29.setText(_translate("MainWindow", "Sample formula example: H 2 O 1, 2H 2 O 1, 238U 1 O 2", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Background", None))
        self.background_no.setText(_translate("MainWindow", "No", None))
        self.background_no_field.setText(_translate("MainWindow", "N/A", None))
        self.label_15.setText(_translate("MainWindow", "(from exp.ini file)", None))
        self.background_yes.setText(_translate("MainWindow", "Yes", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Fourier Filter (ex: 1.5, 50)", None))
        self.fourier_filter_from.setText(_translate("MainWindow", "1.5", None))
        self.label_16.setText(_translate("MainWindow", "*", None))
        self.label_17.setText(_translate("MainWindow", ",", None))
        self.fourier_filter_to.setText(_translate("MainWindow", "50", None))
        self.label_23.setText(_translate("MainWindow", "*", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Plazcek", None))
        self.label_24.setText(_translate("MainWindow", "Type", None))
        self.hydrogen_yes.setText(_translate("MainWindow", "hydrogen", None))
        self.hydrogen_no.setText(_translate("MainWindow", "no hydrogren", None))
        self.label_25.setText(_translate("MainWindow", "Fit Range", None))
        self.plazcek_fit_range_min.setText(_translate("MainWindow", "10", None))
        self.label_26.setText(_translate("MainWindow", "*", None))
        self.label_27.setText(_translate("MainWindow", ",", None))
        self.plazcek_fit_range_max.setText(_translate("MainWindow", "50", None))
        self.label_28.setText(_translate("MainWindow", "*", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Muscat", None))
        self.muscat_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_14.setText(_translate("MainWindow", "No", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Scale Data", None))
        self.scale_data_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_15.setText(_translate("MainWindow", "No", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Run RMC", None))
        self.run_rmc_yes.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_16.setText(_translate("MainWindow", "No", None))
        self.label_30.setText(_translate("MainWindow", "*", None))
        self.label_31.setText(_translate("MainWindow", ": Mandatory field", None))
        self.create_sample_properties_files_button.setText(_translate("MainWindow", "Create Sample Properties Files", None))
        self.run_ndabs_button.setText(_translate("MainWindow", "Run NDabs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "NDabs", None))
        self.label_3.setText(_translate("MainWindow", "SNS Powder Reduction Configuration for NOMAD", None))
        self.comboBox_xUnit.setItemText(0, _translate("MainWindow", "TOF", None))
        self.comboBox_xUnit.setItemText(1, _translate("MainWindow", "d-Spacing", None))
        self.comboBox_xUnit.setItemText(2, _translate("MainWindow", "Q", None))
        self.pushButton_combineBanks.setToolTip(_translate("MainWindow", "<html><head/><body><p>Combine banks back to a 6-bank GSAS file</p></body></html>", None))
        self.pushButton_combineBanks.setText(_translate("MainWindow", "Combine to GSAS", None))
        self.pushButton_loadBraggFile.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load GSS/S(Q)/general 3-column ASCII</p><p>1. GSS: load and then split to 6 workspaces with single spectrum.  Finally group all 6 workspaces to a workspace group</p></body></html>", None))
        self.pushButton_loadBraggFile.setText(_translate("MainWindow", "Load", None))
        self.checkBox_bank1.setText(_translate("MainWindow", "Bank 1", None))
        self.checkBox_bank2.setText(_translate("MainWindow", "Bank 2", None))
        self.checkBox_bank3.setText(_translate("MainWindow", "Bank 3", None))
        self.checkBox_bank4.setText(_translate("MainWindow", "Bank 4", None))
        self.checkBox_bank5.setText(_translate("MainWindow", "Bank 5", None))
        self.checkBox_bank6.setText(_translate("MainWindow", "Bank 6", None))
        self.radioButton_multiBank.setText(_translate("MainWindow", "Multiple Banks", None))
        self.radioButton_multiGSS.setText(_translate("MainWindow", "Multiple GSS", None))
        self.treeWidget_braggWSList.setToolTip(_translate("MainWindow", "<html><head/><body><p>List of workspace names.  Each workspace is an individual bank</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bragg), _translate("MainWindow", "Bragg Peaks", None))
        self.pushButton_loadSQ.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load S(Q) from the reduction tab. Plot S(Q), S(Q)-1 or Q[S(Q)-1] according to the selected radio buttons below.</p><p><span style=\" font-weight:600;\">Use regular file loader at this phase.</span></p><p>Duplicate the function in FastGR/scripts/addie</p><p>149     def read_SQ_file(self):</p><p><br/></p></body></html>", None))
        self.pushButton_loadSQ.setText(_translate("MainWindow", "Load SQ", None))
        self.radioButton_sq.setText(_translate("MainWindow", "S(Q)", None))
        self.radioButton_sqm1.setText(_translate("MainWindow", "S(Q)-1", None))
        self.radioButton_qsqm1.setText(_translate("MainWindow", "Q[S(Q)-1]", None))
        self.labelQmax.setText(_translate("MainWindow", "Qmax", None))
        self.labelQmin.setText(_translate("MainWindow", "Qmin", None))
        self.label_2.setText(_translate("MainWindow", "More Options ...", None))
        self.checkBox.setText(_translate("MainWindow", "CheckBox", None))
        self.pushButton_showQMinMax.setToolTip(_translate("MainWindow", "<html><head/><body><p>Show or hide the vertical indicators for Qmin and Qmax</p></body></html>", None))
        self.pushButton_showQMinMax.setText(_translate("MainWindow", "Show Min/Max", None))
        self.pushButton_generateGR.setText(_translate("MainWindow", "Generate GR", None))
        self.treeWidget_grWsList.setToolTip(_translate("MainWindow", "<html><head/><body><p>write click on the workspace name should give user the option to plot/over plot </p></body></html>", None))
        self.labelRmin.setText(_translate("MainWindow", "Rmin", None))
        self.labeldelR.setText(_translate("MainWindow", "deltaR", None))
        self.labelRmax.setText(_translate("MainWindow", "Rmax", None))
        self.pushButton_clearGrCanvas.setText(_translate("MainWindow", "Clear Canvas", None))
        self.pushButton_saveGR.setText(_translate("MainWindow", "Save GR", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gR), _translate("MainWindow", "Calculate G(R)", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionShow_Cheat_Sheet.setText(_translate("MainWindow", "Show Cheat Sheet", None))

from graphicviewlib import BraggView, SofQView, GofRView
from ipythondockwidget import IPythonDockWidget
from treelib import GofRTree, BraggTree
