# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_mainWindow_no_scroll_bars.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 778)
        MainWindow.setMinimumSize(QtCore.QSize(500, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.diamond_background = QtWidgets.QLineEdit(self.groupBox_5)
        self.diamond_background.setToolTip("")
        self.diamond_background.setStatusTip("")
        self.diamond_background.setAccessibleDescription("")
        self.diamond_background.setInputMask("")
        self.diamond_background.setText("")
        self.diamond_background.setPlaceholderText("")
        self.diamond_background.setObjectName("diamond_background")
        self.gridLayout.addWidget(self.diamond_background, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sample_background = QtWidgets.QLineEdit(self.groupBox_5)
        self.sample_background.setToolTip("")
        self.sample_background.setStatusTip("")
        self.sample_background.setAccessibleDescription("")
        self.sample_background.setInputMask("")
        self.sample_background.setText("")
        self.sample_background.setPlaceholderText("")
        self.sample_background.setObjectName("sample_background")
        self.gridLayout.addWidget(self.sample_background, 4, 1, 1, 1)
        self.vanadium = QtWidgets.QLineEdit(self.groupBox_5)
        self.vanadium.setToolTip("")
        self.vanadium.setStatusTip("")
        self.vanadium.setAccessibleDescription("")
        self.vanadium.setInputMask("")
        self.vanadium.setText("")
        self.vanadium.setPlaceholderText("")
        self.vanadium.setObjectName("vanadium")
        self.gridLayout.addWidget(self.vanadium, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.vanadium_background = QtWidgets.QLineEdit(self.groupBox_5)
        self.vanadium_background.setToolTip("")
        self.vanadium_background.setStatusTip("")
        self.vanadium_background.setAccessibleDescription("")
        self.vanadium_background.setInputMask("")
        self.vanadium_background.setText("")
        self.vanadium_background.setPlaceholderText("")
        self.vanadium_background.setObjectName("vanadium_background")
        self.gridLayout.addWidget(self.vanadium_background, 3, 1, 1, 1)
        self.diamond = QtWidgets.QLineEdit(self.groupBox_5)
        self.diamond.setToolTip("")
        self.diamond.setStatusTip("")
        self.diamond.setAccessibleDescription("")
        self.diamond.setInputMask("")
        self.diamond.setText("")
        self.diamond.setPlaceholderText("")
        self.diamond.setObjectName("diamond")
        self.gridLayout.addWidget(self.diamond, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_21.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_14.addWidget(self.groupBox_5)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_14.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 1, 0, 1, 1)
        self.last_scan = QtWidgets.QLineEdit(self.tab)
        self.last_scan.setText("")
        self.last_scan.setObjectName("last_scan")
        self.gridLayout_6.addWidget(self.last_scan, 1, 1, 1, 1)
        self.first_scan = QtWidgets.QLineEdit(self.tab)
        self.first_scan.setText("")
        self.first_scan.setObjectName("first_scan")
        self.gridLayout_6.addWidget(self.first_scan, 0, 1, 1, 1)
        self.frequency = QtWidgets.QComboBox(self.tab)
        self.frequency.setObjectName("frequency")
        self.frequency.addItem("")
        self.frequency.addItem("")
        self.gridLayout_6.addWidget(self.frequency, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.recalibration_yes = QtWidgets.QRadioButton(self.groupBox_6)
        self.recalibration_yes.setObjectName("recalibration_yes")
        self.horizontalLayout_14.addWidget(self.recalibration_yes)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_14.addWidget(self.radioButton_3)
        self.horizontalLayout_13.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.renormalization_yes = QtWidgets.QRadioButton(self.groupBox_7)
        self.renormalization_yes.setObjectName("renormalization_yes")
        self.horizontalLayout_15.addWidget(self.renormalization_yes)
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_11.setChecked(True)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_15.addWidget(self.radioButton_11)
        self.horizontalLayout_13.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.autotemplate_yes = QtWidgets.QRadioButton(self.groupBox_8)
        self.autotemplate_yes.setChecked(True)
        self.autotemplate_yes.setObjectName("autotemplate_yes")
        self.horizontalLayout_16.addWidget(self.autotemplate_yes)
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_13.setChecked(False)
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_16.addWidget(self.radioButton_13)
        self.horizontalLayout_13.addWidget(self.groupBox_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.comments = QtWidgets.QLineEdit(self.tab)
        self.comments.setObjectName("comments")
        self.horizontalLayout_19.addWidget(self.comments)
        self.verticalLayout_14.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.auto_manual_folder = QtWidgets.QRadioButton(self.groupBox_9)
        self.auto_manual_folder.setChecked(True)
        self.auto_manual_folder.setObjectName("auto_manual_folder")
        self.verticalLayout_12.addWidget(self.auto_manual_folder)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.manual_output_folder = QtWidgets.QRadioButton(self.groupBox_9)
        self.manual_output_folder.setObjectName("manual_output_folder")
        self.horizontalLayout_18.addWidget(self.manual_output_folder)
        self.manual_output_folder_field = QtWidgets.QLineEdit(self.groupBox_9)
        self.manual_output_folder_field.setEnabled(False)
        self.manual_output_folder_field.setObjectName("manual_output_folder_field")
        self.horizontalLayout_18.addWidget(self.manual_output_folder_field)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.verticalLayout_11.addWidget(self.groupBox_9)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem4)
        self.run_autonom_script = QtWidgets.QPushButton(self.tab)
        self.run_autonom_script.setEnabled(False)
        self.run_autonom_script.setObjectName("run_autonom_script")
        self.verticalLayout_13.addWidget(self.run_autonom_script)
        self.horizontalLayout_17.addLayout(self.verticalLayout_13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.move_to_button = QtWidgets.QPushButton(self.tab_2)
        self.move_to_button.setMaximumSize(QtCore.QSize(130, 16777215))
        self.move_to_button.setObjectName("move_to_button")
        self.horizontalLayout_20.addWidget(self.move_to_button)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_20.addWidget(self.label_13)
        self.current_folder_label = QtWidgets.QLabel(self.tab_2)
        self.current_folder_label.setObjectName("current_folder_label")
        self.horizontalLayout_20.addWidget(self.current_folder_label)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.populate_table = QtWidgets.QPushButton(self.tab_2)
        self.populate_table.setObjectName("populate_table")
        self.verticalLayout_17.addWidget(self.populate_table)
        self.table = QtWidgets.QTableWidget(self.tab_2)
        self.table.setMinimumSize(QtCore.QSize(50, 0))
        self.table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.table.setAlternatingRowColors(True)
        self.table.setObjectName("table")
        self.table.setColumnCount(9)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_17.addWidget(self.table)
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_17.addWidget(self.label_29)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.background_no = QtWidgets.QRadioButton(self.groupBox_10)
        self.background_no.setMinimumSize(QtCore.QSize(50, 0))
        self.background_no.setMaximumSize(QtCore.QSize(50, 16777215))
        self.background_no.setChecked(True)
        self.background_no.setObjectName("background_no")
        self.horizontalLayout_22.addWidget(self.background_no)
        self.background_no_field = QtWidgets.QLabel(self.groupBox_10)
        self.background_no_field.setMinimumSize(QtCore.QSize(300, 0))
        self.background_no_field.setObjectName("background_no_field")
        self.horizontalLayout_22.addWidget(self.background_no_field)
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_22.addWidget(self.label_15)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.background_yes = QtWidgets.QRadioButton(self.groupBox_10)
        self.background_yes.setObjectName("background_yes")
        self.horizontalLayout_23.addWidget(self.background_yes)
        self.background_comboBox = QtWidgets.QComboBox(self.groupBox_10)
        self.background_comboBox.setEnabled(False)
        self.background_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.background_comboBox.setObjectName("background_comboBox")
        self.horizontalLayout_23.addWidget(self.background_comboBox)
        self.background_line_edit = QtWidgets.QLineEdit(self.groupBox_10)
        self.background_line_edit.setEnabled(False)
        self.background_line_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.background_line_edit.setObjectName("background_line_edit")
        self.horizontalLayout_23.addWidget(self.background_line_edit)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_21.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.fourier_filter_from = QtWidgets.QLineEdit(self.groupBox_11)
        self.fourier_filter_from.setObjectName("fourier_filter_from")
        self.horizontalLayout_24.addWidget(self.fourier_filter_from)
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_16.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_24.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.groupBox_11)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_24.addWidget(self.label_17)
        self.fourier_filter_to = QtWidgets.QLineEdit(self.groupBox_11)
        self.fourier_filter_to.setObjectName("fourier_filter_to")
        self.horizontalLayout_24.addWidget(self.fourier_filter_to)
        self.label_23 = QtWidgets.QLabel(self.groupBox_11)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_23.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_24.addWidget(self.label_23)
        self.horizontalLayout_21.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_24 = QtWidgets.QLabel(self.groupBox_12)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_25.addWidget(self.label_24)
        self.hydrogen_yes = QtWidgets.QRadioButton(self.groupBox_12)
        self.hydrogen_yes.setChecked(False)
        self.hydrogen_yes.setObjectName("hydrogen_yes")
        self.horizontalLayout_25.addWidget(self.hydrogen_yes)
        self.hydrogen_no = QtWidgets.QRadioButton(self.groupBox_12)
        self.hydrogen_no.setChecked(True)
        self.hydrogen_no.setObjectName("hydrogen_no")
        self.horizontalLayout_25.addWidget(self.hydrogen_no)
        self.verticalLayout_16.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_25 = QtWidgets.QLabel(self.groupBox_12)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_26.addWidget(self.label_25)
        self.plazcek_fit_range_min = QtWidgets.QLineEdit(self.groupBox_12)
        self.plazcek_fit_range_min.setMinimumSize(QtCore.QSize(50, 0))
        self.plazcek_fit_range_min.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plazcek_fit_range_min.setObjectName("plazcek_fit_range_min")
        self.horizontalLayout_26.addWidget(self.plazcek_fit_range_min)
        self.label_26 = QtWidgets.QLabel(self.groupBox_12)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_26.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_26.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.groupBox_12)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_26.addWidget(self.label_27)
        self.plazcek_fit_range_max = QtWidgets.QLineEdit(self.groupBox_12)
        self.plazcek_fit_range_max.setMinimumSize(QtCore.QSize(50, 0))
        self.plazcek_fit_range_max.setMaximumSize(QtCore.QSize(50, 16777215))
        self.plazcek_fit_range_max.setObjectName("plazcek_fit_range_max")
        self.horizontalLayout_26.addWidget(self.plazcek_fit_range_max)
        self.label_28 = QtWidgets.QLabel(self.groupBox_12)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_28.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_26.addWidget(self.label_28)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem5)
        self.verticalLayout_16.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_21.addWidget(self.groupBox_12)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_13.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.muscat_yes = QtWidgets.QRadioButton(self.groupBox_13)
        self.muscat_yes.setObjectName("muscat_yes")
        self.horizontalLayout_28.addWidget(self.muscat_yes)
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_13)
        self.radioButton_14.setChecked(True)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_28.addWidget(self.radioButton_14)
        self.horizontalLayout_27.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_14.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.scale_data_yes = QtWidgets.QRadioButton(self.groupBox_14)
        self.scale_data_yes.setChecked(True)
        self.scale_data_yes.setObjectName("scale_data_yes")
        self.horizontalLayout_29.addWidget(self.scale_data_yes)
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_15.setChecked(False)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_29.addWidget(self.radioButton_15)
        self.horizontalLayout_27.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_15.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.run_rmc_yes = QtWidgets.QRadioButton(self.groupBox_15)
        self.run_rmc_yes.setChecked(True)
        self.run_rmc_yes.setObjectName("run_rmc_yes")
        self.horizontalLayout_30.addWidget(self.run_rmc_yes)
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_16.setChecked(False)
        self.radioButton_16.setObjectName("radioButton_16")
        self.horizontalLayout_30.addWidget(self.radioButton_16)
        self.horizontalLayout_27.addWidget(self.groupBox_15)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem6)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_27)
        self.verticalLayout_17.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_30.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_31.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_31.addWidget(self.label_31)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem7)
        self.create_sample_properties_files_button = QtWidgets.QPushButton(self.tab_2)
        self.create_sample_properties_files_button.setEnabled(False)
        self.create_sample_properties_files_button.setObjectName("create_sample_properties_files_button")
        self.horizontalLayout_31.addWidget(self.create_sample_properties_files_button)
        self.run_ndabs_button = QtWidgets.QPushButton(self.tab_2)
        self.run_ndabs_button.setEnabled(False)
        self.run_ndabs_button.setObjectName("run_ndabs_button")
        self.horizontalLayout_31.addWidget(self.run_ndabs_button)
        self.verticalLayout_17.addLayout(self.horizontalLayout_31)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_bragg = QtWidgets.QWidget()
        self.tab_bragg.setObjectName("tab_bragg")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_bragg)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_bragg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.graphicsView_bragg = BraggView(self.tab_bragg)
        self.graphicsView_bragg.setObjectName("graphicsView_bragg")
        self.verticalLayout_5.addWidget(self.graphicsView_bragg)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_xUnit = QtWidgets.QComboBox(self.tab_bragg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_xUnit.sizePolicy().hasHeightForWidth())
        self.comboBox_xUnit.setSizePolicy(sizePolicy)
        self.comboBox_xUnit.setObjectName("comboBox_xUnit")
        self.comboBox_xUnit.addItem("")
        self.comboBox_xUnit.addItem("")
        self.comboBox_xUnit.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_xUnit)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.pushButton_combineBanks = QtWidgets.QPushButton(self.tab_bragg)
        self.pushButton_combineBanks.setObjectName("pushButton_combineBanks")
        self.horizontalLayout_3.addWidget(self.pushButton_combineBanks)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_loadBraggFile = QtWidgets.QPushButton(self.tab_bragg)
        self.pushButton_loadBraggFile.setObjectName("pushButton_loadBraggFile")
        self.verticalLayout_4.addWidget(self.pushButton_loadBraggFile)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem11)
        self.checkBox_bank1 = QtWidgets.QCheckBox(self.tab_bragg)
        self.checkBox_bank1.setObjectName("checkBox_bank1")
        self.verticalLayout_4.addWidget(self.checkBox_bank1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem12)
        self.checkBox_bank2 = QtWidgets.QCheckBox(self.tab_bragg)
        self.checkBox_bank2.setObjectName("checkBox_bank2")
        self.verticalLayout_4.addWidget(self.checkBox_bank2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem13)
        self.checkBox_bank3 = QtWidgets.QCheckBox(self.tab_bragg)
        self.checkBox_bank3.setObjectName("checkBox_bank3")
        self.verticalLayout_4.addWidget(self.checkBox_bank3)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem14)
        self.checkBox_bank4 = QtWidgets.QCheckBox(self.tab_bragg)
        self.checkBox_bank4.setObjectName("checkBox_bank4")
        self.verticalLayout_4.addWidget(self.checkBox_bank4)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem15)
        self.checkBox_bank5 = QtWidgets.QCheckBox(self.tab_bragg)
        self.checkBox_bank5.setObjectName("checkBox_bank5")
        self.verticalLayout_4.addWidget(self.checkBox_bank5)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem16)
        self.checkBox_bank6 = QtWidgets.QCheckBox(self.tab_bragg)
        self.checkBox_bank6.setObjectName("checkBox_bank6")
        self.verticalLayout_4.addWidget(self.checkBox_bank6)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem17)
        self.radioButton_multiBank = QtWidgets.QRadioButton(self.tab_bragg)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_multiBank.setFont(font)
        self.radioButton_multiBank.setObjectName("radioButton_multiBank")
        self.verticalLayout_4.addWidget(self.radioButton_multiBank)
        self.radioButton_multiGSS = QtWidgets.QRadioButton(self.tab_bragg)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_multiGSS.setFont(font)
        self.radioButton_multiGSS.setObjectName("radioButton_multiGSS")
        self.verticalLayout_4.addWidget(self.radioButton_multiGSS)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem18)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.treeWidget_braggWSList = BraggTree(self.tab_bragg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_braggWSList.sizePolicy().hasHeightForWidth())
        self.treeWidget_braggWSList.setSizePolicy(sizePolicy)
        self.treeWidget_braggWSList.setObjectName("treeWidget_braggWSList")
        self.horizontalLayout_4.addWidget(self.treeWidget_braggWSList)
        self.tabWidget.addTab(self.tab_bragg, "")
        self.tab_gR = QtWidgets.QWidget()
        self.tab_gR.setObjectName("tab_gR")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_gR)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_loadSQ = QtWidgets.QPushButton(self.tab_gR)
        self.pushButton_loadSQ.setObjectName("pushButton_loadSQ")
        self.verticalLayout_2.addWidget(self.pushButton_loadSQ)
        self.radioButton_sq = QtWidgets.QRadioButton(self.tab_gR)
        self.radioButton_sq.setObjectName("radioButton_sq")
        self.verticalLayout_2.addWidget(self.radioButton_sq)
        self.radioButton_sqm1 = QtWidgets.QRadioButton(self.tab_gR)
        self.radioButton_sqm1.setObjectName("radioButton_sqm1")
        self.verticalLayout_2.addWidget(self.radioButton_sqm1)
        self.radioButton_qsqm1 = QtWidgets.QRadioButton(self.tab_gR)
        self.radioButton_qsqm1.setObjectName("radioButton_qsqm1")
        self.verticalLayout_2.addWidget(self.radioButton_qsqm1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelQmax = QtWidgets.QLabel(self.tab_gR)
        self.labelQmax.setObjectName("labelQmax")
        self.gridLayout_4.addWidget(self.labelQmax, 1, 0, 1, 1)
        self.doubleSpinBoxQmax = QtWidgets.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxQmax.setMinimum(1.0)
        self.doubleSpinBoxQmax.setMaximum(50.0)
        self.doubleSpinBoxQmax.setSingleStep(0.5)
        self.doubleSpinBoxQmax.setObjectName("doubleSpinBoxQmax")
        self.gridLayout_4.addWidget(self.doubleSpinBoxQmax, 1, 1, 1, 1)
        self.doubleSpinBoxQmin = QtWidgets.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxQmin.setMinimum(0.01)
        self.doubleSpinBoxQmin.setMaximum(10.0)
        self.doubleSpinBoxQmin.setSingleStep(0.01)
        self.doubleSpinBoxQmin.setObjectName("doubleSpinBoxQmin")
        self.gridLayout_4.addWidget(self.doubleSpinBoxQmin, 0, 1, 1, 1)
        self.labelQmin = QtWidgets.QLabel(self.tab_gR)
        self.labelQmin.setObjectName("labelQmin")
        self.gridLayout_4.addWidget(self.labelQmin, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_gR)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.tab_gR)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 3, 1, 1, 1)
        self.pushButton_showQMinMax = QtWidgets.QPushButton(self.tab_gR)
        self.pushButton_showQMinMax.setObjectName("pushButton_showQMinMax")
        self.gridLayout_4.addWidget(self.pushButton_showQMinMax, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_generateGR = QtWidgets.QPushButton(self.tab_gR)
        self.pushButton_generateGR.setObjectName("pushButton_generateGR")
        self.gridLayout_7.addWidget(self.pushButton_generateGR, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem19)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeWidget_grWsList = GofRTree(self.tab_gR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_grWsList.sizePolicy().hasHeightForWidth())
        self.treeWidget_grWsList.setSizePolicy(sizePolicy)
        self.treeWidget_grWsList.setObjectName("treeWidget_grWsList")
        self.verticalLayout_3.addWidget(self.treeWidget_grWsList)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelRmin = QtWidgets.QLabel(self.tab_gR)
        self.labelRmin.setObjectName("labelRmin")
        self.gridLayout_3.addWidget(self.labelRmin, 0, 0, 1, 1)
        self.labeldelR = QtWidgets.QLabel(self.tab_gR)
        self.labeldelR.setObjectName("labeldelR")
        self.gridLayout_3.addWidget(self.labeldelR, 0, 2, 1, 1)
        self.labelRmax = QtWidgets.QLabel(self.tab_gR)
        self.labelRmax.setObjectName("labelRmax")
        self.gridLayout_3.addWidget(self.labelRmax, 0, 4, 1, 1)
        self.doubleSpinBoxRmin = QtWidgets.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxRmin.setMinimum(0.1)
        self.doubleSpinBoxRmin.setMaximum(4.0)
        self.doubleSpinBoxRmin.setSingleStep(0.1)
        self.doubleSpinBoxRmin.setObjectName("doubleSpinBoxRmin")
        self.gridLayout_3.addWidget(self.doubleSpinBoxRmin, 1, 0, 1, 1)
        self.doubleSpinBoxDelR = QtWidgets.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxDelR.setMinimum(0.01)
        self.doubleSpinBoxDelR.setMaximum(1.0)
        self.doubleSpinBoxDelR.setSingleStep(0.01)
        self.doubleSpinBoxDelR.setProperty("value", 0.1)
        self.doubleSpinBoxDelR.setObjectName("doubleSpinBoxDelR")
        self.gridLayout_3.addWidget(self.doubleSpinBoxDelR, 1, 2, 1, 1)
        self.doubleSpinBoxRmax = QtWidgets.QDoubleSpinBox(self.tab_gR)
        self.doubleSpinBoxRmax.setMinimum(5.0)
        self.doubleSpinBoxRmax.setMaximum(100.0)
        self.doubleSpinBoxRmax.setProperty("value", 20.0)
        self.doubleSpinBoxRmax.setObjectName("doubleSpinBoxRmax")
        self.gridLayout_3.addWidget(self.doubleSpinBoxRmax, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.pushButton_clearGrCanvas = QtWidgets.QPushButton(self.tab_gR)
        self.pushButton_clearGrCanvas.setObjectName("pushButton_clearGrCanvas")
        self.verticalLayout_3.addWidget(self.pushButton_clearGrCanvas)
        self.pushButton_saveGR = QtWidgets.QPushButton(self.tab_gR)
        self.pushButton_saveGR.setObjectName("pushButton_saveGR")
        self.verticalLayout_3.addWidget(self.pushButton_saveGR)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 4, 2, 1, 1)
        self.graphicsView_gr = GofRView(self.tab_gR)
        self.graphicsView_gr.setMinimumSize(QtCore.QSize(50, 300))
        self.graphicsView_gr.setObjectName("graphicsView_gr")
        self.gridLayout_5.addWidget(self.graphicsView_gr, 4, 0, 1, 1)
        self.graphicsView_sq = SofQView(self.tab_gR)
        self.graphicsView_sq.setMinimumSize(QtCore.QSize(50, 300))
        self.graphicsView_sq.setObjectName("graphicsView_sq")
        self.gridLayout_5.addWidget(self.graphicsView_sq, 0, 0, 1, 2)
        self.graphicsView_sq.raise_()
        self.graphicsView_gr.raise_()
        self.tabWidget.addTab(self.tab_gR, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_ipython = IPythonDockWidget(MainWindow)
        self.dockWidget_ipython.setMinimumSize(QtCore.QSize(50, 36))
        self.dockWidget_ipython.setMaximumSize(QtCore.QSize(524287, 300))
        self.dockWidget_ipython.setObjectName("dockWidget_ipython")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget_ipython.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_ipython)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionShow_Cheat_Sheet = QtWidgets.QAction(MainWindow)
        self.actionShow_Cheat_Sheet.setObjectName("actionShow_Cheat_Sheet")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionShow_Cheat_Sheet)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.diamond.editingFinished.connect(MainWindow.diamond_edited)
        self.diamond_background.editingFinished.connect(MainWindow.diamond_background_edited)
        self.vanadium.editingFinished.connect(MainWindow.vanadium_edited)
        self.vanadium_background.editingFinished.connect(MainWindow.vanadium_background_edited)
        self.sample_background.editingFinished.connect(MainWindow.sample_background_edited)
        self.auto_manual_folder.clicked.connect(MainWindow.output_folder_radio_buttons)
        self.manual_output_folder.clicked.connect(MainWindow.output_folder_radio_buttons)
        self.manual_output_folder_field.editingFinished.connect(MainWindow.manual_output_folder_field_edited)
        self.run_autonom_script.clicked.connect(MainWindow.run_autonom)
        self.table.customContextMenuRequested['QPoint'].connect(MainWindow.table_right_click)
        self.run_ndabs_button.clicked.connect(MainWindow.run_ndabs_clicked)
        self.populate_table.clicked.connect(MainWindow.populate_table_clicked)
        self.plazcek_fit_range_min.editingFinished.connect(MainWindow.check_plazcek_widgets)
        self.plazcek_fit_range_max.editingFinished.connect(MainWindow.check_plazcek_widgets)
        self.hydrogen_yes.clicked.connect(MainWindow.hidrogen_clicked)
        self.hydrogen_no.clicked.connect(MainWindow.no_hidrogen_clicked)
        self.fourier_filter_from.editingFinished.connect(MainWindow.check_fourier_filter_widgets)
        self.fourier_filter_to.editingFinished.connect(MainWindow.check_fourier_filter_widgets)
        self.create_sample_properties_files_button.clicked.connect(MainWindow.create_sample_properties_files_clicked)
        self.background_yes.clicked.connect(MainWindow.yes_background_clicked)
        self.background_comboBox.currentIndexChanged['int'].connect(MainWindow.background_combobox_changed)
        self.move_to_button.clicked.connect(MainWindow.move_to_folder_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.diamond, self.diamond_background)
        MainWindow.setTabOrder(self.diamond_background, self.vanadium)
        MainWindow.setTabOrder(self.vanadium, self.vanadium_background)
        MainWindow.setTabOrder(self.vanadium_background, self.sample_background)
        MainWindow.setTabOrder(self.sample_background, self.first_scan)
        MainWindow.setTabOrder(self.first_scan, self.last_scan)
        MainWindow.setTabOrder(self.last_scan, self.frequency)
        MainWindow.setTabOrder(self.frequency, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.renormalization_yes)
        MainWindow.setTabOrder(self.renormalization_yes, self.radioButton_11)
        MainWindow.setTabOrder(self.radioButton_11, self.autotemplate_yes)
        MainWindow.setTabOrder(self.autotemplate_yes, self.radioButton_13)
        MainWindow.setTabOrder(self.radioButton_13, self.comments)
        MainWindow.setTabOrder(self.comments, self.run_autonom_script)
        MainWindow.setTabOrder(self.run_autonom_script, self.auto_manual_folder)
        MainWindow.setTabOrder(self.auto_manual_folder, self.manual_output_folder)
        MainWindow.setTabOrder(self.manual_output_folder, self.manual_output_folder_field)
        MainWindow.setTabOrder(self.manual_output_folder_field, self.table)
        MainWindow.setTabOrder(self.table, self.background_no)
        MainWindow.setTabOrder(self.background_no, self.background_yes)
        MainWindow.setTabOrder(self.background_yes, self.background_comboBox)
        MainWindow.setTabOrder(self.background_comboBox, self.background_line_edit)
        MainWindow.setTabOrder(self.background_line_edit, self.fourier_filter_from)
        MainWindow.setTabOrder(self.fourier_filter_from, self.fourier_filter_to)
        MainWindow.setTabOrder(self.fourier_filter_to, self.hydrogen_yes)
        MainWindow.setTabOrder(self.hydrogen_yes, self.hydrogen_no)
        MainWindow.setTabOrder(self.hydrogen_no, self.plazcek_fit_range_min)
        MainWindow.setTabOrder(self.plazcek_fit_range_min, self.plazcek_fit_range_max)
        MainWindow.setTabOrder(self.plazcek_fit_range_max, self.muscat_yes)
        MainWindow.setTabOrder(self.muscat_yes, self.radioButton_14)
        MainWindow.setTabOrder(self.radioButton_14, self.scale_data_yes)
        MainWindow.setTabOrder(self.scale_data_yes, self.radioButton_15)
        MainWindow.setTabOrder(self.radioButton_15, self.run_rmc_yes)
        MainWindow.setTabOrder(self.run_rmc_yes, self.radioButton_16)
        MainWindow.setTabOrder(self.radioButton_16, self.create_sample_properties_files_button)
        MainWindow.setTabOrder(self.create_sample_properties_files_button, self.run_ndabs_button)
        MainWindow.setTabOrder(self.run_ndabs_button, self.graphicsView_bragg)
        MainWindow.setTabOrder(self.graphicsView_bragg, self.pushButton_loadBraggFile)
        MainWindow.setTabOrder(self.pushButton_loadBraggFile, self.treeWidget_braggWSList)
        MainWindow.setTabOrder(self.treeWidget_braggWSList, self.checkBox_bank1)
        MainWindow.setTabOrder(self.checkBox_bank1, self.checkBox_bank2)
        MainWindow.setTabOrder(self.checkBox_bank2, self.checkBox_bank3)
        MainWindow.setTabOrder(self.checkBox_bank3, self.checkBox_bank4)
        MainWindow.setTabOrder(self.checkBox_bank4, self.checkBox_bank5)
        MainWindow.setTabOrder(self.checkBox_bank5, self.checkBox_bank6)
        MainWindow.setTabOrder(self.checkBox_bank6, self.radioButton_multiBank)
        MainWindow.setTabOrder(self.radioButton_multiBank, self.radioButton_multiGSS)
        MainWindow.setTabOrder(self.radioButton_multiGSS, self.comboBox_xUnit)
        MainWindow.setTabOrder(self.comboBox_xUnit, self.pushButton_combineBanks)
        MainWindow.setTabOrder(self.pushButton_combineBanks, self.graphicsView_sq)
        MainWindow.setTabOrder(self.graphicsView_sq, self.graphicsView_gr)
        MainWindow.setTabOrder(self.graphicsView_gr, self.pushButton_loadSQ)
        MainWindow.setTabOrder(self.pushButton_loadSQ, self.radioButton_sq)
        MainWindow.setTabOrder(self.radioButton_sq, self.radioButton_sqm1)
        MainWindow.setTabOrder(self.radioButton_sqm1, self.radioButton_qsqm1)
        MainWindow.setTabOrder(self.radioButton_qsqm1, self.doubleSpinBoxQmin)
        MainWindow.setTabOrder(self.doubleSpinBoxQmin, self.doubleSpinBoxQmax)
        MainWindow.setTabOrder(self.doubleSpinBoxQmax, self.pushButton_showQMinMax)
        MainWindow.setTabOrder(self.pushButton_showQMinMax, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.pushButton_generateGR)
        MainWindow.setTabOrder(self.pushButton_generateGR, self.treeWidget_grWsList)
        MainWindow.setTabOrder(self.treeWidget_grWsList, self.doubleSpinBoxRmin)
        MainWindow.setTabOrder(self.doubleSpinBoxRmin, self.doubleSpinBoxDelR)
        MainWindow.setTabOrder(self.doubleSpinBoxDelR, self.doubleSpinBoxRmax)
        MainWindow.setTabOrder(self.doubleSpinBoxRmax, self.pushButton_clearGrCanvas)
        MainWindow.setTabOrder(self.pushButton_clearGrCanvas, self.pushButton_saveGR)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Scan Numbers  (ex: 1234, 1300-1305, 1310)"))
        self.label_8.setText(_translate("MainWindow", "*"))
        self.label_7.setText(_translate("MainWindow", "Vanadium background"))
        self.label.setText(_translate("MainWindow", "Diamond"))
        self.label_5.setText(_translate("MainWindow", "Vanadium"))
        self.label_4.setText(_translate("MainWindow", "*"))
        self.label_6.setText(_translate("MainWindow", "*"))
        self.label_9.setText(_translate("MainWindow", "*"))
        self.label_10.setText(_translate("MainWindow", "*"))
        self.label_11.setText(_translate("MainWindow", "Diamond background"))
        self.label_12.setText(_translate("MainWindow", "Sample background"))
        self.label_21.setText(_translate("MainWindow", "*"))
        self.label_22.setText(_translate("MainWindow", ": Mandatory field"))
        self.label_18.setText(_translate("MainWindow", "First scan to be analyzed"))
        self.label_20.setText(_translate("MainWindow", "Frequency (Hz)"))
        self.label_19.setText(_translate("MainWindow", "Last scan to be analyzed"))
        self.frequency.setItemText(0, _translate("MainWindow", "60"))
        self.frequency.setItemText(1, _translate("MainWindow", "30"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Recalibration"))
        self.recalibration_yes.setText(_translate("MainWindow", "yes"))
        self.radioButton_3.setText(_translate("MainWindow", "No"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Renormalization"))
        self.renormalization_yes.setText(_translate("MainWindow", "Yes"))
        self.radioButton_11.setText(_translate("MainWindow", "No"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Autotemplate"))
        self.autotemplate_yes.setText(_translate("MainWindow", "Yes"))
        self.radioButton_13.setText(_translate("MainWindow", "No"))
        self.label_14.setText(_translate("MainWindow", "Comments:"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Name of Output Folder"))
        self.auto_manual_folder.setText(_translate("MainWindow", "Automatic (autoNOM_##)"))
        self.manual_output_folder.setText(_translate("MainWindow", "Manual"))
        self.run_autonom_script.setText(_translate("MainWindow", "Run autoNOM script"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "autoNOM"))
        self.move_to_button.setText(_translate("MainWindow", "Move to Folder ..."))
        self.label_13.setText(_translate("MainWindow", "Current folder:"))
        self.current_folder_label.setText(_translate("MainWindow", "N/A"))
        self.populate_table.setText(_translate("MainWindow", "Populate Table"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Select"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Runs"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sample Formula"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mass Density (g/cc)"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Radius (cm)"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Packing Fraction"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sample Shape"))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Do Abs. Corr. ?"))
        self.label_29.setText(_translate("MainWindow", "Sample formula example: H 2 O 1, 2H 2 O 1, 238U 1 O 2"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Background"))
        self.background_no.setText(_translate("MainWindow", "No"))
        self.background_no_field.setText(_translate("MainWindow", "N/A"))
        self.label_15.setText(_translate("MainWindow", "(from exp.ini file)"))
        self.background_yes.setText(_translate("MainWindow", "Yes"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Fourier Filter (ex: 1.5, 50)"))
        self.fourier_filter_from.setText(_translate("MainWindow", "1.5"))
        self.label_16.setText(_translate("MainWindow", "*"))
        self.label_17.setText(_translate("MainWindow", ","))
        self.fourier_filter_to.setText(_translate("MainWindow", "50"))
        self.label_23.setText(_translate("MainWindow", "*"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Plazcek"))
        self.label_24.setText(_translate("MainWindow", "Type"))
        self.hydrogen_yes.setText(_translate("MainWindow", "hydrogen"))
        self.hydrogen_no.setText(_translate("MainWindow", "no hydrogren"))
        self.label_25.setText(_translate("MainWindow", "Fit Range"))
        self.plazcek_fit_range_min.setText(_translate("MainWindow", "10"))
        self.label_26.setText(_translate("MainWindow", "*"))
        self.label_27.setText(_translate("MainWindow", ","))
        self.plazcek_fit_range_max.setText(_translate("MainWindow", "50"))
        self.label_28.setText(_translate("MainWindow", "*"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Muscat"))
        self.muscat_yes.setText(_translate("MainWindow", "Yes"))
        self.radioButton_14.setText(_translate("MainWindow", "No"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Scale Data"))
        self.scale_data_yes.setText(_translate("MainWindow", "Yes"))
        self.radioButton_15.setText(_translate("MainWindow", "No"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Run RMC"))
        self.run_rmc_yes.setText(_translate("MainWindow", "Yes"))
        self.radioButton_16.setText(_translate("MainWindow", "No"))
        self.label_30.setText(_translate("MainWindow", "*"))
        self.label_31.setText(_translate("MainWindow", ": Mandatory field"))
        self.create_sample_properties_files_button.setText(_translate("MainWindow", "Create Sample Properties Files"))
        self.run_ndabs_button.setText(_translate("MainWindow", "Run NDabs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "NDabs"))
        self.label_3.setText(_translate("MainWindow", "SNS Powder Reduction Configuration for NOMAD"))
        self.comboBox_xUnit.setItemText(0, _translate("MainWindow", "TOF"))
        self.comboBox_xUnit.setItemText(1, _translate("MainWindow", "d-Spacing"))
        self.comboBox_xUnit.setItemText(2, _translate("MainWindow", "Q"))
        self.pushButton_combineBanks.setToolTip(_translate("MainWindow", "<html><head/><body><p>Combine banks back to a 6-bank GSAS file</p></body></html>"))
        self.pushButton_combineBanks.setText(_translate("MainWindow", "Combine to GSAS"))
        self.pushButton_loadBraggFile.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load GSS/S(Q)/general 3-column ASCII</p><p>1. GSS: load and then split to 6 workspaces with single spectrum.  Finally group all 6 workspaces to a workspace group</p></body></html>"))
        self.pushButton_loadBraggFile.setText(_translate("MainWindow", "Load"))
        self.checkBox_bank1.setText(_translate("MainWindow", "Bank 1"))
        self.checkBox_bank2.setText(_translate("MainWindow", "Bank 2"))
        self.checkBox_bank3.setText(_translate("MainWindow", "Bank 3"))
        self.checkBox_bank4.setText(_translate("MainWindow", "Bank 4"))
        self.checkBox_bank5.setText(_translate("MainWindow", "Bank 5"))
        self.checkBox_bank6.setText(_translate("MainWindow", "Bank 6"))
        self.radioButton_multiBank.setText(_translate("MainWindow", "Multiple Banks"))
        self.radioButton_multiGSS.setText(_translate("MainWindow", "Multiple GSS"))
        self.treeWidget_braggWSList.setToolTip(_translate("MainWindow", "<html><head/><body><p>List of workspace names.  Each workspace is an individual bank</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bragg), _translate("MainWindow", "Bragg Peaks"))
        self.pushButton_loadSQ.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load S(Q) from the reduction tab. Plot S(Q), S(Q)-1 or Q[S(Q)-1] according to the selected radio buttons below.</p><p><span style=\" font-weight:600;\">Use regular file loader at this phase.</span></p><p>Duplicate the function in FastGR/scripts/addie</p><p>149     def read_SQ_file(self):</p><p><br/></p></body></html>"))
        self.pushButton_loadSQ.setText(_translate("MainWindow", "Load SQ"))
        self.radioButton_sq.setText(_translate("MainWindow", "S(Q)"))
        self.radioButton_sqm1.setText(_translate("MainWindow", "S(Q)-1"))
        self.radioButton_qsqm1.setText(_translate("MainWindow", "Q[S(Q)-1]"))
        self.labelQmax.setText(_translate("MainWindow", "Qmax"))
        self.labelQmin.setText(_translate("MainWindow", "Qmin"))
        self.label_2.setText(_translate("MainWindow", "More Options ..."))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_showQMinMax.setToolTip(_translate("MainWindow", "<html><head/><body><p>Show or hide the vertical indicators for Qmin and Qmax</p></body></html>"))
        self.pushButton_showQMinMax.setText(_translate("MainWindow", "Show Min/Max"))
        self.pushButton_generateGR.setText(_translate("MainWindow", "Generate GR"))
        self.treeWidget_grWsList.setToolTip(_translate("MainWindow", "<html><head/><body><p>write click on the workspace name should give user the option to plot/over plot </p></body></html>"))
        self.labelRmin.setText(_translate("MainWindow", "Rmin"))
        self.labeldelR.setText(_translate("MainWindow", "deltaR"))
        self.labelRmax.setText(_translate("MainWindow", "Rmax"))
        self.pushButton_clearGrCanvas.setText(_translate("MainWindow", "Clear Canvas"))
        self.pushButton_saveGR.setText(_translate("MainWindow", "Save GR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gR), _translate("MainWindow", "Calculate G(R)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionShow_Cheat_Sheet.setText(_translate("MainWindow", "Show Cheat Sheet"))

from graphicviewlib import BraggView, GofRView, SofQView
from ipythondockwidget import IPythonDockWidget
from treelib import BraggTree, GofRTree
