# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_periodic_table.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1060, 560)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ba = QtGui.QPushButton(self.centralwidget)
        self.ba.setMinimumSize(QtCore.QSize(52, 52))
        self.ba.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ba.setFont(font)
        self.ba.setObjectName(_fromUtf8("ba"))
        self.gridLayout.addWidget(self.ba, 5, 1, 1, 1)
        self.ti = QtGui.QPushButton(self.centralwidget)
        self.ti.setMinimumSize(QtCore.QSize(52, 52))
        self.ti.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ti.setFont(font)
        self.ti.setObjectName(_fromUtf8("ti"))
        self.gridLayout.addWidget(self.ti, 3, 3, 1, 1)
        self.si = QtGui.QPushButton(self.centralwidget)
        self.si.setMinimumSize(QtCore.QSize(52, 52))
        self.si.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.si.setFont(font)
        self.si.setObjectName(_fromUtf8("si"))
        self.gridLayout.addWidget(self.si, 2, 13, 1, 1)
        self.k = QtGui.QPushButton(self.centralwidget)
        self.k.setMinimumSize(QtCore.QSize(52, 52))
        self.k.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.k.setFont(font)
        self.k.setObjectName(_fromUtf8("k"))
        self.gridLayout.addWidget(self.k, 3, 0, 1, 1)
        self.p = QtGui.QPushButton(self.centralwidget)
        self.p.setMinimumSize(QtCore.QSize(52, 52))
        self.p.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.p.setFont(font)
        self.p.setObjectName(_fromUtf8("p"))
        self.gridLayout.addWidget(self.p, 2, 14, 1, 1)
        self.b = QtGui.QPushButton(self.centralwidget)
        self.b.setMinimumSize(QtCore.QSize(52, 52))
        self.b.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b.setFont(font)
        self.b.setObjectName(_fromUtf8("b"))
        self.gridLayout.addWidget(self.b, 1, 12, 1, 1)
        self.cl = QtGui.QPushButton(self.centralwidget)
        self.cl.setMinimumSize(QtCore.QSize(52, 52))
        self.cl.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cl.setFont(font)
        self.cl.setObjectName(_fromUtf8("cl"))
        self.gridLayout.addWidget(self.cl, 2, 16, 1, 1)
        self.al = QtGui.QPushButton(self.centralwidget)
        self.al.setMinimumSize(QtCore.QSize(52, 52))
        self.al.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.al.setFont(font)
        self.al.setObjectName(_fromUtf8("al"))
        self.gridLayout.addWidget(self.al, 2, 12, 1, 1)
        self.sc = QtGui.QPushButton(self.centralwidget)
        self.sc.setMinimumSize(QtCore.QSize(52, 52))
        self.sc.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sc.setFont(font)
        self.sc.setObjectName(_fromUtf8("sc"))
        self.gridLayout.addWidget(self.sc, 3, 2, 1, 1)
        self.ne = QtGui.QPushButton(self.centralwidget)
        self.ne.setMinimumSize(QtCore.QSize(52, 52))
        self.ne.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ne.setFont(font)
        self.ne.setObjectName(_fromUtf8("ne"))
        self.gridLayout.addWidget(self.ne, 1, 17, 1, 1)
        self.ca = QtGui.QPushButton(self.centralwidget)
        self.ca.setMinimumSize(QtCore.QSize(52, 52))
        self.ca.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ca.setFont(font)
        self.ca.setObjectName(_fromUtf8("ca"))
        self.gridLayout.addWidget(self.ca, 3, 1, 1, 1)
        self.ni = QtGui.QPushButton(self.centralwidget)
        self.ni.setMinimumSize(QtCore.QSize(52, 52))
        self.ni.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ni.setFont(font)
        self.ni.setObjectName(_fromUtf8("ni"))
        self.gridLayout.addWidget(self.ni, 3, 9, 1, 1)
        self.s = QtGui.QPushButton(self.centralwidget)
        self.s.setMinimumSize(QtCore.QSize(52, 52))
        self.s.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.s.setFont(font)
        self.s.setObjectName(_fromUtf8("s"))
        self.gridLayout.addWidget(self.s, 2, 15, 1, 1)
        self.mg = QtGui.QPushButton(self.centralwidget)
        self.mg.setMinimumSize(QtCore.QSize(52, 52))
        self.mg.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mg.setFont(font)
        self.mg.setObjectName(_fromUtf8("mg"))
        self.gridLayout.addWidget(self.mg, 2, 1, 1, 1)
        self.i = QtGui.QPushButton(self.centralwidget)
        self.i.setMinimumSize(QtCore.QSize(52, 52))
        self.i.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.i.setFont(font)
        self.i.setObjectName(_fromUtf8("i"))
        self.gridLayout.addWidget(self.i, 4, 16, 1, 1)
        self.be = QtGui.QPushButton(self.centralwidget)
        self.be.setMinimumSize(QtCore.QSize(52, 52))
        self.be.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.be.setFont(font)
        self.be.setObjectName(_fromUtf8("be"))
        self.gridLayout.addWidget(self.be, 1, 1, 1, 1)
        self.kr = QtGui.QPushButton(self.centralwidget)
        self.kr.setMinimumSize(QtCore.QSize(52, 52))
        self.kr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.kr.setFont(font)
        self.kr.setObjectName(_fromUtf8("kr"))
        self.gridLayout.addWidget(self.kr, 3, 17, 1, 1)
        self.fe = QtGui.QPushButton(self.centralwidget)
        self.fe.setMinimumSize(QtCore.QSize(52, 52))
        self.fe.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fe.setFont(font)
        self.fe.setObjectName(_fromUtf8("fe"))
        self.gridLayout.addWidget(self.fe, 3, 7, 1, 1)
        self.br = QtGui.QPushButton(self.centralwidget)
        self.br.setMinimumSize(QtCore.QSize(52, 52))
        self.br.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.br.setFont(font)
        self.br.setObjectName(_fromUtf8("br"))
        self.gridLayout.addWidget(self.br, 3, 16, 1, 1)
        self.h = QtGui.QPushButton(self.centralwidget)
        self.h.setMinimumSize(QtCore.QSize(52, 52))
        self.h.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.h.setFont(font)
        self.h.setObjectName(_fromUtf8("h"))
        self.gridLayout.addWidget(self.h, 0, 0, 1, 1)
        self.co = QtGui.QPushButton(self.centralwidget)
        self.co.setMinimumSize(QtCore.QSize(52, 52))
        self.co.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.co.setFont(font)
        self.co.setObjectName(_fromUtf8("co"))
        self.gridLayout.addWidget(self.co, 3, 8, 1, 1)
        self.ge = QtGui.QPushButton(self.centralwidget)
        self.ge.setMinimumSize(QtCore.QSize(52, 52))
        self.ge.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ge.setFont(font)
        self.ge.setObjectName(_fromUtf8("ge"))
        self.gridLayout.addWidget(self.ge, 3, 13, 1, 1)
        self.zn = QtGui.QPushButton(self.centralwidget)
        self.zn.setMinimumSize(QtCore.QSize(52, 52))
        self.zn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zn.setFont(font)
        self.zn.setObjectName(_fromUtf8("zn"))
        self.gridLayout.addWidget(self.zn, 3, 11, 1, 1)
        self.v = QtGui.QPushButton(self.centralwidget)
        self.v.setMinimumSize(QtCore.QSize(52, 52))
        self.v.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.v.setFont(font)
        self.v.setObjectName(_fromUtf8("v"))
        self.gridLayout.addWidget(self.v, 3, 4, 1, 1)
        self.na = QtGui.QPushButton(self.centralwidget)
        self.na.setMinimumSize(QtCore.QSize(52, 52))
        self.na.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.na.setFont(font)
        self.na.setObjectName(_fromUtf8("na"))
        self.gridLayout.addWidget(self.na, 2, 0, 1, 1)
        self.cr = QtGui.QPushButton(self.centralwidget)
        self.cr.setMinimumSize(QtCore.QSize(52, 52))
        self.cr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cr.setFont(font)
        self.cr.setObjectName(_fromUtf8("cr"))
        self.gridLayout.addWidget(self.cr, 3, 5, 1, 1)
        self.mn = QtGui.QPushButton(self.centralwidget)
        self.mn.setMinimumSize(QtCore.QSize(52, 52))
        self.mn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mn.setFont(font)
        self.mn.setObjectName(_fromUtf8("mn"))
        self.gridLayout.addWidget(self.mn, 3, 6, 1, 1)
        self.ar = QtGui.QPushButton(self.centralwidget)
        self.ar.setMinimumSize(QtCore.QSize(52, 52))
        self.ar.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ar.setFont(font)
        self.ar.setObjectName(_fromUtf8("ar"))
        self.gridLayout.addWidget(self.ar, 2, 17, 1, 1)
        self.ga = QtGui.QPushButton(self.centralwidget)
        self.ga.setMinimumSize(QtCore.QSize(52, 52))
        self.ga.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ga.setFont(font)
        self.ga.setObjectName(_fromUtf8("ga"))
        self.gridLayout.addWidget(self.ga, 3, 12, 1, 1)
        self.li = QtGui.QPushButton(self.centralwidget)
        self.li.setMinimumSize(QtCore.QSize(52, 52))
        self.li.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.li.setFont(font)
        self.li.setObjectName(_fromUtf8("li"))
        self.gridLayout.addWidget(self.li, 1, 0, 1, 1)
        self.he = QtGui.QPushButton(self.centralwidget)
        self.he.setMinimumSize(QtCore.QSize(52, 52))
        self.he.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.he.setFont(font)
        self.he.setObjectName(_fromUtf8("he"))
        self.gridLayout.addWidget(self.he, 0, 17, 1, 1)
        self.cu = QtGui.QPushButton(self.centralwidget)
        self.cu.setMinimumSize(QtCore.QSize(52, 52))
        self.cu.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cu.setFont(font)
        self.cu.setObjectName(_fromUtf8("cu"))
        self.gridLayout.addWidget(self.cu, 3, 10, 1, 1)
        self.c = QtGui.QPushButton(self.centralwidget)
        self.c.setMinimumSize(QtCore.QSize(52, 52))
        self.c.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.c.setFont(font)
        self.c.setObjectName(_fromUtf8("c"))
        self.gridLayout.addWidget(self.c, 1, 13, 1, 1)
        self.o = QtGui.QPushButton(self.centralwidget)
        self.o.setMinimumSize(QtCore.QSize(52, 52))
        self.o.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.o.setFont(font)
        self.o.setObjectName(_fromUtf8("o"))
        self.gridLayout.addWidget(self.o, 1, 15, 1, 1)
        self.f = QtGui.QPushButton(self.centralwidget)
        self.f.setMinimumSize(QtCore.QSize(52, 52))
        self.f.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.f.setFont(font)
        self.f.setObjectName(_fromUtf8("f"))
        self.gridLayout.addWidget(self.f, 1, 16, 1, 1)
        self.hf = QtGui.QPushButton(self.centralwidget)
        self.hf.setMinimumSize(QtCore.QSize(52, 52))
        self.hf.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hf.setFont(font)
        self.hf.setObjectName(_fromUtf8("hf"))
        self.gridLayout.addWidget(self.hf, 5, 3, 1, 1)
        self.lu = QtGui.QPushButton(self.centralwidget)
        self.lu.setMinimumSize(QtCore.QSize(52, 52))
        self.lu.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lu.setFont(font)
        self.lu.setObjectName(_fromUtf8("lu"))
        self.gridLayout.addWidget(self.lu, 5, 2, 1, 1)
        self.nb = QtGui.QPushButton(self.centralwidget)
        self.nb.setMinimumSize(QtCore.QSize(52, 52))
        self.nb.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nb.setFont(font)
        self.nb.setObjectName(_fromUtf8("nb"))
        self.gridLayout.addWidget(self.nb, 4, 4, 1, 1)
        self.se = QtGui.QPushButton(self.centralwidget)
        self.se.setMinimumSize(QtCore.QSize(52, 52))
        self.se.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.se.setFont(font)
        self.se.setObjectName(_fromUtf8("se"))
        self.gridLayout.addWidget(self.se, 3, 15, 1, 1)
        self.arsenic = QtGui.QPushButton(self.centralwidget)
        self.arsenic.setMinimumSize(QtCore.QSize(52, 52))
        self.arsenic.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.arsenic.setFont(font)
        self.arsenic.setObjectName(_fromUtf8("arsenic"))
        self.gridLayout.addWidget(self.arsenic, 3, 14, 1, 1)
        self.ag = QtGui.QPushButton(self.centralwidget)
        self.ag.setMinimumSize(QtCore.QSize(52, 52))
        self.ag.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ag.setFont(font)
        self.ag.setObjectName(_fromUtf8("ag"))
        self.gridLayout.addWidget(self.ag, 4, 10, 1, 1)
        self.sr = QtGui.QPushButton(self.centralwidget)
        self.sr.setMinimumSize(QtCore.QSize(52, 52))
        self.sr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sr.setFont(font)
        self.sr.setObjectName(_fromUtf8("sr"))
        self.gridLayout.addWidget(self.sr, 4, 1, 1, 1)
        self.zr = QtGui.QPushButton(self.centralwidget)
        self.zr.setMinimumSize(QtCore.QSize(52, 52))
        self.zr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zr.setFont(font)
        self.zr.setObjectName(_fromUtf8("zr"))
        self.gridLayout.addWidget(self.zr, 4, 3, 1, 1)
        self.rb = QtGui.QPushButton(self.centralwidget)
        self.rb.setMinimumSize(QtCore.QSize(52, 52))
        self.rb.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rb.setFont(font)
        self.rb.setObjectName(_fromUtf8("rb"))
        self.gridLayout.addWidget(self.rb, 4, 0, 1, 1)
        self.og = QtGui.QPushButton(self.centralwidget)
        self.og.setMinimumSize(QtCore.QSize(52, 52))
        self.og.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.og.setFont(font)
        self.og.setObjectName(_fromUtf8("og"))
        self.gridLayout.addWidget(self.og, 6, 17, 1, 1)
        self.ts = QtGui.QPushButton(self.centralwidget)
        self.ts.setMinimumSize(QtCore.QSize(52, 52))
        self.ts.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ts.setFont(font)
        self.ts.setObjectName(_fromUtf8("ts"))
        self.gridLayout.addWidget(self.ts, 6, 16, 1, 1)
        self.lv = QtGui.QPushButton(self.centralwidget)
        self.lv.setMinimumSize(QtCore.QSize(52, 52))
        self.lv.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lv.setFont(font)
        self.lv.setObjectName(_fromUtf8("lv"))
        self.gridLayout.addWidget(self.lv, 6, 15, 1, 1)
        self.mc = QtGui.QPushButton(self.centralwidget)
        self.mc.setMinimumSize(QtCore.QSize(52, 52))
        self.mc.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mc.setFont(font)
        self.mc.setObjectName(_fromUtf8("mc"))
        self.gridLayout.addWidget(self.mc, 6, 14, 1, 1)
        self.cd = QtGui.QPushButton(self.centralwidget)
        self.cd.setMinimumSize(QtCore.QSize(52, 52))
        self.cd.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cd.setFont(font)
        self.cd.setObjectName(_fromUtf8("cd"))
        self.gridLayout.addWidget(self.cd, 4, 11, 1, 1)
        self.fl = QtGui.QPushButton(self.centralwidget)
        self.fl.setMinimumSize(QtCore.QSize(52, 52))
        self.fl.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fl.setFont(font)
        self.fl.setObjectName(_fromUtf8("fl"))
        self.gridLayout.addWidget(self.fl, 6, 13, 1, 1)
        self.nh = QtGui.QPushButton(self.centralwidget)
        self.nh.setMinimumSize(QtCore.QSize(52, 52))
        self.nh.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nh.setFont(font)
        self.nh.setObjectName(_fromUtf8("nh"))
        self.gridLayout.addWidget(self.nh, 6, 12, 1, 1)
        self.cs = QtGui.QPushButton(self.centralwidget)
        self.cs.setMinimumSize(QtCore.QSize(52, 52))
        self.cs.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cs.setFont(font)
        self.cs.setObjectName(_fromUtf8("cs"))
        self.gridLayout.addWidget(self.cs, 5, 0, 1, 1)
        self.cn = QtGui.QPushButton(self.centralwidget)
        self.cn.setMinimumSize(QtCore.QSize(52, 52))
        self.cn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cn.setFont(font)
        self.cn.setObjectName(_fromUtf8("cn"))
        self.gridLayout.addWidget(self.cn, 6, 11, 1, 1)
        self.rg = QtGui.QPushButton(self.centralwidget)
        self.rg.setMinimumSize(QtCore.QSize(52, 52))
        self.rg.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rg.setFont(font)
        self.rg.setObjectName(_fromUtf8("rg"))
        self.gridLayout.addWidget(self.rg, 6, 10, 1, 1)
        self.ru = QtGui.QPushButton(self.centralwidget)
        self.ru.setMinimumSize(QtCore.QSize(52, 52))
        self.ru.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ru.setFont(font)
        self.ru.setObjectName(_fromUtf8("ru"))
        self.gridLayout.addWidget(self.ru, 4, 7, 1, 1)
        self.ds = QtGui.QPushButton(self.centralwidget)
        self.ds.setMinimumSize(QtCore.QSize(52, 52))
        self.ds.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ds.setFont(font)
        self.ds.setObjectName(_fromUtf8("ds"))
        self.gridLayout.addWidget(self.ds, 6, 9, 1, 1)
        self.mt = QtGui.QPushButton(self.centralwidget)
        self.mt.setMinimumSize(QtCore.QSize(52, 52))
        self.mt.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mt.setFont(font)
        self.mt.setObjectName(_fromUtf8("mt"))
        self.gridLayout.addWidget(self.mt, 6, 8, 1, 1)
        self.indium = QtGui.QPushButton(self.centralwidget)
        self.indium.setMinimumSize(QtCore.QSize(52, 52))
        self.indium.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.indium.setFont(font)
        self.indium.setObjectName(_fromUtf8("indium"))
        self.gridLayout.addWidget(self.indium, 4, 12, 1, 1)
        self.hs = QtGui.QPushButton(self.centralwidget)
        self.hs.setMinimumSize(QtCore.QSize(52, 52))
        self.hs.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hs.setFont(font)
        self.hs.setObjectName(_fromUtf8("hs"))
        self.gridLayout.addWidget(self.hs, 6, 7, 1, 1)
        self.bh = QtGui.QPushButton(self.centralwidget)
        self.bh.setMinimumSize(QtCore.QSize(52, 52))
        self.bh.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bh.setFont(font)
        self.bh.setObjectName(_fromUtf8("bh"))
        self.gridLayout.addWidget(self.bh, 6, 6, 1, 1)
        self.te = QtGui.QPushButton(self.centralwidget)
        self.te.setMinimumSize(QtCore.QSize(52, 52))
        self.te.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.te.setFont(font)
        self.te.setObjectName(_fromUtf8("te"))
        self.gridLayout.addWidget(self.te, 4, 15, 1, 1)
        self.sg = QtGui.QPushButton(self.centralwidget)
        self.sg.setMinimumSize(QtCore.QSize(52, 52))
        self.sg.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sg.setFont(font)
        self.sg.setObjectName(_fromUtf8("sg"))
        self.gridLayout.addWidget(self.sg, 6, 5, 1, 1)
        self.db = QtGui.QPushButton(self.centralwidget)
        self.db.setMinimumSize(QtCore.QSize(52, 52))
        self.db.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.db.setFont(font)
        self.db.setObjectName(_fromUtf8("db"))
        self.gridLayout.addWidget(self.db, 6, 4, 1, 1)
        self.mo = QtGui.QPushButton(self.centralwidget)
        self.mo.setMinimumSize(QtCore.QSize(52, 52))
        self.mo.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mo.setFont(font)
        self.mo.setObjectName(_fromUtf8("mo"))
        self.gridLayout.addWidget(self.mo, 4, 5, 1, 1)
        self.rf = QtGui.QPushButton(self.centralwidget)
        self.rf.setMinimumSize(QtCore.QSize(52, 52))
        self.rf.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rf.setFont(font)
        self.rf.setObjectName(_fromUtf8("rf"))
        self.gridLayout.addWidget(self.rf, 6, 3, 1, 1)
        self.lr = QtGui.QPushButton(self.centralwidget)
        self.lr.setMinimumSize(QtCore.QSize(52, 52))
        self.lr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lr.setFont(font)
        self.lr.setObjectName(_fromUtf8("lr"))
        self.gridLayout.addWidget(self.lr, 6, 2, 1, 1)
        self.xe = QtGui.QPushButton(self.centralwidget)
        self.xe.setMinimumSize(QtCore.QSize(52, 52))
        self.xe.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.xe.setFont(font)
        self.xe.setObjectName(_fromUtf8("xe"))
        self.gridLayout.addWidget(self.xe, 4, 17, 1, 1)
        self.ra = QtGui.QPushButton(self.centralwidget)
        self.ra.setMinimumSize(QtCore.QSize(52, 52))
        self.ra.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ra.setFont(font)
        self.ra.setObjectName(_fromUtf8("ra"))
        self.gridLayout.addWidget(self.ra, 6, 1, 1, 1)
        self.fr = QtGui.QPushButton(self.centralwidget)
        self.fr.setMinimumSize(QtCore.QSize(52, 52))
        self.fr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fr.setFont(font)
        self.fr.setObjectName(_fromUtf8("fr"))
        self.gridLayout.addWidget(self.fr, 6, 0, 1, 1)
        self.rn = QtGui.QPushButton(self.centralwidget)
        self.rn.setMinimumSize(QtCore.QSize(52, 52))
        self.rn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rn.setFont(font)
        self.rn.setObjectName(_fromUtf8("rn"))
        self.gridLayout.addWidget(self.rn, 5, 17, 1, 1)
        self.at = QtGui.QPushButton(self.centralwidget)
        self.at.setMinimumSize(QtCore.QSize(52, 52))
        self.at.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.at.setFont(font)
        self.at.setObjectName(_fromUtf8("at"))
        self.gridLayout.addWidget(self.at, 5, 16, 1, 1)
        self.sb = QtGui.QPushButton(self.centralwidget)
        self.sb.setMinimumSize(QtCore.QSize(52, 52))
        self.sb.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb.setFont(font)
        self.sb.setObjectName(_fromUtf8("sb"))
        self.gridLayout.addWidget(self.sb, 4, 14, 1, 1)
        self.po = QtGui.QPushButton(self.centralwidget)
        self.po.setMinimumSize(QtCore.QSize(52, 52))
        self.po.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.po.setFont(font)
        self.po.setObjectName(_fromUtf8("po"))
        self.gridLayout.addWidget(self.po, 5, 15, 1, 1)
        self.bi = QtGui.QPushButton(self.centralwidget)
        self.bi.setMinimumSize(QtCore.QSize(52, 52))
        self.bi.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bi.setFont(font)
        self.bi.setObjectName(_fromUtf8("bi"))
        self.gridLayout.addWidget(self.bi, 5, 14, 1, 1)
        self.pd = QtGui.QPushButton(self.centralwidget)
        self.pd.setMinimumSize(QtCore.QSize(52, 52))
        self.pd.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pd.setFont(font)
        self.pd.setObjectName(_fromUtf8("pd"))
        self.gridLayout.addWidget(self.pd, 4, 9, 1, 1)
        self.pb = QtGui.QPushButton(self.centralwidget)
        self.pb.setMinimumSize(QtCore.QSize(52, 52))
        self.pb.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb.setFont(font)
        self.pb.setObjectName(_fromUtf8("pb"))
        self.gridLayout.addWidget(self.pb, 5, 13, 1, 1)
        self.tl = QtGui.QPushButton(self.centralwidget)
        self.tl.setMinimumSize(QtCore.QSize(52, 52))
        self.tl.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tl.setFont(font)
        self.tl.setObjectName(_fromUtf8("tl"))
        self.gridLayout.addWidget(self.tl, 5, 12, 1, 1)
        self.hg = QtGui.QPushButton(self.centralwidget)
        self.hg.setMinimumSize(QtCore.QSize(52, 52))
        self.hg.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hg.setFont(font)
        self.hg.setObjectName(_fromUtf8("hg"))
        self.gridLayout.addWidget(self.hg, 5, 11, 1, 1)
        self.tc = QtGui.QPushButton(self.centralwidget)
        self.tc.setMinimumSize(QtCore.QSize(52, 52))
        self.tc.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tc.setFont(font)
        self.tc.setObjectName(_fromUtf8("tc"))
        self.gridLayout.addWidget(self.tc, 4, 6, 1, 1)
        self.au = QtGui.QPushButton(self.centralwidget)
        self.au.setMinimumSize(QtCore.QSize(52, 52))
        self.au.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.au.setFont(font)
        self.au.setObjectName(_fromUtf8("au"))
        self.gridLayout.addWidget(self.au, 5, 10, 1, 1)
        self.pt = QtGui.QPushButton(self.centralwidget)
        self.pt.setMinimumSize(QtCore.QSize(52, 52))
        self.pt.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pt.setFont(font)
        self.pt.setObjectName(_fromUtf8("pt"))
        self.gridLayout.addWidget(self.pt, 5, 9, 1, 1)
        self.y = QtGui.QPushButton(self.centralwidget)
        self.y.setMinimumSize(QtCore.QSize(52, 52))
        self.y.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.y.setFont(font)
        self.y.setObjectName(_fromUtf8("y"))
        self.gridLayout.addWidget(self.y, 4, 2, 1, 1)
        self.ir = QtGui.QPushButton(self.centralwidget)
        self.ir.setMinimumSize(QtCore.QSize(52, 52))
        self.ir.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ir.setFont(font)
        self.ir.setObjectName(_fromUtf8("ir"))
        self.gridLayout.addWidget(self.ir, 5, 8, 1, 1)
        self.os = QtGui.QPushButton(self.centralwidget)
        self.os.setMinimumSize(QtCore.QSize(52, 52))
        self.os.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.os.setFont(font)
        self.os.setObjectName(_fromUtf8("os"))
        self.gridLayout.addWidget(self.os, 5, 7, 1, 1)
        self.sn = QtGui.QPushButton(self.centralwidget)
        self.sn.setMinimumSize(QtCore.QSize(52, 52))
        self.sn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sn.setFont(font)
        self.sn.setObjectName(_fromUtf8("sn"))
        self.gridLayout.addWidget(self.sn, 4, 13, 1, 1)
        self.re = QtGui.QPushButton(self.centralwidget)
        self.re.setMinimumSize(QtCore.QSize(52, 52))
        self.re.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.re.setFont(font)
        self.re.setObjectName(_fromUtf8("re"))
        self.gridLayout.addWidget(self.re, 5, 6, 1, 1)
        self.w = QtGui.QPushButton(self.centralwidget)
        self.w.setMinimumSize(QtCore.QSize(52, 52))
        self.w.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w.setFont(font)
        self.w.setObjectName(_fromUtf8("w"))
        self.gridLayout.addWidget(self.w, 5, 5, 1, 1)
        self.rh = QtGui.QPushButton(self.centralwidget)
        self.rh.setMinimumSize(QtCore.QSize(52, 52))
        self.rh.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rh.setFont(font)
        self.rh.setObjectName(_fromUtf8("rh"))
        self.gridLayout.addWidget(self.rh, 4, 8, 1, 1)
        self.ta = QtGui.QPushButton(self.centralwidget)
        self.ta.setMinimumSize(QtCore.QSize(52, 52))
        self.ta.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ta.setFont(font)
        self.ta.setObjectName(_fromUtf8("ta"))
        self.gridLayout.addWidget(self.ta, 5, 4, 1, 1)
        self.n = QtGui.QPushButton(self.centralwidget)
        self.n.setMinimumSize(QtCore.QSize(52, 52))
        self.n.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.n.setFont(font)
        self.n.setObjectName(_fromUtf8("n"))
        self.gridLayout.addWidget(self.n, 1, 14, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.chemical_formula = QtGui.QLineEdit(self.centralwidget)
        self.chemical_formula.setMinimumSize(QtCore.QSize(300, 0))
        self.chemical_formula.setPlaceholderText(_fromUtf8(""))
        self.chemical_formula.setObjectName(_fromUtf8("chemical_formula"))
        self.horizontalLayout.addWidget(self.chemical_formula)
        self.clear_button = QtGui.QPushButton(self.centralwidget)
        self.clear_button.setMinimumSize(QtCore.QSize(30, 25))
        self.clear_button.setMaximumSize(QtCore.QSize(30, 25))
        self.clear_button.setText(_fromUtf8(""))
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.horizontalLayout.addWidget(self.clear_button)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cancel_button = QtGui.QPushButton(self.centralwidget)
        self.cancel_button.setObjectName(_fromUtf8("cancel_button"))
        self.horizontalLayout_3.addWidget(self.cancel_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.save_button = QtGui.QPushButton(self.centralwidget)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.horizontalLayout_3.addWidget(self.save_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.h, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.h_button)
        QtCore.QObject.connect(self.he, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.he_button)
        QtCore.QObject.connect(self.li, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.li_button)
        QtCore.QObject.connect(self.be, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.be_button)
        QtCore.QObject.connect(self.b, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.b_button)
        QtCore.QObject.connect(self.c, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.c_button)
        QtCore.QObject.connect(self.n, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.n_button)
        QtCore.QObject.connect(self.o, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.o_button)
        QtCore.QObject.connect(self.f, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.f_button)
        QtCore.QObject.connect(self.ne, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ne_button)
        QtCore.QObject.connect(self.na, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.na_button)
        QtCore.QObject.connect(self.mg, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.mg_button)
        QtCore.QObject.connect(self.al, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.al_button)
        QtCore.QObject.connect(self.si, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.si_button)
        QtCore.QObject.connect(self.p, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.p_button)
        QtCore.QObject.connect(self.s, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.s_button)
        QtCore.QObject.connect(self.cl, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cl_button)
        QtCore.QObject.connect(self.ar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ar_button)
        QtCore.QObject.connect(self.k, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.k_button)
        QtCore.QObject.connect(self.ca, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ca_button)
        QtCore.QObject.connect(self.sc, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sc_button)
        QtCore.QObject.connect(self.ti, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ti_button)
        QtCore.QObject.connect(self.v, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.v_button)
        QtCore.QObject.connect(self.cr, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cr_button)
        QtCore.QObject.connect(self.mn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.mn_button)
        QtCore.QObject.connect(self.fe, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.fe_button)
        QtCore.QObject.connect(self.co, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.co_button)
        QtCore.QObject.connect(self.ni, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ni_button)
        QtCore.QObject.connect(self.cu, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cu_button)
        QtCore.QObject.connect(self.zn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.zn_button)
        QtCore.QObject.connect(self.ga, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ga_button)
        QtCore.QObject.connect(self.ge, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ge_button)
        QtCore.QObject.connect(self.arsenic, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.as_button)
        QtCore.QObject.connect(self.se, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.se_button)
        QtCore.QObject.connect(self.br, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.br_button)
        QtCore.QObject.connect(self.kr, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.kr_button)
        QtCore.QObject.connect(self.rb, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.rb_button)
        QtCore.QObject.connect(self.sr, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sr_button)
        QtCore.QObject.connect(self.y, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.y_button)
        QtCore.QObject.connect(self.zr, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.zr_button)
        QtCore.QObject.connect(self.nb, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.nb_button)
        QtCore.QObject.connect(self.mo, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.mo_button)
        QtCore.QObject.connect(self.tc, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.tc_button)
        QtCore.QObject.connect(self.ru, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ru_button)
        QtCore.QObject.connect(self.rh, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.rh_button)
        QtCore.QObject.connect(self.pd, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.pd_button)
        QtCore.QObject.connect(self.ag, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ag_button)
        QtCore.QObject.connect(self.cd, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cd_button)
        QtCore.QObject.connect(self.indium, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.in_button)
        QtCore.QObject.connect(self.sn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sn_button)
        QtCore.QObject.connect(self.sb, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sb_button)
        QtCore.QObject.connect(self.te, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.te_button)
        QtCore.QObject.connect(self.i, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.i_button)
        QtCore.QObject.connect(self.xe, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.xe_button)
        QtCore.QObject.connect(self.cs, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cs_button)
        QtCore.QObject.connect(self.ba, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ba_button)
        QtCore.QObject.connect(self.lu, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.lu_button)
        QtCore.QObject.connect(self.hf, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.hf_button)
        QtCore.QObject.connect(self.ta, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ta_button)
        QtCore.QObject.connect(self.w, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.w_button)
        QtCore.QObject.connect(self.re, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.re_button)
        QtCore.QObject.connect(self.os, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.os_button)
        QtCore.QObject.connect(self.ir, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ir_button)
        QtCore.QObject.connect(self.pt, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.pt_button)
        QtCore.QObject.connect(self.au, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.au_button)
        QtCore.QObject.connect(self.hg, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.hg_button)
        QtCore.QObject.connect(self.tl, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.tl_button)
        QtCore.QObject.connect(self.pb, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.pb_button)
        QtCore.QObject.connect(self.bi, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.bi_button)
        QtCore.QObject.connect(self.po, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.po_button)
        QtCore.QObject.connect(self.at, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.at_button)
        QtCore.QObject.connect(self.rn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.rn_button)
        QtCore.QObject.connect(self.fr, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.fr_button)
        QtCore.QObject.connect(self.ra, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ra_button)
        QtCore.QObject.connect(self.lr, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.lr_button)
        QtCore.QObject.connect(self.rf, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.rf_button)
        QtCore.QObject.connect(self.db, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.db_button)
        QtCore.QObject.connect(self.sg, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.sg_button)
        QtCore.QObject.connect(self.bh, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.bh_button)
        QtCore.QObject.connect(self.hs, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.hs_button)
        QtCore.QObject.connect(self.mt, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.mt_button)
        QtCore.QObject.connect(self.ds, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ds_button)
        QtCore.QObject.connect(self.rg, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.rg_button)
        QtCore.QObject.connect(self.cn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cn_button)
        QtCore.QObject.connect(self.nh, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.nh_button)
        QtCore.QObject.connect(self.fl, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.fl_button)
        QtCore.QObject.connect(self.mc, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.mc_button)
        QtCore.QObject.connect(self.lv, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.lv_button)
        QtCore.QObject.connect(self.ts, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ts_button)
        QtCore.QObject.connect(self.og, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.og_button)
        QtCore.QObject.connect(self.cancel_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cancel)
        QtCore.QObject.connect(self.save_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ok)
        QtCore.QObject.connect(self.clear_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.reset_text_field)
        QtCore.QObject.connect(self.chemical_formula, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainWindow.chemical_formula_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.ba.setText(_translate("MainWindow", "Ba", None))
        self.ti.setText(_translate("MainWindow", "Ti", None))
        self.si.setText(_translate("MainWindow", "Si", None))
        self.k.setText(_translate("MainWindow", "K", None))
        self.p.setText(_translate("MainWindow", "P", None))
        self.b.setText(_translate("MainWindow", "B", None))
        self.cl.setText(_translate("MainWindow", "Cl", None))
        self.al.setText(_translate("MainWindow", "Al", None))
        self.sc.setText(_translate("MainWindow", "Sc", None))
        self.ne.setText(_translate("MainWindow", "Ne", None))
        self.ca.setText(_translate("MainWindow", "Ca", None))
        self.ni.setText(_translate("MainWindow", "Ni", None))
        self.s.setText(_translate("MainWindow", "S", None))
        self.mg.setText(_translate("MainWindow", "Mg", None))
        self.i.setText(_translate("MainWindow", "I", None))
        self.be.setText(_translate("MainWindow", "Be", None))
        self.kr.setText(_translate("MainWindow", "Kr", None))
        self.fe.setText(_translate("MainWindow", "Fe", None))
        self.br.setText(_translate("MainWindow", "Br", None))
        self.h.setText(_translate("MainWindow", "H", None))
        self.co.setText(_translate("MainWindow", "Co", None))
        self.ge.setText(_translate("MainWindow", "Ge", None))
        self.zn.setText(_translate("MainWindow", "Zn", None))
        self.v.setText(_translate("MainWindow", "V", None))
        self.na.setText(_translate("MainWindow", "Na", None))
        self.cr.setText(_translate("MainWindow", "Cr", None))
        self.mn.setText(_translate("MainWindow", "Mn", None))
        self.ar.setText(_translate("MainWindow", "Ar", None))
        self.ga.setText(_translate("MainWindow", "Ga", None))
        self.li.setText(_translate("MainWindow", "Li", None))
        self.he.setText(_translate("MainWindow", "He", None))
        self.cu.setText(_translate("MainWindow", "Cu", None))
        self.c.setText(_translate("MainWindow", "C", None))
        self.o.setText(_translate("MainWindow", "O", None))
        self.f.setText(_translate("MainWindow", "F", None))
        self.hf.setText(_translate("MainWindow", "Hf", None))
        self.lu.setText(_translate("MainWindow", "Lu", None))
        self.nb.setText(_translate("MainWindow", "Nb", None))
        self.se.setText(_translate("MainWindow", "Se", None))
        self.arsenic.setText(_translate("MainWindow", "As", None))
        self.ag.setText(_translate("MainWindow", "Ag", None))
        self.sr.setText(_translate("MainWindow", "Sr", None))
        self.zr.setText(_translate("MainWindow", "Zr", None))
        self.rb.setText(_translate("MainWindow", "Rb", None))
        self.og.setText(_translate("MainWindow", "Og", None))
        self.ts.setText(_translate("MainWindow", "Ts", None))
        self.lv.setText(_translate("MainWindow", "Lv", None))
        self.mc.setText(_translate("MainWindow", "Mc", None))
        self.cd.setText(_translate("MainWindow", "Cd", None))
        self.fl.setText(_translate("MainWindow", "Fl", None))
        self.nh.setText(_translate("MainWindow", "Nh", None))
        self.cs.setText(_translate("MainWindow", "Cs", None))
        self.cn.setText(_translate("MainWindow", "Cn", None))
        self.rg.setText(_translate("MainWindow", "Rg", None))
        self.ru.setText(_translate("MainWindow", "Ru", None))
        self.ds.setText(_translate("MainWindow", "Ds", None))
        self.mt.setText(_translate("MainWindow", "Mt", None))
        self.indium.setText(_translate("MainWindow", "In", None))
        self.hs.setText(_translate("MainWindow", "Hs", None))
        self.bh.setText(_translate("MainWindow", "Bh", None))
        self.te.setText(_translate("MainWindow", "Te", None))
        self.sg.setText(_translate("MainWindow", "Sg", None))
        self.db.setText(_translate("MainWindow", "Db", None))
        self.mo.setText(_translate("MainWindow", "Mo", None))
        self.rf.setText(_translate("MainWindow", "Rf", None))
        self.lr.setText(_translate("MainWindow", "Lr", None))
        self.xe.setText(_translate("MainWindow", "Xe", None))
        self.ra.setText(_translate("MainWindow", "Ra", None))
        self.fr.setText(_translate("MainWindow", "Fr", None))
        self.rn.setText(_translate("MainWindow", "Rn", None))
        self.at.setText(_translate("MainWindow", "At", None))
        self.sb.setText(_translate("MainWindow", "Sb", None))
        self.po.setText(_translate("MainWindow", "Po", None))
        self.bi.setText(_translate("MainWindow", "Bi", None))
        self.pd.setText(_translate("MainWindow", "Pd", None))
        self.pb.setText(_translate("MainWindow", "Pb", None))
        self.tl.setText(_translate("MainWindow", "Tl", None))
        self.hg.setText(_translate("MainWindow", "Hg", None))
        self.tc.setText(_translate("MainWindow", "Tc", None))
        self.au.setText(_translate("MainWindow", "Au", None))
        self.pt.setText(_translate("MainWindow", "Pt", None))
        self.y.setText(_translate("MainWindow", "Y", None))
        self.ir.setText(_translate("MainWindow", "Ir", None))
        self.os.setText(_translate("MainWindow", "Os", None))
        self.sn.setText(_translate("MainWindow", "Sn", None))
        self.re.setText(_translate("MainWindow", "Re", None))
        self.w.setText(_translate("MainWindow", "W", None))
        self.rh.setText(_translate("MainWindow", "Rh", None))
        self.ta.setText(_translate("MainWindow", "Ta", None))
        self.n.setText(_translate("MainWindow", "N", None))
        self.label.setText(_translate("MainWindow", "Chemical Formula: ", None))
        self.label_2.setText(_translate("MainWindow", "(Li7)2 (O16)3 (Sb103) C", None))
        self.cancel_button.setText(_translate("MainWindow", "Cancel", None))
        self.save_button.setText(_translate("MainWindow", "Save", None))

