# load information from setup.cfg/setup.py
{% set data = load_setup_py_data() %}
{% set license = data.get('license') %}
{% set description = data.get('description') %}
{% set url = data.get('url') %}
# this will reproduce the version from tags to match versioningit
{% set version = environ.get('VERSION') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}

package:
  name: "addie"
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: {{ version_number }}
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit

  build:
    - configparser
    - mantid-total-scattering-python-wrapper
    - mantidworkbench
    - periodictable
    - psutil
    - python
    - pystog
    - setuptools
    - simplejson
    - versioningit

  run:
    - configparser
    - mantid-total-scattering-python-wrapper
    - mantidworkbench
    - periodictable
    - psutil
    - python
    - pystog
    - simplejson
    - pyoncat

test:
  imports:
    - addie

about:
  home: {{ url }}
  license: {{ license }}
  license_family: MIT
  license_file: ../LICENSE
  summary: {{ description }}

extra:
  recipe-maintainers:
    - JeanBilheux
    - marshallmcdonnell
    - peterfpeterson
