# this will reproduce the version from tags to match versioningit
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}

package:
  name: "addie"
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: {{ version_number }}
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit

  build:
    - configparser
    - mantid-total-scattering-python-wrapper
    - mantidworkbench
    - periodictable
    - psutil
    - python
    - pystog
    - setuptools
    - simplejson
    - versioningit

  run:
    - configparser
    - mantid-total-scattering-python-wrapper
    - mantidworkbench
    - periodictable
    - psutil
    - python
    - pystog
    - simplejson

test:
  imports:
    - addie

about:
  home: https://github.com/neutrons/addie
  license: GPL (version 3)
  license_family: GPL3
  license_file: ../LICENSE
  summary: ADvanced DIffraction Environment

extra:
  recipe-maintainers:
    - JeanBilheux
    - marshallmcdonnell
    - peterfpeterson
